# Generated by Django 4.2.21 on 2025-08-14 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="مفتاح الجلسة"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="معلومات المتصفح"),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الدخول"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="آخر نشاط"),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الخروج"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "سطح المكتب"),
                            ("mobile", "هاتف محمول"),
                            ("tablet", "جهاز لوحي"),
                            ("unknown", "غير معروف"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="نوع الجهاز",
                    ),
                ),
                (
                    "browser",
                    models.CharField(blank=True, max_length=50, verbose_name="المتصفح"),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نظام التشغيل"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_user_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "💻 جلسة مستخدم",
                "verbose_name_plural": "💻 جلسات المستخدمين",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="UserLoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الدخول"),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الخروج"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="معلومات المتصفح"),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="مفتاح الجلسة"),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المتصفح"
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نظام التشغيل"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "سطح المكتب"),
                            ("mobile", "هاتف محمول"),
                            ("tablet", "جهاز لوحي"),
                            ("unknown", "غير معروف"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="نوع الجهاز",
                    ),
                ),
                (
                    "pages_visited",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد الصفحات المزارة"
                    ),
                ),
                (
                    "actions_performed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد العمليات المنجزة"
                    ),
                ),
                (
                    "is_successful_login",
                    models.BooleanField(default=True, verbose_name="تسجيل دخول ناجح"),
                ),
                (
                    "logout_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "خروج يدوي"),
                            ("timeout", "انتهاء المهلة"),
                            ("forced", "خروج قسري"),
                            ("system", "خروج النظام"),
                            ("unknown", "غير معروف"),
                        ],
                        default="unknown",
                        max_length=50,
                        verbose_name="سبب الخروج",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_login_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "🔐 سجل دخول",
                "verbose_name_plural": "🔐 سجلات الدخول",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "تسجيل دخول"),
                            ("logout", "تسجيل خروج"),
                            ("view", "عرض صفحة"),
                            ("create", "إنشاء"),
                            ("update", "تحديث"),
                            ("delete", "حذف"),
                            ("search", "بحث"),
                            ("export", "تصدير"),
                            ("import", "استيراد"),
                            ("download", "تحميل"),
                            ("upload", "رفع ملف"),
                            ("print", "طباعة"),
                            ("email", "إرسال بريد إلكتروني"),
                            ("api_call", "استدعاء API"),
                            ("error", "خطأ"),
                            ("security", "أمان"),
                            ("admin", "إدارة"),
                            ("report", "تقرير"),
                            ("backup", "نسخ احتياطي"),
                            ("restore", "استعادة"),
                            ("maintenance", "صيانة"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("user", "مستخدم"),
                            ("customer", "عميل"),
                            ("order", "طلب"),
                            ("product", "منتج"),
                            ("inspection", "معاينة"),
                            ("manufacturing", "تصنيع"),
                            ("installation", "تركيب"),
                            ("complaint", "شكوى"),
                            ("report", "تقرير"),
                            ("system", "نظام"),
                            ("file", "ملف"),
                            ("page", "صفحة"),
                            ("api", "واجهة برمجية"),
                            ("database", "قاعدة بيانات"),
                            ("other", "أخرى"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="نوع الكائن",
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="معرف الكائن"
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الكائن"
                    ),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "url_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسار الصفحة"
                    ),
                ),
                (
                    "http_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="طريقة HTTP"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="معلومات المتصفح"),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="الوقت"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="نجح")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="user_activity.usersession",
                        verbose_name="الجلسة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "📋 سجل نشاط",
                "verbose_name_plural": "📋 سجلات النشاط",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="OnlineUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="آخر ظهور"),
                ),
                (
                    "current_page",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="الصفحة الحالية"
                    ),
                ),
                (
                    "current_page_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان الصفحة الحالية"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="مفتاح الجلسة"),
                ),
                (
                    "device_info",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="معلومات الجهاز"
                    ),
                ),
                (
                    "pages_visited",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد الصفحات المزارة"
                    ),
                ),
                (
                    "actions_performed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد العمليات المنجزة"
                    ),
                ),
                ("login_time", models.DateTimeField(verbose_name="وقت الدخول")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_online_status",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "🟢 مستخدم نشط",
                "verbose_name_plural": "🟢 المستخدمون النشطون",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "-last_activity"], name="user_activi_user_id_9aa902_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["is_active"], name="user_activi_is_acti_babfd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_key"], name="user_activi_session_3b28d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["login_time"], name="user_activi_login_t_f7afba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginhistory",
            index=models.Index(
                fields=["user", "-login_time"], name="user_activi_user_id_375546_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginhistory",
            index=models.Index(
                fields=["login_time"], name="user_activi_login_t_f138b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginhistory",
            index=models.Index(
                fields=["ip_address"], name="user_activi_ip_addr_44f65a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginhistory",
            index=models.Index(
                fields=["is_successful_login"], name="user_activi_is_succ_dcb041_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["user", "-timestamp"], name="user_activi_user_id_d6238b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["action_type"], name="user_activi_action__48049f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["entity_type"], name="user_activi_entity__613158_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["timestamp"], name="user_activi_timesta_acc82a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["success"], name="user_activi_success_608dff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["ip_address"], name="user_activi_ip_addr_444a35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlineuser",
            index=models.Index(
                fields=["-last_seen"], name="user_activi_last_se_39aa58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlineuser",
            index=models.Index(
                fields=["session_key"], name="user_activi_session_30a4ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlineuser",
            index=models.Index(fields=["user"], name="user_activi_user_id_799f88_idx"),
        ),
    ]
