# Generated by Django 6.0 on 2025-12-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_activity", "0002_fix_session_foreign_key"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="useractivitylog",
            name="user_activity_session_idx",
        ),
    ]
