# Generated by Django 6.0 on 2026-01-17 10:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("manufacturing", "0028_alter_manufacturingorderitem_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FactoryCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("reviewing", "قيد المراجعة"),
                            ("completed", "مكتمل"),
                            ("paid", "مدفوع"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "total_billable_meters",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="إجمالي الأمتار المستحقة",
                    ),
                ),
                (
                    "production_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="التاريخ الذي أصبح فيه الأمر جاهزاً أو مكتملاً",
                        null=True,
                        verbose_name="تاريخ الإنتاج",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_factory_cards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "manufacturing_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_card",
                        to="manufacturing.manufacturingorder",
                        verbose_name="أمر التصنيع",
                    ),
                ),
            ],
            options={
                "verbose_name": "بطاقة المصنع",
                "verbose_name_plural": "بطاقات المصنع",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="الحالة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="التاريخ والوقت",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التغيير بواسطة",
                    ),
                ),
                (
                    "manufacturing_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_status_logs",
                        to="manufacturing.manufacturingorder",
                        verbose_name="أمر التصنيع",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حالة الإنتاج",
                "verbose_name_plural": "سجلات حالات الإنتاج",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Tailor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="الاسم"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("tailor", "خياط"), ("cutter", "قصاص")],
                        default="tailor",
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tailors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "خياط/قصاص",
                "verbose_name_plural": "الخياطين والقصاصين",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CardMeasurementSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="الكمية المخصصة (متر)",
                    ),
                ),
                (
                    "unit_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="السعر للمتر",
                    ),
                ),
                (
                    "monetary_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="القيمة المالية",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="مدفوع"
                    ),
                ),
                (
                    "paid_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الدفع"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "factory_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="factory_accounting.factorycard",
                        verbose_name="بطاقة المصنع",
                    ),
                ),
                (
                    "tailor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="factory_accounting.tailor",
                        verbose_name="الخياط/القصاص",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقسيم القياسات",
                "verbose_name_plural": "تقسيمات القياسات",
                "ordering": ["factory_card", "tailor"],
            },
        ),
        migrations.AddIndex(
            model_name="factorycard",
            index=models.Index(fields=["status"], name="factcard_status_idx"),
        ),
        migrations.AddIndex(
            model_name="factorycard",
            index=models.Index(
                fields=["production_date"], name="factcard_proddate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factorycard",
            index=models.Index(fields=["-created_at"], name="factcard_created_idx"),
        ),
        migrations.AddIndex(
            model_name="productionstatuslog",
            index=models.Index(
                fields=["manufacturing_order", "status"],
                name="prodlog_order_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productionstatuslog",
            index=models.Index(fields=["timestamp"], name="prodlog_timestamp_idx"),
        ),
        migrations.AddIndex(
            model_name="tailor",
            index=models.Index(fields=["name"], name="tailor_name_idx"),
        ),
        migrations.AddIndex(
            model_name="tailor",
            index=models.Index(fields=["is_active"], name="tailor_active_idx"),
        ),
        migrations.AddIndex(
            model_name="cardmeasurementsplit",
            index=models.Index(
                fields=["factory_card", "tailor"], name="split_card_tailor_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cardmeasurementsplit",
            index=models.Index(fields=["is_paid"], name="split_paid_idx"),
        ),
    ]
