# Generated by Django 6.0 on 2026-01-17 10:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tailor",
            name="default_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="السعر الافتراضي الذي يتم استخدامه عند تعيين هذا الخياط",
                max_digits=10,
                verbose_name="السعر الافتراضي للمتر",
            ),
        ),
    ]
