# Generated by Django 6.0 on 2026-01-17 10:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0002_tailor_default_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardmeasurementsplit",
            name="share_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="عدد الأمتار المخصصة للخياط",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="الكمية المخصصة (متر)",
            ),
        ),
        migrations.AlterField(
            model_name="cardmeasurementsplit",
            name="unit_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="يتم جلبه تلقائياً من إعدادات الخياط",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="السعر للمتر",
            ),
        ),
        migrations.AlterField(
            model_name="tailor",
            name="default_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="السعر الثابت الذي يتم استخدامه لحساب المستحقات (ر.س/متر)",
                max_digits=10,
                verbose_name="السعر للمتر",
            ),
        ),
    ]
