# Generated by Django 6.0 on 2026-01-17 10:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0003_alter_cardmeasurementsplit_share_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactoryAccountingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "include_belts",
                    models.BooleanField(
                        default=False,
                        help_text="تضمين الأحزمة في حساب إجمالي الأمتار",
                        verbose_name="احتساب الأحزمة",
                    ),
                ),
                (
                    "include_trims",
                    models.BooleanField(
                        default=True,
                        help_text="تضمين الكشاكيش في حساب إجمالي الأمتار",
                        verbose_name="احتساب الكشاكيش",
                    ),
                ),
                (
                    "include_ribbons",
                    models.BooleanField(
                        default=True,
                        help_text="تضمين الشرائط في حساب إجمالي الأمتار",
                        verbose_name="احتساب الشرائط",
                    ),
                ),
                (
                    "default_rate_per_meter",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="السعر الافتراضي المستخدم للخياطين الذين لا يملكون سعر مخصص",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="السعر الافتراضي للمتر",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "إعدادات حسابات المصنع",
                "verbose_name_plural": "إعدادات حسابات المصنع",
            },
        ),
        migrations.AddField(
            model_name="tailor",
            name="use_custom_rate",
            field=models.BooleanField(
                default=False,
                help_text="إذا كان محدداً، سيتم استخدام السعر المخصص أدناه. وإلا سيتم استخدام السعر العام من الإعدادات",
                verbose_name="استخدام سعر مخصص",
            ),
        ),
        migrations.AlterField(
            model_name="tailor",
            name="default_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="السعر المخصص لهذا الخياط (اتركه فارغاً لاستخدام السعر العام)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="السعر المخصص للمتر",
            ),
        ),
    ]
