# Generated by Django 6.0 on 2026-01-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "factory_accounting",
            "0004_factoryaccountingsettings_tailor_use_custom_rate_and_more",
        ),
        ("orders", "0087_remove_fabric_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factoryaccountingsettings",
            name="include_belts",
        ),
        migrations.RemoveField(
            model_name="factoryaccountingsettings",
            name="include_ribbons",
        ),
        migrations.RemoveField(
            model_name="factoryaccountingsettings",
            name="include_trims",
        ),
        migrations.AddField(
            model_name="factoryaccountingsettings",
            name="excluded_tailoring_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="حدد أنواع التفصيل التي يجب استبعادها من حساب إجمالي الأمتار (مثل: الأحزمة)",
                limit_choices_to={"field_type": "tailoring_type", "is_active": True},
                to="orders.wizardfieldoption",
                verbose_name="أنواع التفصيل المستبعدة",
            ),
        ),
    ]
