# Generated by Django 6.0 on 2026-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "factory_accounting",
            "0005_remove_factoryaccountingsettings_include_belts_and_more",
        ),
        ("inventory", "0028_add_material_width_to_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factoryaccountingsettings",
            name="excluded_tailoring_types",
        ),
        migrations.AddField(
            model_name="factoryaccountingsettings",
            name="excluded_fabrics",
            field=models.ManyToManyField(
                blank=True,
                help_text="حدد أنواع الأقمشة التي يجب استبعادها من حساب إجمالي الأمتار (مثل: الأحزمة، الكشاكيش، إلخ)",
                limit_choices_to={"is_active": True},
                to="inventory.product",
                verbose_name="الأقمشة المستبعدة",
            ),
        ),
    ]
