# Generated by Django 6.0 on 2026-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "factory_accounting",
            "0006_remove_factoryaccountingsettings_excluded_tailoring_types_and_more",
        ),
        ("inventory", "0028_add_material_width_to_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factoryaccountingsettings",
            name="excluded_fabrics",
            field=models.ManyToManyField(
                blank=True,
                help_text="حدد أنواع الأقمشة التي يجب استبعادها من حساب إجمالي الأمتار (مثل: الأحزمة، الكشاكيش، إلخ)",
                to="inventory.product",
                verbose_name="الأقمشة المستبعدة",
            ),
        ),
    ]
