# Generated by Django 6.0 on 2026-01-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0007_alter_factoryaccountingsettings_excluded_fabrics"),
        ("orders", "0087_remove_fabric_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factoryaccountingsettings",
            name="excluded_fabrics",
        ),
        migrations.AddField(
            model_name="factoryaccountingsettings",
            name="excluded_fabric_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="حدد أنواع الأقمشة التي يجب استبعادها من حساب إجمالي الأمتار (مثل: الأحزمة، الكشاكيش، إلخ)",
                limit_choices_to={"field_type": "fabric_type", "is_active": True},
                to="orders.wizardfieldoption",
                verbose_name="أنواع الأقمشة المستبعدة",
            ),
        ),
    ]
