# Generated by Django 6.0 on 2026-01-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "factory_accounting",
            "0008_remove_factoryaccountingsettings_excluded_fabrics_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE factory_accounting_tailor DROP COLUMN IF EXISTS payment_type;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
