# Generated by Django 6.0 on 2026-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0009_remove_payment_type_column"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE factory_accounting_cardmeasurementsplit DROP COLUMN IF EXISTS payment_type;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
