# Generated by Django 6.0 on 2026-01-17 12:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0010_remove_payment_type_from_split"),
        ("orders", "0087_remove_fabric_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="factoryaccountingsettings",
            name="double_meter_tailoring_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="حدد أنواع التفصيل التي يجب مضاعفة أمتارها في الحساب (مثل: كابتونيه، بليسيه)",
                limit_choices_to={"field_type": "tailoring_type", "is_active": True},
                related_name="double_meter_settings",
                to="orders.wizardfieldoption",
                verbose_name="أنواع التفصيل بأمتار مضاعفة",
            ),
        ),
        migrations.AddField(
            model_name="factorycard",
            name="total_double_meters",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="مجموع الأمتار بعد تطبيق المضاعفة لأنواع التفصيل المحددة",
                max_digits=10,
                verbose_name="إجمالي الأمتار (مضاعف)",
            ),
        ),
    ]
