# Generated by Django 6.0 on 2026-01-17 12:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0011_add_double_meter_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="factoryaccountingsettings",
            name="default_cutter_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="السعر الافتراضي لمتر القص",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="السعر الافتراضي للمتر (قصاص)",
            ),
        ),
        migrations.AddField(
            model_name="factorycard",
            name="cutter_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="سعر المتر للقصاص في هذا الأمر",
                max_digits=10,
                verbose_name="سعر متر القصاص",
            ),
        ),
        migrations.AddField(
            model_name="factorycard",
            name="total_cutter_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="إجمالي الأمتار الفعلية × سعر القصاص",
                max_digits=10,
                verbose_name="إجمالي تكلفة القصاص",
            ),
        ),
        migrations.AlterField(
            model_name="factoryaccountingsettings",
            name="default_rate_per_meter",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="السعر الافتراضي المستخدم للخياطين الذين لا يملكون سعر مخصص",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="السعر الافتراضي للمتر (خياط)",
            ),
        ),
    ]
