# Generated by Django 6.0 on 2026-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0012_add_cutter_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="factorycard",
            name="payment_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="تاريخ سداد المستحقات",
                null=True,
                verbose_name="تاريخ الدفع",
            ),
        ),
    ]
