# Generated by Django 5.1.5 on 2026-02-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0013_factorycard_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionstatuslog",
            name="previous_status",
            field=models.CharField(
                blank=True,
                help_text="الحالة قبل التغيير",
                max_length=30,
                verbose_name="الحالة السابقة",
            ),
        ),
    ]
