# Generated by Django 5.1.5 on 2026-02-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0014_productionstatuslog_previous_status"),
        ("manufacturing", "0032_manufacturingorder_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factorycard",
            name="manufacturing_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factory_card",
                to="manufacturing.manufacturingorder",
                verbose_name="أمر التصنيع",
            ),
        ),
    ]
