# Generated by Django 5.1.15 on 2026-02-15 14:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0015_alter_factorycard_manufacturing_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardmeasurementsplit",
            name="monetary_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="القيمة المالية",
            ),
        ),
        migrations.AlterField(
            model_name="cardmeasurementsplit",
            name="share_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="عدد الأمتار المخصصة للخياط",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="الكمية المخصصة (متر)",
            ),
        ),
        migrations.AlterField(
            model_name="cardmeasurementsplit",
            name="unit_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="يتم جلبه تلقائياً من إعدادات الخياط",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="السعر للمتر",
            ),
        ),
        migrations.AlterField(
            model_name="factoryaccountingsettings",
            name="default_cutter_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="السعر الافتراضي لمتر القص",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="السعر الافتراضي للمتر (قصاص)",
            ),
        ),
        migrations.AlterField(
            model_name="factoryaccountingsettings",
            name="default_rate_per_meter",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="السعر الافتراضي المستخدم للخياطين الذين لا يملكون سعر مخصص",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="السعر الافتراضي للمتر (خياط)",
            ),
        ),
        migrations.AlterField(
            model_name="factorycard",
            name="cutter_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="سعر المتر للقصاص في هذا الأمر",
                max_digits=15,
                verbose_name="سعر متر القصاص",
            ),
        ),
        migrations.AlterField(
            model_name="factorycard",
            name="total_billable_meters",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="إجمالي الأمتار المستحقة",
            ),
        ),
        migrations.AlterField(
            model_name="factorycard",
            name="total_cutter_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="إجمالي الأمتار الفعلية × سعر القصاص",
                max_digits=15,
                verbose_name="إجمالي تكلفة القصاص",
            ),
        ),
        migrations.AlterField(
            model_name="factorycard",
            name="total_double_meters",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="مجموع الأمتار بعد تطبيق المضاعفة لأنواع التفصيل المحددة",
                max_digits=12,
                verbose_name="إجمالي الأمتار (مضاعف)",
            ),
        ),
        migrations.AlterField(
            model_name="tailor",
            name="default_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="السعر المخصص لهذا الخياط (اتركه فارغاً لاستخدام السعر العام)",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="السعر المخصص للمتر",
            ),
        ),
    ]
