# Generated by Django 5.1.15 on 2026-03-02 14:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0016_standardize_decimal_precision"),
        ("orders", "0103_accessory_3_checkboxes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factoryaccountingsettings",
            name="double_meter_tailoring_types",
        ),
        migrations.RemoveField(
            model_name="factorycard",
            name="total_double_meters",
        ),
        migrations.AddField(
            model_name="factorycard",
            name="tailoring_cost_breakdown",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="تفصيل التكلفة لكل نوع تفصيل",
                verbose_name="تفاصيل تكلفة التفصيل",
            ),
        ),
        migrations.AddField(
            model_name="factorycard",
            name="total_tailoring_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="مجموع تكاليف كل الأقمشة حسب تسعير نوع التفصيل",
                max_digits=15,
                verbose_name="إجمالي تكلفة التفصيل المقدّرة",
            ),
        ),
        migrations.CreateModel(
            name="TailoringTypePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="السعر لكل متر أو لكل قطعة حسب طريقة الحساب",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="السعر",
                    ),
                ),
                (
                    "calc_method",
                    models.CharField(
                        choices=[
                            ("per_meter", "بالمتر"),
                            ("per_piece", "بالعدد (قطعة)"),
                        ],
                        default="per_meter",
                        max_length=20,
                        verbose_name="طريقة الحساب",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "tailoring_type",
                    models.OneToOneField(
                        limit_choices_to={
                            "field_type": "tailoring_type",
                            "is_active": True,
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_pricing",
                        to="orders.wizardfieldoption",
                        verbose_name="نوع التفصيل",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسعير نوع التفصيل",
                "verbose_name_plural": "تسعير أنواع التفصيل",
                "ordering": [
                    "tailoring_type__sequence",
                    "tailoring_type__display_name",
                ],
            },
        ),
    ]
