# Generated by Django 5.1.15 on 2026-03-04 14:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "factory_accounting",
            "0017_remove_factoryaccountingsettings_double_meter_tailoring_types_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadyCurtainEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="عدد الستائر",
                    ),
                ),
                (
                    "price_per_piece",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="سعر القطعة",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="يتم حسابها تلقائياً: عدد الستائر × سعر القطعة",
                        max_digits=15,
                        verbose_name="التكلفة الإجمالية",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="وصف / ملاحظات"
                    ),
                ),
                (
                    "production_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاريخ الإنتاج",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="مدفوع"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الدفع"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ready_curtains",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "tailor",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "role": "tailor"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ready_curtain_entries",
                        to="factory_accounting.tailor",
                        verbose_name="الخياط",
                    ),
                ),
            ],
            options={
                "verbose_name": "ستائر جاهزة",
                "verbose_name_plural": "ستائر جاهزة",
                "ordering": ["-production_date", "-created_at"],
            },
        ),
    ]
