# Generated by Django 5.1.15 on 2026-03-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0018_readycurtainentry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factorycard",
            options={
                "ordering": ["-created_at"],
                "permissions": [("view_factory_reports", "عرض تقارير حسابات المصنع")],
                "verbose_name": "بطاقة المصنع",
                "verbose_name_plural": "بطاقات المصنع",
            },
        ),
    ]
