# Generated by Django 6.0 on 2026-01-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardWidgetSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("revenue_chart", "مخطط الإيرادات"),
                            ("inventory_chart", "مخطط المخزون"),
                            ("staff_performance", "أداء الموظفين"),
                            ("debt_analytics", "تحليل الديون"),
                            ("kpi_revenue", "KPI: الإيرادات"),
                            ("kpi_cutting", "KPI: القص"),
                            ("kpi_top_user", "KPI: أفضل موظف"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="اسم الودجت",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="العنوان الظاهر"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="إعدادات إضافية"
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="القيمة المستهدفة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد ودجت اللوحة",
                "verbose_name_plural": "إعدادات ودجت اللوحة",
                "ordering": ["order"],
            },
        ),
    ]
