# Generated by Django 5.1.15 on 2026-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardwidgetsettings",
            name="target_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="القيمة المستهدفة",
            ),
        ),
    ]
