# Generated by Django 5.2.6 on 2025-11-29 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "إنشاء"),
                            ("UPDATE", "تحديث"),
                            ("DELETE", "حذف"),
                            ("LOGIN", "تسجيل دخول"),
                            ("LOGOUT", "تسجيل خروج"),
                            ("PERMISSION_CHANGE", "تغيير صلاحيات"),
                            ("SECURITY_EVENT", "حدث أمني"),
                            ("DATA_EXPORT", "تصدير بيانات"),
                            ("SETTINGS_CHANGE", "تغيير إعدادات"),
                        ],
                        max_length=50,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "معلومات"),
                            ("WARNING", "تحذير"),
                            ("ERROR", "خطأ"),
                            ("CRITICAL", "حرج"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="مستوى الخطورة",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="اسم النموذج"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(null=True, verbose_name="معرف الكائن"),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(null=True, verbose_name="عنوان IP"),
                ),
                ("user_agent", models.TextField(null=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="التاريخ والوقت"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, null=True, verbose_name="مفتاح الجلسة"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجلات التدقيق",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="core_auditl_timesta_189a84_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="core_auditl_user_id_2a1528_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="core_auditl_action_f07419_idx",
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"],
                        name="core_auditl_severit_890175_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_FAILED", "فشل تسجيل دخول"),
                            ("LOGIN_SUCCESS", "نجاح تسجيل دخول"),
                            ("BRUTE_FORCE", "محاولة Brute Force"),
                            ("SQL_INJECTION", "محاولة SQL Injection"),
                            ("XSS_ATTEMPT", "محاولة XSS"),
                            ("CSRF_FAILED", "فشل CSRF"),
                            ("RATE_LIMIT", "تجاوز Rate Limit"),
                            ("SUSPICIOUS_ACTIVITY", "نشاط مشبوه"),
                            ("PERMISSION_DENIED", "رفض صلاحيات"),
                        ],
                        max_length=50,
                        verbose_name="نوع الحدث",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                ("details", models.JSONField(default=dict, verbose_name="التفاصيل")),
                ("user_agent", models.TextField(null=True, verbose_name="User Agent")),
                ("url", models.URLField(max_length=500, null=True, verbose_name="URL")),
                (
                    "method",
                    models.CharField(
                        max_length=10, null=True, verbose_name="HTTP Method"
                    ),
                ),
                (
                    "blocked",
                    models.BooleanField(default=False, verbose_name="تم الحظر"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="التاريخ والوقت"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حدث أمني",
                "verbose_name_plural": "الأحداث الأمنية",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="core_securi_timesta_b9db08_idx"
                    ),
                    models.Index(
                        fields=["event_type", "-timestamp"],
                        name="core_securi_event_t_5d2273_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="core_securi_ip_addr_bc5740_idx",
                    ),
                ],
            },
        ),
    ]
