# Generated by Django 6.0 on 2026-01-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecycleBin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "سلة المحذوفات",
                "verbose_name_plural": "سلة المحذوفات",
                "managed": False,
            },
        ),
    ]
