# Generated by Django 5.1.5 on 2026-02-12 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_recyclebin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="app_label",
            field=models.CharField(blank=True, max_length=100, verbose_name="التطبيق"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="changed_fields",
            field=models.JSONField(
                blank=True,
                help_text="قائمة بأسماء الحقول التي تغيرت",
                null=True,
                verbose_name="الحقول المتغيرة",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="extra_data",
            field=models.JSONField(blank=True, null=True, verbose_name="بيانات إضافية"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="http_method",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="HTTP Method"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="object_repr",
            field=models.CharField(
                blank=True,
                help_text="تمثيل نصي للكائن وقت التسجيل",
                max_length=500,
                verbose_name="وصف الكائن",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="url_path",
            field=models.CharField(blank=True, max_length=500, verbose_name="المسار"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="يُحفظ كنسخة نصية في حال حذف المستخدم",
                max_length=150,
                verbose_name="اسم المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "إنشاء"),
                    ("UPDATE", "تحديث"),
                    ("DELETE", "حذف"),
                    ("LOGIN", "تسجيل دخول"),
                    ("LOGOUT", "تسجيل خروج"),
                    ("PERMISSION_CHANGE", "تغيير صلاحيات"),
                    ("SECURITY_EVENT", "حدث أمني"),
                    ("DATA_EXPORT", "تصدير بيانات"),
                    ("SETTINGS_CHANGE", "تغيير إعدادات"),
                    ("VIEW", "عرض"),
                    ("BULK_UPDATE", "تحديث جماعي"),
                    ("BULK_DELETE", "حذف جماعي"),
                ],
                max_length=50,
                verbose_name="نوع العملية",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="اسم النموذج"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="معرف الكائن"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="session_key",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="مفتاح الجلسة"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True, default="", verbose_name="User Agent"),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["app_label", "model_name", "-timestamp"],
                name="core_auditl_app_lab_f1c2f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["object_id", "model_name"],
                name="core_auditl_object__437891_idx",
            ),
        ),
    ]
