# Generated by Django 4.2.21 on 2025-08-28 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0007_alter_product_currency"),
        ("orders", "0026_orderitem_additional_quantity_orderitem_bag_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuttingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cutting_code",
                    models.CharField(
                        help_text="كود فريد لأمر التقطيع",
                        max_length=50,
                        unique=True,
                        verbose_name="كود التقطيع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("in_progress", "قيد التقطيع"),
                            ("completed", "مكتمل"),
                            ("partially_completed", "مكتمل جزئياً"),
                            ("cancelled", "ملغي"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة التقطيع",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ بدء التقطيع"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ اكتمال التقطيع"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "notifications_sent",
                    models.JSONField(
                        blank=True, default=list, verbose_name="الإشعارات المرسلة"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cutting_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مسؤول التقطيع",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutting_orders",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutting_orders",
                        to="inventory.warehouse",
                        verbose_name="المستودع",
                    ),
                ),
            ],
            options={
                "verbose_name": "أمر تقطيع",
                "verbose_name_plural": "أوامر التقطيع",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CuttingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "يومي"),
                            ("weekly", "أسبوعي"),
                            ("monthly", "شهري"),
                            ("yearly", "سنوي"),
                        ],
                        max_length=10,
                        verbose_name="نوع التقرير",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي الأوامر"
                    ),
                ),
                (
                    "completed_items",
                    models.PositiveIntegerField(
                        default=0, verbose_name="العناصر المكتملة"
                    ),
                ),
                (
                    "rejected_items",
                    models.PositiveIntegerField(
                        default=0, verbose_name="العناصر المرفوضة"
                    ),
                ),
                (
                    "pending_items",
                    models.PositiveIntegerField(
                        default=0, verbose_name="العناصر المعلقة"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ التقرير",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutting_reports",
                        to="inventory.warehouse",
                        verbose_name="المستودع",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير تقطيع",
                "verbose_name_plural": "تقارير التقطيع",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="CuttingOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("in_progress", "قيد التقطيع"),
                            ("completed", "مكتمل"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة التقطيع",
                    ),
                ),
                (
                    "cutter_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم القصاص"
                    ),
                ),
                (
                    "permit_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم الإذن"
                    ),
                ),
                (
                    "receiver_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم المستلم"
                    ),
                ),
                (
                    "cutting_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التقطيع"
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التسليم"
                    ),
                ),
                (
                    "bag_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم الشنطة"
                    ),
                ),
                (
                    "additional_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="كمية إضافية",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="سبب الرفض"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "cutting_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cutting.cuttingorder",
                        verbose_name="أمر التقطيع",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutting_items",
                        to="orders.orderitem",
                        verbose_name="عنصر الطلب",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="محدث بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر تقطيع",
                "verbose_name_plural": "عناصر التقطيع",
                "ordering": ["cutting_order", "order_item"],
                "indexes": [
                    models.Index(
                        fields=["cutting_order"], name="cutting_item_order_idx"
                    ),
                    models.Index(
                        fields=["order_item"], name="cutting_item_original_idx"
                    ),
                    models.Index(fields=["status"], name="cutting_item_status_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cuttingorder",
            index=models.Index(fields=["order"], name="cutting_order_idx"),
        ),
        migrations.AddIndex(
            model_name="cuttingorder",
            index=models.Index(fields=["warehouse"], name="cutting_warehouse_idx"),
        ),
        migrations.AddIndex(
            model_name="cuttingorder",
            index=models.Index(fields=["status"], name="cutting_status_idx"),
        ),
        migrations.AddIndex(
            model_name="cuttingorder",
            index=models.Index(fields=["created_at"], name="cutting_created_idx"),
        ),
    ]
