# Generated by Django 4.2.21 on 2025-08-28 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_product_currency"),
        ("cutting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuttingorderitem",
            name="inventory_deducted",
            field=models.BooleanField(default=False, verbose_name="تم خصم المخزون"),
        ),
        migrations.AddField(
            model_name="cuttingorderitem",
            name="inventory_deduction_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ خصم المخزون"
            ),
        ),
        migrations.AddField(
            model_name="cuttingorderitem",
            name="inventory_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cutting_items",
                to="inventory.stocktransaction",
                verbose_name="معاملة المخزون",
            ),
        ),
    ]
