# Generated by Django 4.2.21 on 2025-08-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0002_cuttingorderitem_inventory_deducted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuttingorderitem",
            name="bag_number",
        ),
    ]
