# Generated by Django 4.2.21 on 2025-08-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0003_remove_bag_number_from_cutting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuttingorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد الانتظار"),
                    ("in_progress", "قيد التقطيع"),
                    ("completed", "مكتمل"),
                    ("incomplete", "به نواقص"),
                    ("cancelled", "ملغي"),
                ],
                default="pending",
                max_length=20,
                verbose_name="حالة التقطيع",
            ),
        ),
    ]
