# Generated by Django 4.2.21 on 2025-08-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0004_alter_cuttingorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuttingorder",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="يُملأ في حالة رفض أمر التقطيع",
                verbose_name="سبب الرفض",
            ),
        ),
        migrations.AlterField(
            model_name="cuttingorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد الانتظار"),
                    ("in_progress", "قيد التقطيع"),
                    ("completed", "مكتمل"),
                    ("rejected", "مرفوض"),
                ],
                default="pending",
                max_length=20,
                verbose_name="حالة التقطيع",
            ),
        ),
    ]
