# Generated by Django 4.2.21 on 2025-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0005_cuttingorder_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuttingorderitem",
            name="bag_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم الشنطة"
            ),
        ),
        migrations.AddField(
            model_name="cuttingorderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاريخ الإنشاء"
            ),
        ),
        migrations.AddField(
            model_name="cuttingorderitem",
            name="fabric_received",
            field=models.BooleanField(default=False, verbose_name="تم استلام الأقمشة"),
        ),
    ]
