# Generated by Django 4.2.21 on 2025-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0006_add_fabric_received_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم القسم"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف القسم")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
                "ordering": ["name"],
            },
        ),
    ]
