# Generated by Django 5.2.6 on 2025-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0007_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuttingorderitem",
            name="backdate_reason",
            field=models.TextField(blank=True, verbose_name="سبب التسجيل بتاريخ سابق"),
        ),
        migrations.AddField(
            model_name="cuttingorderitem",
            name="exit_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الخروج"),
        ),
    ]
