# Generated by Django 5.2.6 on 2025-12-03 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0008_cuttingorderitem_backdate_reason_and_more"),
        (
            "inventory",
            "0015_product_product_code_idx_product_product_name_idx_and_more",
        ),
        ("orders", "0073_add_accessory_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cuttingorder",
            index=models.Index(
                fields=["status", "created_at"], name="cut_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuttingorder",
            index=models.Index(
                fields=["warehouse", "status"], name="cut_wareh_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuttingorder",
            index=models.Index(fields=["order", "status"], name="cut_order_status_idx"),
        ),
        migrations.AddIndex(
            model_name="cuttingorder",
            index=models.Index(
                fields=["assigned_to", "status"], name="cut_assign_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuttingorderitem",
            index=models.Index(
                fields=["cutting_order", "status"], name="cut_item_ord_sts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuttingorderitem",
            index=models.Index(
                fields=["status", "exit_date"], name="cut_item_sts_exit_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuttingorderitem",
            index=models.Index(
                fields=["inventory_deducted", "status"], name="cut_item_inv_sts_idx"
            ),
        ),
    ]
