# Generated by Django 6.0 on 2025-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0009_cuttingorder_cut_status_created_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingorderitem',
            name='bag_number',
            field=models.CharField(
                max_length=50,
                blank=True,
                verbose_name='رقم الشنطة',
                default=''
            ),
        ),
    ]
