# Generated by Django 6.0 on 2025-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0009_cuttingorder_cut_status_created_idx_and_more"),
    ]

    operations = [
        # bag_number already added in 0006_add_fabric_received_field
    ]
