# Generated by Django 6.0 on 2025-12-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0010_add_bag_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuttingorderitem",
            name="bag_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم الشنطة"
            ),
        ),
    ]
