# Generated by Django 6.0 on 2026-01-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0011_add_production_line_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuttingOrderFixLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإصلاح"
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[
                            ("auto_on_create", "تلقائي عند الإنشاء"),
                            ("auto_on_receive", "تلقائي عند الاستلام"),
                            ("manual", "يدوي"),
                        ],
                        default="auto_on_create",
                        max_length=20,
                        verbose_name="مصدر التشغيل",
                    ),
                ),
                (
                    "items_moved",
                    models.IntegerField(default=0, verbose_name="أصناف منقولة"),
                ),
                (
                    "service_items_deleted",
                    models.IntegerField(default=0, verbose_name="أصناف خدمية محذوفة"),
                ),
                (
                    "duplicates_deleted",
                    models.IntegerField(default=0, verbose_name="تكرارات محذوفة"),
                ),
                (
                    "new_orders_created",
                    models.IntegerField(default=0, verbose_name="أوامر جديدة منشأة"),
                ),
                (
                    "details",
                    models.JSONField(default=dict, verbose_name="تفاصيل العملية"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="نجاح")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "cutting_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fix_logs",
                        to="cutting.cuttingorder",
                        verbose_name="أمر التقطيع",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل إصلاح أمر تقطيع",
                "verbose_name_plural": "سجلات إصلاح أوامر التقطيع",
                "ordering": ["-timestamp"],
            },
        ),
    ]
