# Generated by Django 6.0 on 2026-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0012_cuttingorderfixlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuttingorder",
            name="needs_fix",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="يحتاج لإصلاح"
            ),
        ),
    ]
