# Generated by Django 6.0 on 2026-01-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0013_cuttingorder_needs_fix"),
        ("orders", "0087_remove_fabric_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuttingorderitem",
            name="external_fabric_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="اسم القماش الخارجي"
            ),
        ),
        migrations.AddField(
            model_name="cuttingorderitem",
            name="is_external",
            field=models.BooleanField(default=False, verbose_name="قماش خارجي"),
        ),
        migrations.AddField(
            model_name="cuttingorderitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="الكمية المطلوبة (يتم تعبئتها تلقائياً للأقمشة الخارجية)",
                max_digits=10,
                verbose_name="الكمية",
            ),
        ),
        migrations.AlterField(
            model_name="cuttingorderitem",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cutting_items",
                to="orders.orderitem",
                verbose_name="عنصر الطلب",
            ),
        ),
    ]
