# Generated by Django 6.0 on 2026-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0014_cuttingorderitem_external_fabric_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuttingorder",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="cuttingorder",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="cuttingorderitem",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="cuttingorderitem",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
    ]
