# Generated by Django 5.1.15 on 2026-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0017_cuttingorderfixlog_triggered_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuttingorderitem",
            name="additional_quantity",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=12, verbose_name="كمية إضافية"
            ),
        ),
        migrations.AlterField(
            model_name="cuttingorderitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="الكمية المطلوبة (يتم تعبئتها تلقائياً للأقمشة الخارجية)",
                max_digits=12,
                verbose_name="الكمية",
            ),
        ),
    ]
