# Generated by Django 5.1.15 on 2026-03-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0018_alter_cuttingorder_deleted_by_and_more"),
        ("cutting", "0018_standardize_decimal_precision"),
    ]

    operations = []
