# Generated by Django 4.2.21 on 2025-06-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_db_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ'),
        ),
        migrations.AddField(
            model_name='database',
            name='status',
            field=models.BooleanField(default=False, verbose_name='حالة الاتصال'),
        ),
    ]
