# Generated by Django 5.2.4 on 2025-07-09 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_db_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='معرف الجلسة')),
                ('filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('status', models.CharField(choices=[('starting', 'بدء العملية'), ('reading_file', 'قراءة الملف'), ('processing', 'معالجة البيانات'), ('restoring', 'استعادة البيانات'), ('completed', 'مكتملة'), ('failed', 'فشلت')], default='starting', max_length=20, verbose_name='الحالة')),
                ('total_items', models.IntegerField(default=0, verbose_name='إجمالي العناصر')),
                ('processed_items', models.IntegerField(default=0, verbose_name='العناصر المعالجة')),
                ('success_count', models.IntegerField(default=0, verbose_name='عدد النجاح')),
                ('error_count', models.IntegerField(default=0, verbose_name='عدد الأخطاء')),
                ('current_step', models.CharField(blank=True, max_length=255, verbose_name='الخطوة الحالية')),
                ('progress_percentage', models.FloatField(default=0.0, verbose_name='نسبة التقدم')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='بيانات النتيجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odoo_db_manager.database', verbose_name='قاعدة البيانات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقدم الاستعادة',
                'verbose_name_plural': 'تقدم الاستعادة',
                'ordering': ['-created_at'],
            },
        ),
    ]
