# Generated by Django 4.2.21 on 2025-08-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odoo_db_manager", "0002_add_comprehensive_sync_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Backup",
        ),
    ]
