# Generated by Django 6.0 on 2026-01-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odoo_db_manager", "0002_add_comprehensive_sync_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Backup",
        ),
    ]
