# Generated by Django 4.2.21 on 2025-07-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_db_manager', '0002_googledriveconfig_contracts_folder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlesheetmapping',
            name='auto_create_installations',
        ),
    ]
