# Generated by Django 4.2.21 on 2025-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_db_manager', '0004_backup_is_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='db_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL')], max_length=20, verbose_name='نوع قاعدة البيانات'),
        ),
    ]
