# Generated by Django 4.2.21 on 2025-05-27 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odoo_db_manager', '0005_remove_sqlite_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='إعدادات Google Drive', max_length=100, verbose_name='اسم الإعداد')),
                ('inspections_folder_id', models.CharField(blank=True, help_text='معرف المجلد في Google Drive لحفظ ملفات المعاينات', max_length=255, verbose_name='معرف مجلد المعاينات')),
                ('inspections_folder_name', models.CharField(blank=True, help_text='اسم المجلد في Google Drive', max_length=255, verbose_name='اسم مجلد المعاينات')),
                ('credentials_file', models.FileField(blank=True, help_text='ملف JSON من Google Cloud Console', null=True, upload_to='google_credentials/', verbose_name='ملف اعتماد Google')),
                ('filename_pattern', models.CharField(default='{customer}_{branch}_{date}_{order}', help_text='المتغيرات المتاحة: {customer}, {branch}, {date}, {order}', max_length=200, verbose_name='نمط تسمية الملفات')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('last_test', models.DateTimeField(blank=True, null=True, verbose_name='آخر اختبار')),
                ('test_status', models.CharField(blank=True, max_length=50, verbose_name='حالة الاختبار')),
                ('test_message', models.TextField(blank=True, verbose_name='رسالة الاختبار')),
                ('total_uploads', models.IntegerField(default=0, verbose_name='إجمالي الرفعات')),
                ('last_upload', models.DateTimeField(blank=True, null=True, verbose_name='آخر رفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات Google Drive',
                'verbose_name_plural': 'إعدادات Google Drive',
                'ordering': ['-created_at'],
            },
        ),
    ]
