# Generated by Django 4.2.21 on 2025-05-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("odoo_db_manager", "0006_add_google_drive_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSyncConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "spreadsheet_id",
                    models.CharField(max_length=255, verbose_name="معرف جدول البيانات"),
                ),
                (
                    "credentials_file",
                    models.FileField(
                        upload_to="google_credentials/",
                        verbose_name="ملف بيانات الاعتماد",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر مزامنة"
                    ),
                ),
                (
                    "sync_frequency",
                    models.IntegerField(
                        default=24, verbose_name="تكرار المزامنة (بالساعات)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "sync_databases",
                    models.BooleanField(
                        default=True, verbose_name="مزامنة قواعد البيانات"
                    ),
                ),
                (
                    "sync_users",
                    models.BooleanField(default=True, verbose_name="مزامنة المستخدمين"),
                ),
                (
                    "sync_customers",
                    models.BooleanField(default=True, verbose_name="مزامنة العملاء"),
                ),
                (
                    "sync_orders",
                    models.BooleanField(default=True, verbose_name="مزامنة الطلبات"),
                ),
                (
                    "sync_products",
                    models.BooleanField(default=True, verbose_name="مزامنة المنتجات"),
                ),
                (
                    "sync_settings",
                    models.BooleanField(default=True, verbose_name="مزامنة الإعدادات"),
                ),
            ],
            options={
                "verbose_name": "إعداد مزامنة غوغل",
                "verbose_name_plural": "إعدادات مزامنة غوغل",
            },
        ),
        migrations.CreateModel(
            name="GoogleSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "نجاح"),
                            ("error", "خطأ"),
                            ("warning", "تحذير"),
                        ],
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="التفاصيل"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="odoo_db_manager.googlesyncconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل مزامنة غوغل",
                "verbose_name_plural": "سجلات مزامنة غوغل",
                "ordering": ["-created_at"],
            },
        ),
    ]
