# Generated by Django 5.1.15 on 2026-03-12 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0023_alter_customer_phone_alter_customer_phone2"),
        ("inventory", "0039_add_original_warehouse_field"),
        ("orders", "0103_accessory_3_checkboxes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DecoratorEngineerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designer_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="يُولَّد تلقائياً عند الإنشاء",
                        max_length=20,
                        unique=True,
                        verbose_name="كود المهندس",
                    ),
                ),
                (
                    "company_office_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم المكتب / الشركة"
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="سنوات الخبرة"
                    ),
                ),
                (
                    "area_of_operation",
                    models.CharField(
                        blank=True,
                        help_text="المدن / المناطق التي يعمل فيها المهندس",
                        max_length=300,
                        verbose_name="منطقة العمل",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="المدينة",
                    ),
                ),
                (
                    "instagram_handle",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Instagram"
                    ),
                ),
                (
                    "portfolio_url",
                    models.URLField(blank=True, verbose_name="Portfolio URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "price_segment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "اقتصادي"),
                            ("medium", "متوسط"),
                            ("luxury", "فاخر"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="الشريحة السعرية",
                    ),
                ),
                (
                    "design_style",
                    models.CharField(
                        blank=True,
                        help_text="مثال: كلاسيك، مودرن، كونتمبوراري",
                        max_length=200,
                        verbose_name="أسلوب التصميم",
                    ),
                ),
                (
                    "preferred_colors",
                    models.TextField(blank=True, verbose_name="الألوان المفضلة"),
                ),
                (
                    "project_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="أنواع المشاريع التي يتخصص فيها المهندس",
                        verbose_name="أنواع المشاريع",
                    ),
                ),
                (
                    "interests_notes",
                    models.TextField(
                        blank=True,
                        help_text="أنواع الخامات والأقمشة المفضلة",
                        verbose_name="اهتمامات المهندس وتفضيلاته",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, verbose_name="ملاحظات داخلية (للقسم فقط)"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("vip", "VIP — أولوية قصوى"),
                            ("active", "نشط"),
                            ("regular", "عادي"),
                            ("cold", "فاتر — يحتاج إعادة تفعيل"),
                        ],
                        db_index=True,
                        default="regular",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "last_contact_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="آخر تواصل"
                    ),
                ),
                (
                    "last_order_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="آخر طلب"
                    ),
                ),
                (
                    "next_followup_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="موعد المتابعة القادمة",
                    ),
                ),
                (
                    "total_clients_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد العملاء"),
                ),
                (
                    "total_orders_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الطلبات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_decorator_engineers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="موظف المتابعة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decorator_profiles_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decorator_profile",
                        to="customers.customer",
                        verbose_name="العميل (المهندس)",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decorator_profiles_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف مهندس ديكور",
                "verbose_name_plural": "ملفات مهندسي الديكور",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_decorator_profiles", "Can view decorator engineer profiles"),
                    (
                        "manage_decorator_profiles",
                        "Can manage decorator engineer profiles",
                    ),
                    ("view_decorator_commissions", "Can view commission data"),
                    ("manage_decorator_commissions", "Can manage commissions"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EngineerContactLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("call", "مكالمة هاتفية"),
                            ("whatsapp", "رسالة واتساب"),
                            ("meeting", "اجتماع"),
                            ("appointment", "حجز موعد زيارة"),
                            ("email", "بريد إلكتروني"),
                            ("visit", "زيارة ميدانية"),
                            ("other", "أخرى"),
                        ],
                        db_index=True,
                        max_length=15,
                        verbose_name="نوع التواصل",
                    ),
                ),
                (
                    "contact_date",
                    models.DateTimeField(
                        db_index=True, verbose_name="تاريخ ووقت التواصل"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("answered", "رد على المكالمة"),
                            ("no_answer", "لم يرد"),
                            ("busy", "مشغول"),
                            ("appointment_booked", "تم حجز موعد"),
                            ("interested", "مهتم"),
                            ("not_interested", "غير مهتم"),
                            ("callback_requested", "طلب معاودة الاتصال"),
                            ("completed", "اكتملت المتابعة"),
                        ],
                        max_length=25,
                        verbose_name="نتيجة التواصل",
                    ),
                ),
                ("notes", models.TextField(verbose_name="تفاصيل / ملاحظات")),
                (
                    "next_followup_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="موعد المتابعة القادمة",
                    ),
                ),
                (
                    "next_followup_notes",
                    models.TextField(
                        blank=True, verbose_name="تفاصيل المتابعة القادمة"
                    ),
                ),
                (
                    "appointment_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ ووقت الموعد"
                    ),
                ),
                (
                    "appointment_location",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="مكان الموعد"
                    ),
                ),
                (
                    "appointment_confirmed",
                    models.BooleanField(default=False, verbose_name="تأكيد الموعد"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_logs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سُجِّل بواسطة",
                    ),
                ),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_logs",
                        to="external_sales.decoratorengineerprofile",
                        verbose_name="المهندس",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تواصل",
                "verbose_name_plural": "سجلات التواصل",
                "ordering": ["-contact_date"],
            },
        ),
        migrations.CreateModel(
            name="EngineerLinkedCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("referred_client", "عميل أحاله المهندس"),
                            ("designer_project", "مشروع المهندس نفسه"),
                        ],
                        default="referred_client",
                        max_length=20,
                        verbose_name="نوع العلاقة",
                    ),
                ),
                (
                    "default_commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="تُطبق تلقائياً على الطلبات الجديدة إذا لم تُحدَّد قيمة خاصة",
                        max_digits=5,
                        verbose_name="نسبة العمولة الافتراضية %",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineer_links",
                        to="customers.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_customers",
                        to="external_sales.decoratorengineerprofile",
                        verbose_name="المهندس",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_links_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ربط بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "عميل مرتبط بمهندس",
                "verbose_name_plural": "العملاء المرتبطون بمهندسين",
            },
        ),
        migrations.CreateModel(
            name="EngineerLinkedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("manual", "يدوي"),
                            ("auto", "تلقائي عبر العميل المرتبط"),
                        ],
                        default="manual",
                        max_length=10,
                        verbose_name="نوع الربط",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("percentage", "نسبة مئوية من قيمة الطلب"),
                            ("fixed_amount", "مبلغ ثابت"),
                        ],
                        default="percentage",
                        max_length=15,
                        verbose_name="نوع العمولة",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="نسبة العمولة %",
                    ),
                ),
                (
                    "commission_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="يُحسب تلقائياً أو يُدخل يدوياً",
                        max_digits=12,
                        verbose_name="قيمة العمولة",
                    ),
                ),
                (
                    "commission_status",
                    models.CharField(
                        choices=[
                            ("pending", "معلقة"),
                            ("approved", "معتمدة"),
                            ("paid", "مدفوعة"),
                            ("cancelled", "ملغاة"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="حالة العمولة",
                    ),
                ),
                (
                    "commission_paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ دفع العمولة"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات العمولة")),
                (
                    "commission_paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions_paid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_orders",
                        to="external_sales.decoratorengineerprofile",
                        verbose_name="المهندس",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_links_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ربط بواسطة",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineer_link",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب مرتبط بمهندس",
                "verbose_name_plural": "الطلبات المرتبطة بمهندسين",
            },
        ),
        migrations.CreateModel(
            name="EngineerMaterialInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        max_length=200, verbose_name="اسم الخامة / القماش"
                    ),
                ),
                (
                    "interest_level",
                    models.CharField(
                        choices=[
                            ("high", "مرتفع"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="درجة الاهتمام",
                    ),
                ),
                (
                    "request_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="كم مرة طلب المهندس هذه الخامة",
                        verbose_name="عدد مرات الطلب",
                    ),
                ),
                (
                    "last_requested_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="آخر مرة طُلبت",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_interests",
                        to="external_sales.decoratorengineerprofile",
                        verbose_name="المهندس",
                    ),
                ),
                (
                    "inventory_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engineer_interests",
                        to="inventory.category",
                        verbose_name="تصنيف المخزون",
                    ),
                ),
            ],
            options={
                "verbose_name": "اهتمام بخامة",
                "verbose_name_plural": "اهتمامات الخامات",
                "ordering": ["-request_count"],
            },
        ),
        migrations.AddIndex(
            model_name="decoratorengineerprofile",
            index=models.Index(
                fields=["priority", "-created_at"],
                name="external_sa_priorit_359f17_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decoratorengineerprofile",
            index=models.Index(
                fields=["assigned_staff"], name="external_sa_assigne_43a5a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decoratorengineerprofile",
            index=models.Index(fields=["city"], name="external_sa_city_024c83_idx"),
        ),
        migrations.AddIndex(
            model_name="engineercontactlog",
            index=models.Index(
                fields=["engineer", "-contact_date"],
                name="external_sa_enginee_05d102_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="engineercontactlog",
            index=models.Index(
                fields=["next_followup_date"], name="external_sa_next_fo_db13c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engineercontactlog",
            index=models.Index(
                fields=["outcome"], name="external_sa_outcome_95bcab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engineerlinkedcustomer",
            index=models.Index(
                fields=["engineer", "is_active"], name="external_sa_enginee_abba23_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="engineerlinkedcustomer",
            unique_together={("engineer", "customer")},
        ),
        migrations.AddIndex(
            model_name="engineerlinkedorder",
            index=models.Index(
                fields=["engineer", "commission_status"],
                name="external_sa_enginee_43d979_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="engineerlinkedorder",
            index=models.Index(
                fields=["engineer", "-linked_at"], name="external_sa_enginee_2dc69a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="engineermaterialinterest",
            unique_together={("engineer", "material_name")},
        ),
    ]
