# Generated by Django 4.2.21 on 2025-07-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupschedule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
    ]
