# Generated by Django 5.2.4 on 2025-07-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedSystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Elkhawaga', max_length=200, verbose_name='اسم الشركة')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='شعار الشركة')),
                ('company_address', models.TextField(blank=True, null=True, verbose_name='عنوان الشركة')),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف الشركة')),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد الشركة')),
                ('company_website', models.URLField(blank=True, null=True, verbose_name='موقع الشركة')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=50, null=True, verbose_name='السجل التجاري')),
                ('currency', models.CharField(choices=[('SAR', 'ريال سعودي'), ('EGP', 'جنيه مصري'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو'), ('AED', 'درهم إماراتي'), ('KWD', 'دينار كويتي'), ('QAR', 'ريال قطري'), ('BHD', 'دينار بحريني'), ('OMR', 'ريال عماني')], default='SAR', max_length=3, verbose_name='العملة')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات')),
                ('enable_email_notifications', models.BooleanField(default=False, verbose_name='تفعيل إشعارات البريد الإلكتروني')),
                ('items_per_page', models.PositiveIntegerField(default=20, verbose_name='عدد العناصر في الصفحة')),
                ('low_stock_threshold', models.PositiveIntegerField(default=20, verbose_name='حد المخزون المنخفض (%)')),
                ('enable_analytics', models.BooleanField(default=True, verbose_name='تفعيل التحليلات')),
                ('primary_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='اللون الثانوي')),
                ('accent_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='لون التمييز')),
                ('default_theme', models.CharField(default='default', max_length=50, verbose_name='الثيم الافتراضي')),
                ('working_hours', models.CharField(blank=True, default='', max_length=100, verbose_name='ساعات العمل')),
                ('about_text', models.TextField(blank=True, null=True, verbose_name='نص عن الشركة')),
                ('vision_text', models.TextField(blank=True, null=True, verbose_name='رؤية الشركة')),
                ('mission_text', models.TextField(blank=True, null=True, verbose_name='رسالة الشركة')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='رابط تويتر')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='رابط انستغرام')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='رابط لينكد إن')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='رسالة الصيانة')),
                ('system_version', models.CharField(default='1.0.0', editable=False, max_length=50, verbose_name='إصدار النظام')),
                ('system_release_date', models.CharField(default='2025-04-30', editable=False, max_length=50, verbose_name='تاريخ الإطلاق')),
                ('system_developer', models.CharField(default='zakee tahawi', editable=False, max_length=100, verbose_name='المطور')),
                ('copyright_text', models.CharField(blank=True, default='جميع الحقوق محفوظة لشركة الخواجة للستائر والمفروشات تطوير zakee tahawi', max_length=255, verbose_name='نص حقوق النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات النظام الموحدة',
                'verbose_name_plural': 'إعدادات النظام الموحدة',
            },
        ),
    ]
