# Generated by Django 5.2.4 on 2025-07-12 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_unifiedsystemsettings'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender_department',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_branch',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_department',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_users',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, verbose_name='رابط الإجراء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='auto_delete_after_days',
            field=models.PositiveIntegerField(default=30, verbose_name='حذف تلقائي بعد (أيام)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='مؤرشف'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='تم الإرسال'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تحذير'), ('error', 'خطأ'), ('order', 'طلب'), ('inspection', 'معاينة'), ('manufacturing', 'تصنيع'), ('inventory', 'مخزون'), ('system', 'نظام')], default='info', max_length=20, verbose_name='نوع الإشعار'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلمون'),
        ),
        migrations.AddField(
            model_name='notification',
            name='requires_action',
            field=models.BooleanField(default=False, verbose_name='يتطلب إجراء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_branches',
            field=models.ManyToManyField(blank=True, to='accounts.branch', verbose_name='الفروع المستهدفة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_departments',
            field=models.ManyToManyField(blank=True, to='accounts.department', verbose_name='الأقسام المستهدفة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المحتوى'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='مقروء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=10, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'priority'], name='accounts_no_notific_49417d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', 'created_at'], name='accounts_no_is_read_e9d68f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='accounts_no_content_9af20f_idx'),
        ),
    ]
