# Generated by Django 5.2.4 on 2025-07-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_notification_read_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedsystemsettings',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الشركة'),
        ),
        migrations.AddField(
            model_name='unifiedsystemsettings',
            name='social_links',
            field=models.JSONField(blank=True, null=True, verbose_name='روابط التواصل الاجتماعي الإضافية'),
        ),
    ]
