# Generated by Django 4.2.21 on 2025-07-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_companyinfo_header_logo_alter_companyinfo_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_salesperson",
            field=models.BooleanField(default=False, verbose_name="بائع"),
        ),
    ]
