# Generated by Django 4.2.21 on 2025-07-12 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_unifiedsystemsettings_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='تفعيل المصادقة الثنائية')),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, verbose_name='مفتاح المصادقة الثنائية')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='رموز النسخ الاحتياطي')),
                ('password_changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ تغيير كلمة المرور')),
                ('password_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء كلمة المرور')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='محاولات تسجيل الدخول الفاشلة')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='مقفل حتى')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر IP لتسجيل الدخول')),
                ('last_login_user_agent', models.TextField(blank=True, verbose_name='آخر User Agent')),
                ('session_timeout', models.PositiveIntegerField(default=30, verbose_name='مهلة الجلسة (دقائق)')),
                ('login_history', models.JSONField(blank=True, default=list, verbose_name='سجل تسجيل الدخول')),
                ('security_events', models.JSONField(blank=True, default=list, verbose_name='الأحداث الأمنية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف الأمان',
                'verbose_name_plural': 'ملفات الأمان',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('password_change', 'تغيير كلمة المرور'), ('permission_change', 'تغيير الصلاحيات'), ('data_access', 'الوصول للبيانات'), ('data_modification', 'تعديل البيانات'), ('security_violation', 'انتهاك أمني'), ('system_event', 'حدث نظام')], max_length=20, verbose_name='نوع الحدث')),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=10, verbose_name='مستوى الخطورة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='نوع الكائن المرتبط')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن المرتبط')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='accounts_au_user_id_d6bb38_idx'), models.Index(fields=['timestamp'], name='accounts_au_timesta_276167_idx'), models.Index(fields=['severity'], name='accounts_au_severit_5f2320_idx')],
            },
        ),
    ]
