# Generated by Django 4.2.21 on 2025-08-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20250729_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_factory_manager',
            field=models.BooleanField(default=False, verbose_name='مسؤول مصنع'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_inspection_manager',
            field=models.BooleanField(default=False, verbose_name='مسؤول معاينات'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_installation_manager',
            field=models.BooleanField(default=False, verbose_name='مسؤول تركيبات'),
        ),
    ]
