# Generated by Django 4.2.21 on 2025-08-04 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_user_is_factory_manager_user_is_inspection_manager_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="branchmessage",
            name="is_for_all_branches",
            field=models.BooleanField(default=False, verbose_name="لجميع الفروع"),
        ),
        migrations.AlterField(
            model_name="branchmessage",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="accounts.branch",
                verbose_name="الفرع",
            ),
        ),
    ]
