# Generated by Django 4.2.21 on 2025-06-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_branchmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_theme',
            field=models.CharField(default='default', max_length=50, verbose_name='الثيم الافتراضي'),
        ),
    ]
