# Generated by Django 4.2.21 on 2025-08-14 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_initial_fixed"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="مفتاح الجلسة"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="معلومات المتصفح"),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الدخول"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="آخر نشاط"),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الخروج"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "سطح المكتب"),
                            ("mobile", "هاتف محمول"),
                            ("tablet", "جهاز لوحي"),
                            ("unknown", "غير معروف"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="نوع الجهاز",
                    ),
                ),
                (
                    "browser",
                    models.CharField(blank=True, max_length=50, verbose_name="المتصفح"),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نظام التشغيل"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة مستخدم",
                "verbose_name_plural": "جلسات المستخدمين",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="UserLoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الدخول"),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الخروج"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="معلومات المتصفح"),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="مفتاح الجلسة"),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المتصفح"
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نظام التشغيل"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "سطح المكتب"),
                            ("mobile", "هاتف محمول"),
                            ("tablet", "جهاز لوحي"),
                            ("unknown", "غير معروف"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="نوع الجهاز",
                    ),
                ),
                (
                    "pages_visited",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد الصفحات المزارة"
                    ),
                ),
                (
                    "actions_performed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد العمليات المنجزة"
                    ),
                ),
                (
                    "is_successful_login",
                    models.BooleanField(default=True, verbose_name="تسجيل دخول ناجح"),
                ),
                (
                    "logout_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "خروج يدوي"),
                            ("timeout", "انتهاء المهلة"),
                            ("forced", "خروج قسري"),
                            ("system", "خروج النظام"),
                            ("unknown", "غير معروف"),
                        ],
                        default="unknown",
                        max_length=50,
                        verbose_name="سبب الخروج",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تسجيل الدخول",
                "verbose_name_plural": "سجلات تسجيل الدخول",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "🔐 تسجيل دخول"),
                            ("logout", "🚪 تسجيل خروج"),
                            ("login_failed", "❌ فشل تسجيل دخول"),
                            ("page_view", "👁️ عرض صفحة"),
                            ("dashboard_view", "📊 عرض لوحة التحكم"),
                            ("create", "➕ إنشاء"),
                            ("read", "👁️ قراءة"),
                            ("update", "✏️ تحديث"),
                            ("delete", "🗑️ حذف"),
                            ("search", "🔍 بحث"),
                            ("export", "📤 تصدير"),
                            ("import", "📥 استيراد"),
                            ("print", "🖨️ طباعة"),
                            ("download", "⬇️ تحميل"),
                            ("upload", "⬆️ رفع"),
                            ("backup", "💾 نسخ احتياطي"),
                            ("restore", "🔄 استعادة"),
                            ("sync", "🔄 مزامنة"),
                            ("other", "📝 أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("customer", "عميل"),
                            ("order", "طلب"),
                            ("product", "منتج"),
                            ("inspection", "معاينة"),
                            ("manufacturing", "تصنيع"),
                            ("installation", "تركيب"),
                            ("inventory", "مخزون"),
                            ("report", "تقرير"),
                            ("user", "مستخدم"),
                            ("system", "نظام"),
                            ("page", "صفحة"),
                            ("other", "أخرى"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="نوع الكائن",
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="معرف الكائن"
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الكائن"
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف العملية")),
                (
                    "url_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسار الصفحة"
                    ),
                ),
                (
                    "http_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="طريقة HTTP"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="معلومات المتصفح"),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت العملية"),
                ),
                (
                    "success",
                    models.BooleanField(default=True, verbose_name="نجحت العملية"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="accounts.usersession",
                        verbose_name="الجلسة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل نشاط المستخدم",
                "verbose_name_plural": "سجلات أنشطة المستخدمين",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="OnlineUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="آخر ظهور"),
                ),
                (
                    "current_page",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="الصفحة الحالية"
                    ),
                ),
                (
                    "current_page_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان الصفحة الحالية"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="مفتاح الجلسة"),
                ),
                (
                    "device_info",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="معلومات الجهاز"
                    ),
                ),
                (
                    "pages_visited",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد الصفحات المزارة"
                    ),
                ),
                (
                    "actions_performed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد العمليات المنجزة"
                    ),
                ),
                ("login_time", models.DateTimeField(verbose_name="وقت الدخول")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_status",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم متصل",
                "verbose_name_plural": "المستخدمون المتصلون",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "-last_activity"], name="accounts_us_user_id_018f2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["is_active"], name="accounts_us_is_acti_58b48a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_key"], name="accounts_us_session_511f42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["login_time"], name="accounts_us_login_t_af2958_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginhistory",
            index=models.Index(
                fields=["user", "-login_time"], name="accounts_us_user_id_98058e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginhistory",
            index=models.Index(
                fields=["login_time"], name="accounts_us_login_t_4cf3f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginhistory",
            index=models.Index(
                fields=["ip_address"], name="accounts_us_ip_addr_9b8fd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginhistory",
            index=models.Index(
                fields=["is_successful_login"], name="accounts_us_is_succ_37f1fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["user", "-timestamp"], name="accounts_us_user_id_39428d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["action_type"], name="accounts_us_action__52beb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["entity_type"], name="accounts_us_entity__2e5627_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["timestamp"], name="accounts_us_timesta_d708d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["success"], name="accounts_us_success_dfcf7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["ip_address"], name="accounts_us_ip_addr_8ca938_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlineuser",
            index=models.Index(
                fields=["-last_seen"], name="accounts_on_last_se_46eb81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlineuser",
            index=models.Index(
                fields=["session_key"], name="accounts_on_session_5a9b20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlineuser",
            index=models.Index(fields=["user"], name="accounts_on_user_id_0310ce_idx"),
        ),
    ]
