# Generated by Django 4.2.21 on 2025-08-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_onlineuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userloginhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='OnlineUser',
        ),
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
        migrations.DeleteModel(
            name='UserLoginHistory',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
