# Generated by Django 4.2.21 on 2025-08-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_add_user_to_salesperson"),
    ]

    operations = []
