# Generated by Django 4.2.21 on 2025-08-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_auto_20250821_1309"),
    ]

    operations = [
        # Use raw SQL to drop the Notification table and its m2m table if they exist.
        # This is safer in environments where the m2m through table might have been
        # removed or never created (pre-existing inconsistencies).
        migrations.RunSQL(
            sql=(
                "DROP TABLE IF EXISTS accounts_notification_target_users CASCADE;"
                "DROP TABLE IF EXISTS accounts_notification CASCADE;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
