# Generated by Django 4.2.21 on 2025-08-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_delete_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_notifications',
            field=models.BooleanField(default=True, verbose_name='تفعيل الإشعارات'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_email_notifications',
            field=models.BooleanField(default=False, verbose_name='تفعيل إشعارات البريد الإلكتروني'),
        ),
    ]