# Generated by Django 4.2.21 on 2025-08-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_auto_20250821_1309"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
