# Generated by Django 4.2.21 on 2025-08-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_delete_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
