# Generated by Django 4.2.21 on 2025-08-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_delete_notification"),
    ]

    operations = [
        # Idempotent removal: drop the Notification table and its m2m through table if they exist.
        migrations.RunSQL(
            sql=(
                "DROP TABLE IF EXISTS accounts_notification_target_users CASCADE;"
                "DROP TABLE IF EXISTS accounts_notification CASCADE;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
