# Generated by Django 4.2.21 on 2025-09-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_delete_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearFilterExemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("customers", "العملاء"),
                            ("inspections", "المعاينات"),
                            ("inventory", "المخزون"),
                            ("reports", "التقارير"),
                            ("orders", "الطلبات"),
                            ("installations", "التركيبات"),
                            ("manufacturing", "التصنيع"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="القسم",
                    ),
                ),
                (
                    "is_exempt",
                    models.BooleanField(
                        default=False, verbose_name="معفى من فلتر السنة"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="الوصف"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إعفاء قسم من فلتر السنة",
                "verbose_name_plural": "إعفاءات الأقسام من فلتر السنة",
                "ordering": ["section"],
            },
        ),
    ]
