# Generated by Django 4.2.21 on 2025-09-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_delete_notification"),
    ]

    operations = [
        # استخدام RunSQL لحذف النموذج بطريقة آمنة
        migrations.RunSQL(
            sql=(
                # حذف الجدول الرئيسي إذا كان موجوداً
                "DROP TABLE IF EXISTS accounts_notification CASCADE;",
                # حذف جدول العلاقة ManyToMany إذا كان موجوداً
                "DROP TABLE IF EXISTS accounts_notification_target_users CASCADE;",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
