# Generated by Django 4.2.21 on 2025-09-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_delete_notification"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- حذف جميع الجداول المتعلقة بنموذج Notification بأمان
            DROP TABLE IF EXISTS accounts_notification_target_users;
            DROP TABLE IF EXISTS accounts_notification;
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.DeleteModel(
                    name="Notification",
                ),
            ],
        ),
    ]
