# Generated by Django 5.2.6 on 2025-09-30 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_delete_notification_final"),
        ("inventory", "0007_alter_product_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="المستودع المخصص لموظف المستودع",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_staff",
                to="inventory.warehouse",
                verbose_name="المستودع المخصص",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_warehouse_staff",
            field=models.BooleanField(default=False, verbose_name="موظف مستودع"),
        ),
    ]
