# Generated by Django 5.2.6 on 2025-10-06 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_user_assigned_warehouse_user_is_warehouse_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="الموضوع")),
                ("body", models.TextField(verbose_name="المحتوى")),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروءة")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القراءة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="مهم"),
                ),
                (
                    "is_deleted_by_sender",
                    models.BooleanField(default=False, verbose_name="محذوفة من المرسل"),
                ),
                (
                    "is_deleted_by_recipient",
                    models.BooleanField(
                        default=False, verbose_name="محذوفة من المستلم"
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="accounts.internalmessage",
                        verbose_name="الرسالة الأصلية",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستلم",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المرسل",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة داخلية",
                "verbose_name_plural": "الرسائل الداخلية",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="accounts_in_recipie_982729_idx",
                    ),
                    models.Index(
                        fields=["sender", "-created_at"],
                        name="accounts_in_sender__d418cf_idx",
                    ),
                    models.Index(
                        fields=["is_read", "recipient"],
                        name="accounts_in_is_read_147c10_idx",
                    ),
                ],
            },
        ),
    ]
