# Generated by Django 5.2.6 on 2025-10-07 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_internalmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeCustomization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_theme",
                    models.CharField(
                        default="default", max_length=50, verbose_name="الثيم الأساسي"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="لون الخلفية الرئيسية",
                    ),
                ),
                (
                    "surface_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="لون السطح"
                    ),
                ),
                (
                    "card_bg_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="خلفية البطاقات",
                    ),
                ),
                (
                    "elevated_bg_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="خلفية مرتفعة"
                    ),
                ),
                (
                    "table_bg_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="خلفية الجداول",
                    ),
                ),
                (
                    "filter_bg_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="خلفية الفلاتر",
                    ),
                ),
                (
                    "input_bg_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="خلفية الحقول"
                    ),
                ),
                (
                    "navbar_bg_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="خلفية Navbar"
                    ),
                ),
                (
                    "navbar_text_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="نص Navbar"
                    ),
                ),
                (
                    "footer_bg_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="خلفية Footer"
                    ),
                ),
                (
                    "footer_text_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="نص Footer"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="اللون الأساسي",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="اللون الثانوي",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="لون الإبراز"
                    ),
                ),
                (
                    "text_primary_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="النص الأساسي"
                    ),
                ),
                (
                    "text_secondary_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="النص الثانوي"
                    ),
                ),
                (
                    "text_tertiary_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="النص الثالثي"
                    ),
                ),
                (
                    "success_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="لون النجاح"
                    ),
                ),
                (
                    "warning_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="لون التحذير"
                    ),
                ),
                (
                    "error_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="لون الخطأ"
                    ),
                ),
                (
                    "info_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="لون المعلومات",
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="لون الحدود"
                    ),
                ),
                (
                    "separator_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="لون الفواصل"
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="لون الأيقونات",
                    ),
                ),
                (
                    "icon_hover_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="لون الأيقونات عند التمرير",
                    ),
                ),
                (
                    "link_color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="لون الروابط"
                    ),
                ),
                (
                    "link_hover_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="لون الروابط عند التمرير",
                    ),
                ),
                (
                    "advanced_customization",
                    models.TextField(
                        blank=True,
                        help_text="تخصيصات إضافية بصيغة JSON",
                        null=True,
                        verbose_name="تخصيصات متقدمة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_customization",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصيص الثيم",
                "verbose_name_plural": "تخصيصات الثيمات",
                "ordering": ["-updated_at"],
            },
        ),
    ]
