# Generated by Django 5.2.6 on 2025-11-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_internalmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="max_draft_orders_per_user",
            field=models.PositiveIntegerField(
                default=5,
                help_text="العدد الأقصى للمسودات (الدرافتات) المسموح بها لكل مستخدم",
                verbose_name="الحد الأقصى للمسودات لكل مستخدم",
            ),
        ),
    ]
