# Generated by Django 5.2.6 on 2025-12-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_add_max_draft_orders_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="currency",
            field=models.CharField(
                choices=[
                    ("SAR", "ريال سعودي"),
                    ("EGP", "جنيه مصري"),
                    ("USD", "دولار أمريكي"),
                    ("EUR", "يورو"),
                    ("AED", "درهم إماراتي"),
                    ("KWD", "دينار كويتي"),
                    ("QAR", "ريال قطري"),
                    ("BHD", "دينار بحريني"),
                    ("OMR", "ريال عماني"),
                ],
                default="EGP",
                max_length=3,
                verbose_name="العملة",
            ),
        ),
    ]
