# Generated by Django 6.0 on 2025-12-07 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_alter_systemsettings_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        help_text="اسم تعريفي للجهاز (مثل: كمبيوتر الاستقبال 1)",
                        max_length=200,
                        verbose_name="اسم الجهاز",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="معرف فريد للجهاز يتم توليده تلقائياً",
                        max_length=64,
                        unique=True,
                        verbose_name="بصمة الجهاز",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="آخر عنوان IP مستخدم",
                        null=True,
                        verbose_name="عنوان IP",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="معلومات المتصفح والنظام",
                        verbose_name="معلومات المتصفح",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل هذا الجهاز مفعل للاستخدام؟",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "first_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="أول استخدام"
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر استخدام"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="ملاحظات إضافية عن الجهاز",
                        verbose_name="ملاحظات",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="accounts.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "last_used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_used_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آخر مستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "جهاز الفرع",
                "verbose_name_plural": "أجهزة الفروع",
                "ordering": ["branch", "device_name"],
                "indexes": [
                    models.Index(
                        fields=["device_fingerprint"],
                        name="accounts_br_device__3fe610_idx",
                    ),
                    models.Index(
                        fields=["branch", "is_active"],
                        name="accounts_br_branch__cdb7c4_idx",
                    ),
                ],
            },
        ),
    ]
