# Generated by Django 6.0 on 2025-12-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_branchdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchdevice",
            name="hardware_serial",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="الرقم التسلسلي للجهاز (Hardware UUID/Serial)",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="الرقم التسلسلي للجهاز",
            ),
        ),
        migrations.AlterField(
            model_name="branchdevice",
            name="device_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="معرف فريد للجهاز يتم توليده تلقائياً (اختياري)",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="بصمة الجهاز",
            ),
        ),
    ]
