# Generated by Django 6.0 on 2025-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_branchdevice_hardware_serial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="enable_device_restriction",
            field=models.BooleanField(
                default=False,
                help_text="عند التفعيل، لن يتمكن الموظفون من تسجيل الدخول إلا من الأجهزة المسجلة لفرعهم. السوبر يوزر والمدير العام معفيين.",
                verbose_name="تفعيل قفل الأجهزة",
            ),
        ),
    ]
