# Generated by Django 6.0 on 2025-12-07 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_systemsettings_enable_device_restriction"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnauthorizedDeviceAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="وقت المحاولة"
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="بصمة الجهاز"
                    ),
                ),
                (
                    "hardware_serial",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="الرقم التسلسلي للجهاز",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="معلومات المتصفح"),
                ),
                (
                    "denial_reason",
                    models.CharField(
                        choices=[
                            ("device_not_registered", "جهاز غير مسجل"),
                            ("wrong_branch", "جهاز مسجل لفرع آخر"),
                            ("device_inactive", "جهاز معطل"),
                        ],
                        default="device_not_registered",
                        max_length=50,
                        verbose_name="سبب الرفض",
                    ),
                ),
                (
                    "is_notified",
                    models.BooleanField(
                        default=False,
                        help_text="هل تم إرسال إشعار لمدير النظام؟",
                        verbose_name="تم الإشعار",
                    ),
                ),
                (
                    "device_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_unauthorized_attempts",
                        to="accounts.branch",
                        verbose_name="فرع الجهاز",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unauthorized_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "user_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unauthorized_login_attempts",
                        to="accounts.branch",
                        verbose_name="فرع المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "محاولة دخول غير مصرح بها",
                "verbose_name_plural": "محاولات الدخول غير المصرح بها",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["-attempted_at"], name="accounts_un_attempt_4ddfbe_idx"
                    ),
                    models.Index(
                        fields=["user", "-attempted_at"],
                        name="accounts_un_user_id_b59da8_idx",
                    ),
                    models.Index(
                        fields=["is_notified"], name="accounts_un_is_noti_02f717_idx"
                    ),
                ],
            },
        ),
    ]
