# Generated by Django 6.0 on 2025-12-08 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_unauthorizeddeviceattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchdevice",
            name="users_logged",
            field=models.ManyToManyField(
                blank=True,
                help_text="قائمة المستخدمين الذين استخدموا هذا الجهاز (بدون تكرار)",
                related_name="devices_used",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدمون الذين سجلوا الدخول",
            ),
        ),
    ]
