# Generated by Django 6.0 on 2025-12-08 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_branchdevice_users_logged"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchdevice",
            name="blocked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحظر"
            ),
        ),
        migrations.AddField(
            model_name="branchdevice",
            name="blocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocked_devices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الحظر بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="branchdevice",
            name="blocked_reason",
            field=models.TextField(
                blank=True, help_text="سبب حظر هذا الجهاز", verbose_name="سبب الحظر"
            ),
        ),
        migrations.AddField(
            model_name="branchdevice",
            name="is_blocked",
            field=models.BooleanField(
                default=False,
                help_text="هل هذا الجهاز محظور من الاستخدام؟ (الحظر أقوى من التعطيل)",
                verbose_name="محظور",
            ),
        ),
        migrations.AddField(
            model_name="unauthorizeddeviceattempt",
            name="username_attempted",
            field=models.CharField(
                default="",
                help_text="اسم المستخدم الذي تم محاولة الدخول به",
                max_length=150,
                verbose_name="اسم المستخدم المحاول",
            ),
        ),
        migrations.AlterField(
            model_name="unauthorizeddeviceattempt",
            name="denial_reason",
            field=models.CharField(
                choices=[
                    ("invalid_username", "اسم مستخدم خاطئ"),
                    ("invalid_password", "كلمة مرور خاطئة"),
                    ("device_not_registered", "جهاز غير مسجل"),
                    ("wrong_branch", "جهاز مسجل لفرع آخر"),
                    ("device_inactive", "جهاز معطل"),
                    ("device_blocked", "جهاز محظور"),
                ],
                default="device_not_registered",
                max_length=50,
                verbose_name="سبب الرفض",
            ),
        ),
        migrations.AlterField(
            model_name="unauthorizeddeviceattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="المستخدم الذي حاول الدخول (null إذا كان اسم المستخدم خاطئ)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unauthorized_attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
    ]
