# Generated by Django 6.0 on 2025-12-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_branchdevice_blocked_at_branchdevice_blocked_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unauthorizeddeviceattempt",
            name="device",
            field=models.ForeignKey(
                blank=True,
                help_text="الجهاز الذي تمت المحاولة منه (إذا كان مسجلاً)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unauthorized_attempts",
                to="accounts.branchdevice",
                verbose_name="الجهاز",
            ),
        ),
    ]
