# Generated by Django 6.0 on 2025-12-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_unauthorizeddeviceattempt_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_factory_receiver",
            field=models.BooleanField(default=False, verbose_name="مسؤول استلام مصنع"),
        ),
    ]
