# Generated by Django 6.0 on 2025-12-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_create_system_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="show_accounting",
            field=models.BooleanField(default=False, verbose_name="عرض المحاسبة"),
        ),
        migrations.AddField(
            model_name="department",
            name="show_complaints",
            field=models.BooleanField(default=False, verbose_name="عرض الشكاوى"),
        ),
        migrations.AddField(
            model_name="department",
            name="show_customers",
            field=models.BooleanField(default=False, verbose_name="عرض العملاء"),
        ),
        migrations.AddField(
            model_name="department",
            name="show_database",
            field=models.BooleanField(default=False, verbose_name="عرض إدارة البيانات"),
        ),
        migrations.AddField(
            model_name="department",
            name="show_inspections",
            field=models.BooleanField(default=False, verbose_name="عرض المعاينات"),
        ),
        migrations.AddField(
            model_name="department",
            name="show_installations",
            field=models.BooleanField(default=False, verbose_name="عرض التركيبات"),
        ),
        migrations.AddField(
            model_name="department",
            name="show_inventory",
            field=models.BooleanField(default=False, verbose_name="عرض المخزون"),
        ),
        migrations.AddField(
            model_name="department",
            name="show_manufacturing",
            field=models.BooleanField(default=False, verbose_name="عرض المصنع"),
        ),
        migrations.AddField(
            model_name="department",
            name="show_orders",
            field=models.BooleanField(default=False, verbose_name="عرض الطلبات"),
        ),
        migrations.AddField(
            model_name="department",
            name="show_reports",
            field=models.BooleanField(default=False, verbose_name="عرض التقارير"),
        ),
    ]
