# Generated by Django 5.2.6 on 2025-12-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_masterqrcode_branchdevice_token_system"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="masterqrcode",
            new_name="accounts_ma_code_a66b95_idx",
            old_name="accounts_ma_code_43c0ed_idx",
        ),
        migrations.RenameIndex(
            model_name="masterqrcode",
            new_name="accounts_ma_created_7916c3_idx",
            old_name="accounts_ma_created_2fce03_idx",
        ),
        migrations.AddField(
            model_name="branch",
            name="require_device_lock",
            field=models.BooleanField(
                default=True,
                help_text="إذا كان مفعل، يتطلب من موظفي هذا الفرع تسجيل الدخول من أجهزة مسجلة فقط",
                verbose_name="قفل الأجهزة",
            ),
        ),
    ]
