# Generated by Django 5.2.6 on 2025-12-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_add_branch_device_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='require_device_lock',
            field=models.BooleanField(default=False, help_text='إذا كان مفعل، يتطلب من موظفي هذا الفرع تسجيل الدخول من أجهزة مسجلة فقط', verbose_name='قفل الأجهزة'),
        ),
    ]
