# Generated by Django 6.0 on 2025-12-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_change_branch_lock_default_false"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchdevice",
            name="hardware_serial",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="الرقم التسلسلي للجهاز (Hardware UUID/Serial) - احتياطي",
                max_length=200,
                null=True,
                verbose_name="الرقم التسلسلي للجهاز",
            ),
        ),
        migrations.AlterField(
            model_name="unauthorizeddeviceattempt",
            name="hardware_serial",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="الرقم التسلسلي"
            ),
        ),
    ]
