# Generated by Django 5.2.6 on 2025-12-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_fix_hardware_serial_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unauthorizeddeviceattempt",
            name="hardware_serial",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="الرقم التسلسلي للجهاز",
            ),
        ),
    ]
