# Generated by Django 6.0 on 2025-12-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_alter_unauthorizeddeviceattempt_hardware_serial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchdevice",
            name="manual_identifier",
            field=models.CharField(
                blank=True,
                help_text="رقم تعريفي يدوي للجهاز (مثل: Asset Tag، رقم الجهاز، أو معرّف من اختيارك) - يساعد في التمييز بين الأجهزة المتشابهة",
                max_length=100,
                verbose_name="معرّف الجهاز اليدوي",
            ),
        ),
    ]
