# Generated by Django 6.0 on 2025-12-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_add_manual_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_general_manager",
        ),
        migrations.AddField(
            model_name="user",
            name="is_factory_accountant",
            field=models.BooleanField(default=False, verbose_name="محاسب مصنع"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_sales_manager",
            field=models.BooleanField(default=False, verbose_name="مدير مبيعات"),
        ),
    ]
