# Generated by Django 6.0 on 2025-12-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_update_roles_and_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_export",
            field=models.BooleanField(
                default=False,
                help_text="السماح للمستخدم بتصدير البيانات إلى Excel",
                verbose_name="إمكانية التصدير",
            ),
        ),
    ]
