# Generated by Django 6.0 on 2026-01-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_remove_hardware_serial_and_fingerprint"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="branchdevice",
            name="accounts_br_device__3fe610_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="authorized_devices",
            field=models.ManyToManyField(
                blank=True,
                help_text="الأجهزة التي يمكن للمستخدم الدخول منها (حد أقصى 20 جهاز)",
                related_name="authorized_users",
                to="accounts.branchdevice",
                verbose_name="الأجهزة المصرح بها",
            ),
        ),
    ]
