# Generated by Django 6.0 on 2026-01-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_add_authorized_devices_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_retail",
            field=models.BooleanField(default=True, verbose_name="عمليات قطاعي"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_wholesale",
            field=models.BooleanField(default=False, verbose_name="عمليات جملة"),
        ),
    ]
