# Generated by Django 6.0 on 2026-01-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_user_is_retail_user_is_wholesale"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_edit_price",
            field=models.BooleanField(
                default=False,
                help_text="السماح للمستخدم بتعديل أسعار المنتجات في الطلبات يدوياً",
                verbose_name="تعديل الأسعار",
            ),
        ),
    ]
