# Generated by Django 6.0 on 2026-01-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_user_can_edit_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DashboardYearSettings",
        ),
    ]
