# Generated by Django 6.0 on 2026-01-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_delete_dashboardyearsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_traffic_manager",
            field=models.BooleanField(default=False, verbose_name="مدير حركة"),
        ),
    ]
