# Generated by Django 5.1.5 on 2026-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_user_is_traffic_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_apply_administrative_discount",
            field=models.BooleanField(
                default=False,
                help_text="السماح للمستخدم بتطبيق خصم إداري على الطلبات",
                verbose_name="صلاحية الخصم الإداري",
            ),
        ),
    ]
