# Generated by Django 5.1.5 on 2026-02-11 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0054_user_can_apply_administrative_discount"),
        ("inventory", "0034_update_productsetitem_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_warehouses",
            field=models.ManyToManyField(
                blank=True,
                help_text="المستودعات المخصصة لموظف المستودع - يمكن تحديد أكثر من مستودع",
                related_name="assigned_staff",
                to="inventory.warehouse",
                verbose_name="المستودعات المخصصة",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="assigned_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="المستودع المخصص لموظف المستودع (قديم - استخدم المستودعات المخصصة)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_staff",
                to="inventory.warehouse",
                verbose_name="المستودع المخصص",
            ),
        ),
    ]
