# Generated by Django 5.1.5 on 2026-02-11 16:15

from django.db import migrations


def copy_warehouse_fk_to_m2m(apps, schema_editor):
    """نسخ المستودع المخصص (FK) إلى حقل المستودعات المتعددة (M2M)"""
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(
        is_warehouse_staff=True, assigned_warehouse__isnull=False
    ):
        user.assigned_warehouses.add(user.assigned_warehouse)


def reverse_copy(apps, schema_editor):
    """عكس العملية - لا حاجة لحذف البيانات"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_add_assigned_warehouses_m2m"),
    ]

    operations = [
        migrations.RunPython(copy_warehouse_fk_to_m2m, reverse_copy),
    ]
