# Generated by Django 5.1.5 on 2026-02-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_copy_assigned_warehouse_to_m2m"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("inventory", "0035_audit_improvements_final"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["branch", "is_active"], name="user_branch_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_salesperson", "is_active"], name="user_sales_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["-date_joined"], name="user_date_joined_idx"),
        ),
    ]
