# Generated by Django 5.1.15 on 2026-02-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_user_user_branch_active_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchmessage",
            name="animation",
            field=models.CharField(
                choices=[
                    ("fade", "تلاشي"),
                    ("slide-down", "انزلاق من الأعلى"),
                    ("slide-up", "انزلاق من الأسفل"),
                    ("zoom", "تكبير"),
                    ("bounce", "ارتداد"),
                    ("flip", "انقلاب"),
                ],
                default="zoom",
                max_length=20,
                verbose_name="نوع الحركة",
            ),
        ),
        migrations.AddField(
            model_name="branchmessage",
            name="border_style",
            field=models.CharField(
                choices=[
                    ("none", "بدون حدود"),
                    ("thin", "حد رفيع"),
                    ("accent", "حد ملون - يسار"),
                    ("accent-top", "حد ملون - أعلى"),
                    ("rounded", "حدود دائرية"),
                ],
                default="none",
                max_length=20,
                verbose_name="نمط الحدود",
            ),
        ),
        migrations.AddField(
            model_name="branchmessage",
            name="custom_bg_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="كود اللون بصيغة HEX مثل #f0f0f0",
                max_length=7,
                verbose_name="لون خلفية مخصص",
            ),
        ),
        migrations.AddField(
            model_name="branchmessage",
            name="custom_text_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="كود اللون بصيغة HEX مثل #333333",
                max_length=7,
                verbose_name="لون نص مخصص",
            ),
        ),
        migrations.AddField(
            model_name="branchmessage",
            name="popup_size",
            field=models.CharField(
                choices=[
                    ("small", "صغير - 380px"),
                    ("medium", "متوسط - 480px"),
                    ("large", "كبير - 600px"),
                    ("full", "عرض كامل"),
                ],
                default="medium",
                max_length=10,
                verbose_name="حجم النافذة",
            ),
        ),
        migrations.AddField(
            model_name="branchmessage",
            name="position",
            field=models.CharField(
                choices=[
                    ("center", "وسط الشاشة"),
                    ("top", "أعلى"),
                    ("top-start", "أعلى اليمين"),
                    ("top-end", "أعلى اليسار"),
                    ("bottom", "أسفل"),
                    ("bottom-start", "أسفل اليمين"),
                    ("bottom-end", "أسفل اليسار"),
                ],
                default="center",
                max_length=20,
                verbose_name="موقع الرسالة",
            ),
        ),
        migrations.AddField(
            model_name="branchmessage",
            name="show_icon",
            field=models.BooleanField(default=True, verbose_name="إظهار الأيقونة"),
        ),
        migrations.AddField(
            model_name="branchmessage",
            name="show_shadow",
            field=models.BooleanField(default=True, verbose_name="إظهار الظل"),
        ),
        migrations.AddField(
            model_name="branchmessage",
            name="show_swal_icon",
            field=models.BooleanField(
                default=False,
                help_text="الأيقونة الكبيرة الدائرية الخاصة بـ SweetAlert2",
                verbose_name="إظهار أيقونة SweetAlert الدائرية",
            ),
        ),
        migrations.AddField(
            model_name="branchmessage",
            name="text_color",
            field=models.CharField(
                choices=[
                    ("dark", "داكن"),
                    ("light", "فاتح"),
                    ("primary", "أزرق"),
                    ("danger", "أحمر"),
                    ("success", "أخضر"),
                    ("custom", "مخصص"),
                ],
                default="dark",
                max_length=20,
                verbose_name="لون النص",
            ),
        ),
        migrations.AlterField(
            model_name="branchmessage",
            name="display_style",
            field=models.CharField(
                choices=[
                    ("sweetalert2", "SweetAlert2 - حديث وأنيق"),
                    ("toast", "إشعار علوي - صغير وسريع"),
                    ("banner", "شريط علوي - بارز"),
                    ("card", "بطاقة جانبية - هادئ"),
                ],
                default="sweetalert2",
                max_length=20,
                verbose_name="نمط العرض",
            ),
        ),
        migrations.AlterField(
            model_name="branchmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("welcome", "رسالة ترحيبية"),
                    ("goal", "هدف"),
                    ("announcement", "إعلان"),
                    ("holiday", "إجازة"),
                    ("info", "معلومات"),
                    ("urgent", "عاجل"),
                    ("congratulation", "تهنئة"),
                    ("reminder", "تذكير"),
                ],
                default="announcement",
                max_length=20,
                verbose_name="نوع الرسالة",
            ),
        ),
    ]
