# Generated by Django 5.1.15 on 2026-03-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0058_branch_message_enhanced_customization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_decorator_dept_manager",
            field=models.BooleanField(
                default=False, verbose_name="مدير قسم مهندسي الديكور"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_decorator_dept_staff",
            field=models.BooleanField(
                default=False, verbose_name="موظف قسم مهندسي الديكور"
            ),
        ),
    ]
