# Generated by Django 5.1.15 on 2026-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0060_external_sales_groups_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="show_external_sales",
            field=models.BooleanField(
                default=False, verbose_name="عرض المبيعات الخارجية"
            ),
        ),
    ]
