# Generated by Django 5.1.15 on 2026-03-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_remove_factory_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_external_sales_director",
            field=models.BooleanField(
                default=False, verbose_name="مدير عام المبيعات الخارجية"
            ),
        ),
    ]
