# Generated by Django 5.1.15 on 2026-03-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0063_add_external_sales_director"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_issue_promo_code",
            field=models.BooleanField(
                default=False,
                help_text="السماح للمستخدم بإنشاء أكواد خصم ترويجية",
                verbose_name="إصدار أكواد خصم",
            ),
        ),
    ]
