# Generated by Django 4.2.21 on 2025-08-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_initial_fixed'),
        ('inventory', '0002_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='accounts.branch', verbose_name='الفرع'),
        ),
    ]
