# Generated by Django 4.2.21 on 2025-08-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_warehouse_timestamps_and_creator'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['name', 'code'], name='inventory_w_name_36c4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['created_at'], name='inventory_w_created_6e6d24_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='inventory_w_is_acti_3ddeac_idx'),
        ),
    ]
