# Generated by Django 4.2.21 on 2025-08-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_warehouse_inventory_w_name_36c4d1_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EGP", "جنيه مصري"),
                    ("USD", "دولار أمريكي"),
                    ("EUR", "يورو"),
                ],
                default="EGP",
                max_length=3,
                verbose_name="العملة",
            ),
        ),
    ]
