# Generated by Django 5.2.6 on 2025-10-01 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_product_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_number",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="رقم التحويل",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "قيد الانتظار"),
                            ("approved", "تمت الموافقة"),
                            ("in_transit", "قيد النقل"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغي"),
                            ("rejected", "مرفوض"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "transfer_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التحويل"
                    ),
                ),
                (
                    "expected_arrival_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الوصول المتوقع"
                    ),
                ),
                (
                    "actual_arrival_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الوصول الفعلي"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("reason", models.TextField(blank=True, verbose_name="سبب التحويل")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الموافقة"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإكمال"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تمت الموافقة بواسطة",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإكمال بواسطة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="inventory.warehouse",
                        verbose_name="من مستودع",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="inventory.warehouse",
                        verbose_name="إلى مستودع",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحويل مخزني",
                "verbose_name_plural": "التحويلات المخزنية",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الكمية المطلوبة"
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الكمية المستلمة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_items",
                        to="inventory.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.stocktransfer",
                        verbose_name="التحويل",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر تحويل مخزني",
                "verbose_name_plural": "عناصر التحويل المخزني",
                "ordering": ["transfer", "product"],
            },
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["transfer_number"], name="transfer_number_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["from_warehouse"], name="transfer_from_wh_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["to_warehouse"], name="transfer_to_wh_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["status"], name="transfer_status_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["transfer_date"], name="transfer_date_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["created_at"], name="transfer_created_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransferitem",
            index=models.Index(fields=["transfer"], name="transfer_item_transfer_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransferitem",
            index=models.Index(fields=["product"], name="transfer_item_product_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="stocktransferitem",
            unique_together={("transfer", "product")},
        ),
    ]
