# Generated by Django 5.2.6 on 2025-10-20 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_stocktransfer_stocktransferitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkUploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("products", "رفع منتجات"),
                            ("stock_update", "تحديث مخزون"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "قيد المعالجة"),
                            ("completed", "مكتمل"),
                            ("completed_with_errors", "مكتمل مع أخطاء"),
                            ("failed", "فشل"),
                        ],
                        default="processing",
                        max_length=30,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="اسم الملف"),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي الصفوف"
                    ),
                ),
                (
                    "processed_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد المعالج"),
                ),
                (
                    "created_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد المنشأ"),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد المحدث"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الأخطاء"),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="خيارات العملية"
                    ),
                ),
                (
                    "created_warehouses",
                    models.JSONField(
                        blank=True, default=list, verbose_name="المستودعات المنشأة"
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="ملخص العملية")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإكمال"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم بواسطة",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_logs",
                        to="inventory.warehouse",
                        verbose_name="المستودع",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل رفع جماعي",
                "verbose_name_plural": "سجلات الرفع الجماعي",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkUploadError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField(verbose_name="رقم الصف")),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("validation", "خطأ في التحقق"),
                            ("duplicate", "تكرار"),
                            ("missing_data", "بيانات ناقصة"),
                            ("invalid_data", "بيانات غير صالحة"),
                            ("database", "خطأ في قاعدة البيانات"),
                            ("processing", "خطأ في المعالجة"),
                            ("other", "خطأ آخر"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="نوع الخطأ",
                    ),
                ),
                ("error_message", models.TextField(verbose_name="رسالة الخطأ")),
                (
                    "row_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات الصف"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "upload_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="inventory.bulkuploadlog",
                        verbose_name="سجل الرفع",
                    ),
                ),
            ],
            options={
                "verbose_name": "خطأ رفع جماعي",
                "verbose_name_plural": "أخطاء الرفع الجماعي",
                "ordering": ["upload_log", "row_number"],
            },
        ),
        migrations.AddIndex(
            model_name="bulkuploadlog",
            index=models.Index(fields=["upload_type"], name="upload_log_type_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkuploadlog",
            index=models.Index(fields=["status"], name="upload_log_status_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkuploadlog",
            index=models.Index(fields=["created_at"], name="upload_log_created_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkuploadlog",
            index=models.Index(fields=["created_by"], name="upload_log_user_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkuploaderror",
            index=models.Index(fields=["upload_log"], name="upload_error_log_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkuploaderror",
            index=models.Index(fields=["error_type"], name="upload_error_type_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkuploaderror",
            index=models.Index(fields=["row_number"], name="upload_error_row_idx"),
        ),
    ]
