# Generated by Django 4.2.21 on 2025-06-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='EGP', max_length=3, verbose_name='العملة'),
        ),
    ]
