# Generated by Django 5.2.6 on 2025-11-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_bulkuploaderror_result_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="is_official_fabric_warehouse",
            field=models.BooleanField(
                default=False,
                help_text="تحديد إذا كان هذا المستودع معتمد رسمياً لتخزين الأقمشة",
                verbose_name="مستودع رسمي للأقمشة",
            ),
        ),
    ]
