# Generated by Django 5.2.6 on 2025-11-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_add_fabric_warehouse_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkuploadlog",
            name="task_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="معرّف المهمة"
            ),
        ),
    ]
