# Generated by Django 5.2.6 on 2025-11-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_bulkuploadlog_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
