# Generated by Django 5.2.6 on 2025-12-01 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_increase_product_code_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockalert",
            options={
                "ordering": ["-is_pinned", "-is_urgent", "-created_at"],
                "verbose_name": "تنبيه مخزون",
                "verbose_name_plural": "تنبيهات المخزون",
            },
        ),
        migrations.AddField(
            model_name="stockalert",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_stock_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإنشاء بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="مثبت"),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="is_urgent",
            field=models.BooleanField(default=False, verbose_name="عاجل"),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="quantity_after",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="الكمية الحالية",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="quantity_before",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="الكمية السابقة",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="threshold_limit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="حد التنبيه"
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="عنوان التنبيه"
            ),
        ),
        migrations.AddField(
            model_name="warehouselocation",
            name="capacity",
            field=models.PositiveIntegerField(
                default=1000, help_text="السعة القصوى للموقع", verbose_name="السعة"
            ),
        ),
        migrations.AddField(
            model_name="warehouselocation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاريخ الإنشاء",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warehouselocation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="warehouselocation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
    ]
