# Generated by Django 5.2.6 on 2025-12-03 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_stockalert_options_stockalert_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["code"], name="product_code_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="product_name_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "created_at"], name="product_cat_crt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="product_price_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["product", "warehouse", "transaction_date"],
                name="stock_prd_wrh_dt_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["warehouse", "transaction_date"], name="stock_wrh_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["transaction_type", "transaction_date"],
                name="stock_type_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["reason", "transaction_date"], name="stock_reason_date_idx"
            ),
        ),
    ]
