# Generated by Django 5.2.6 on 2025-12-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_add_comprehensive_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="category_parent_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_currency_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_unit_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_min_stock_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_cat_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_updated_idx",
        ),
        migrations.RemoveIndex(
            model_name="stocktransaction",
            name="stock_created_by_idx",
        ),
        migrations.RemoveIndex(
            model_name="stocktransaction",
            name="stock_balance_idx",
        ),
        migrations.RemoveIndex(
            model_name="stocktransaction",
            name="stock_date_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="warehouse",
            name="warehouse_branch_idx",
        ),
        migrations.RemoveIndex(
            model_name="warehouse",
            name="warehouse_manager_idx",
        ),
    ]
