# Generated by Django 6.0 on 2025-12-17 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_add_wizard_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="اسم المنتج الأساسي"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="الكود الأساسي"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="السعر الافتراضي لجميع المتغيرات",
                        max_digits=10,
                        verbose_name="السعر الأساسي",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "جنيه مصري"),
                            ("SAR", "ريال سعودي"),
                            ("USD", "دولار أمريكي"),
                            ("EUR", "يورو"),
                        ],
                        default="EGP",
                        max_length=3,
                        verbose_name="العملة",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "قطعة"),
                            ("kg", "كيلوجرام"),
                            ("gram", "جرام"),
                            ("liter", "لتر"),
                            ("meter", "متر"),
                            ("box", "علبة"),
                            ("pack", "عبوة"),
                            ("dozen", "دستة"),
                            ("roll", "لفة"),
                            ("sheet", "ورقة"),
                        ],
                        default="piece",
                        max_length=10,
                        verbose_name="الوحدة",
                    ),
                ),
                (
                    "minimum_stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الحد الأدنى للمخزون"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="base_products",
                        to="inventory.category",
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_base_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "منتج أساسي",
                "verbose_name_plural": "المنتجات الأساسية",
                "ordering": ["name"],
                "permissions": [
                    ("manage_base_products", "إدارة المنتجات الأساسية"),
                    ("bulk_price_update", "تحديث الأسعار بالجملة"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ColorAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="اسم اللون")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز اللون"
                    ),
                ),
                (
                    "hex_code",
                    models.CharField(
                        blank=True,
                        help_text="مثال: #FF5733",
                        max_length=7,
                        verbose_name="كود اللون HEX",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
            ],
            options={
                "verbose_name": "لون",
                "verbose_name_plural": "الألوان",
                "ordering": ["display_order", "name"],
                "indexes": [models.Index(fields=["code"], name="color_code_idx")],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant_code",
                    models.CharField(
                        help_text="مثال: C 004, C1, OFF WHITE",
                        max_length=50,
                        verbose_name="كود المتغير",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="يُستخدم إذا لم يكن اللون موجوداً في جدول الألوان",
                        max_length=30,
                        verbose_name="كود اللون",
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="اتركه فارغاً لاستخدام السعر الأساسي",
                        max_digits=10,
                        null=True,
                        verbose_name="تجاوز السعر",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="الباركود",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "base_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="inventory.baseproduct",
                        verbose_name="المنتج الأساسي",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants",
                        to="inventory.colorattribute",
                        verbose_name="اللون",
                    ),
                ),
                (
                    "legacy_product",
                    models.OneToOneField(
                        blank=True,
                        help_text="للتوافق مع النظام القديم",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variant_link",
                        to="inventory.product",
                        verbose_name="المنتج القديم",
                    ),
                ),
            ],
            options={
                "verbose_name": "متغير منتج",
                "verbose_name_plural": "متغيرات المنتجات",
                "ordering": ["base_product", "variant_code"],
                "permissions": [
                    ("manage_variants", "إدارة المتغيرات"),
                    ("override_variant_price", "تجاوز سعر المتغير"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر القديم"
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر الجديد"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("manual", "يدوي"),
                            ("percentage", "نسبة مئوية"),
                            ("fixed", "قيمة ثابتة"),
                            ("reset", "إعادة للأساسي"),
                            ("bulk", "تحديث جماعي"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="نوع التغيير",
                    ),
                ),
                (
                    "change_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="النسبة أو القيمة المطبقة",
                        max_digits=10,
                        null=True,
                        verbose_name="قيمة التغيير",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التغيير"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التغيير بواسطة",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="inventory.productvariant",
                        verbose_name="المتغير",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل سعر",
                "verbose_name_plural": "سجل الأسعار",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="VariantStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الكمية الحالية",
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="الكمية المحجوزة للطلبات غير المكتملة",
                        max_digits=10,
                        verbose_name="الكمية المحجوزة",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_stocks",
                        to="inventory.productvariant",
                        verbose_name="المتغير",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_stocks",
                        to="inventory.warehouse",
                        verbose_name="المستودع",
                    ),
                ),
            ],
            options={
                "verbose_name": "مخزون متغير",
                "verbose_name_plural": "مخزونات المتغيرات",
            },
        ),
        migrations.AddIndex(
            model_name="baseproduct",
            index=models.Index(fields=["code"], name="base_product_code_idx"),
        ),
        migrations.AddIndex(
            model_name="baseproduct",
            index=models.Index(fields=["name"], name="base_product_name_idx"),
        ),
        migrations.AddIndex(
            model_name="baseproduct",
            index=models.Index(fields=["category"], name="base_product_cat_idx"),
        ),
        migrations.AddIndex(
            model_name="baseproduct",
            index=models.Index(fields=["is_active"], name="base_product_active_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["base_product"], name="variant_base_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["variant_code"], name="variant_code_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["color"], name="variant_color_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["is_active"], name="variant_active_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["barcode"], name="variant_barcode_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("base_product", "variant_code")},
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(fields=["variant"], name="price_hist_variant_idx"),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(fields=["changed_at"], name="price_hist_date_idx"),
        ),
        migrations.AddIndex(
            model_name="variantstock",
            index=models.Index(
                fields=["variant", "warehouse"], name="var_stock_var_wh_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variantstock",
            index=models.Index(fields=["current_quantity"], name="var_stock_qty_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="variantstock",
            unique_together={("variant", "warehouse")},
        ),
    ]
