# Generated by Django 6.0 on 2025-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_variant_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseproduct",
            name="code",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="الكود الأساسي"
            ),
        ),
    ]
