# Generated by Django 6.0 on 2025-12-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_increase_baseproduct_code_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorattribute",
            name="code",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="رمز اللون"
            ),
        ),
        migrations.AlterField(
            model_name="colorattribute",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم اللون"),
        ),
    ]
