# Generated by Django 6.0 on 2025-12-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_increase_colorattribute_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("manual", "يدوي"),
                    ("percentage", "نسبة مئوية"),
                    ("fixed", "قيمة ثابتة"),
                    ("reset", "إعادة للأساسي"),
                    ("bulk", "تحديث جماعي"),
                    ("base_update", "تحديث السعر الأساسي"),
                ],
                default="manual",
                max_length=20,
                verbose_name="نوع التغيير",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EGP", "جنيه مصري"),
                    ("SAR", "ريال سعودي"),
                    ("USD", "دولار أمريكي"),
                    ("EUR", "يورو"),
                ],
                default="EGP",
                max_length=3,
                verbose_name="العملة",
            ),
        ),
    ]
