# Generated by Django 6.0 on 2025-12-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_use_egp_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="qr_code_base64",
            field=models.TextField(blank=True, null=True, verbose_name="رمز QR (مخزن)"),
        ),
    ]
