# Generated by Django 6.0 on 2025-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_add_qr_code_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="qr_code_base64",
            field=models.TextField(blank=True, null=True, verbose_name="رمز QR (مخزن)"),
        ),
    ]
