# Generated by Django 6.0 on 2025-12-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_baseproduct_qr_code_base64"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="cloudflare_synced",
            field=models.BooleanField(
                default=False,
                help_text="هل تم مزامنة هذا المنتج مع Cloudflare KV؟",
                verbose_name="تم المزامنة مع Cloudflare",
            ),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="آخر مرة تم فيها مزامنة المنتج مع Cloudflare",
                null=True,
                verbose_name="تاريخ آخر مزامنة",
            ),
        ),
    ]
