# Generated by Django 6.0 on 2026-01-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_add_cloudflare_sync_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="wholesale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="السعر لعملاء الجملة",
                max_digits=10,
                verbose_name="سعر الجملة",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="wholesale_price_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="اتركه فارغاً لاستخدام سعر الجملة الأساسي",
                max_digits=10,
                null=True,
                verbose_name="تجاوز سعر الجملة",
            ),
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="السعر الافتراضي لعملاء التجزئة",
                max_digits=10,
                verbose_name="السعر القطاعي",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="اتركه فارغاً لاستخدام السعر القطاعي الأساسي",
                max_digits=10,
                null=True,
                verbose_name="تجاوز السعر القطاعي",
            ),
        ),
    ]
