# Generated by Django 6.0 on 2026-01-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_wholesale_pricing_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="wholesale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="سعر الجملة للمنتج",
                max_digits=10,
                verbose_name="سعر الجملة",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="سعر التجزئة للمنتج",
                max_digits=10,
                verbose_name="السعر القطاعي",
            ),
        ),
    ]
