# Generated by Django 6.0 on 2026-01-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_add_wholesale_price_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="material",
            field=models.CharField(
                blank=True,
                default="Linen",
                max_length=100,
                verbose_name="نوع القماش (Material)",
            ),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="width",
            field=models.CharField(
                blank=True,
                default="280 cm",
                max_length=50,
                verbose_name="العرض (Width)",
            ),
        ),
    ]
