# Generated by Django 6.0 on 2026-01-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_baseproduct_material_baseproduct_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(
                blank=True,
                default="",
                help_text="نوع الخامة مثل: Linen, Cotton, Polyester",
                max_length=100,
                verbose_name="Material",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.CharField(
                blank=True,
                default="",
                help_text="عرض القماش مثل: 280 cm, 140 cm",
                max_length=50,
                verbose_name="Width",
            ),
        ),
    ]
