# Generated by Django 6.0 on 2026-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0028_add_material_width_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="productbatch",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="productbatch",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="warehouselocation",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="warehouselocation",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
    ]
