# Generated by Django 5.1.5 on 2026-02-07 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_increase_decimal_capacity_for_bulk_upload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثل: طقم أقمشة كلاسيكي",
                        max_length=200,
                        verbose_name="اسم المجموعة",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "cloudflare_synced",
                    models.BooleanField(
                        default=False, verbose_name="متزامن مع Cloudflare"
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر مزامنة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعة منتجات",
                "verbose_name_plural": "مجموعات المنتجات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductSetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="ترتيب عرض المنتج في المجموعة",
                        verbose_name="الترتيب",
                    ),
                ),
                (
                    "base_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.baseproduct",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "product_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.productset",
                        verbose_name="المجموعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "منتج في مجموعة",
                "verbose_name_plural": "منتجات في مجموعة",
                "ordering": ["display_order"],
                "unique_together": {("product_set", "base_product")},
            },
        ),
        migrations.AddField(
            model_name="productset",
            name="base_products",
            field=models.ManyToManyField(
                related_name="product_sets",
                through="inventory.ProductSetItem",
                to="inventory.baseproduct",
                verbose_name="المنتجات",
            ),
        ),
    ]
