# Generated by Django 5.1.15 on 2026-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0035_audit_improvements_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="إجمالي المبلغ"
            ),
        ),
    ]
