# Generated by Django 5.1.15 on 2026-03-01 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0036_standardize_decimal_precision"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="inventory_p_categor_607069_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_code_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_name_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="product_name_code_idx",
            old_name="inventory_p_name_af55cc_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="product_created_at_idx",
            old_name="inventory_p_created_081871_idx",
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="running_balance",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=18,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="الرصيد لا يمكن أن يكون سالباً"
                    )
                ],
                verbose_name="الرصيد المتحرك",
            ),
        ),
    ]
