# Generated by Django 5.1.15 on 2026-03-01 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0037_fix_indexes_running_balance_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryadjustment",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="المستودع الذي تُطبّق عليه التسوية — إذا لم يُحدَّد يُستخدم المستودع الافتراضي",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_adjustments",
                to="inventory.warehouse",
                verbose_name="المستودع",
            ),
        ),
    ]
