# Generated by Django 5.1.15 on 2026-03-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0038_inventory_adjustment_add_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="original_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="المستودع الذي تمت فيه المعاملة أصلاً قبل النقل الكامل",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="migrated_transactions",
                to="inventory.warehouse",
                verbose_name="المستودع الأصلي",
            ),
        ),
    ]
