# Generated by Django 5.1.15 on 2026-03-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0032_alter_product_deleted_by_and_more"),
        ("inventory", "0039_add_original_warehouse_field"),
    ]

    operations = []
