# Generated by Django 4.2.9 on 2025-05-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('reports', '0002_alter_report_report_type'),
    ]

    operations = [
    ]
