# Generated by Django 5.2.6 on 2025-12-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_add_seller_activity_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("sales", "تقرير المبيعات"),
                    ("production", "تقرير الإنتاج"),
                    ("inventory", "تقرير المخزون"),
                    ("financial", "تقرير مالي"),
                    ("analytics", "تقرير تحليلي"),
                    ("seller_activity", "تقرير نشاط البائعين"),
                    ("custom", "تقرير مخصص"),
                ],
                max_length=20,
                verbose_name="نوع التقرير",
            ),
        ),
    ]
