# Generated by Django 5.2 on 2025-05-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_merge_0002_add_indexes_0002_alter_report_report_type'),
    ]

    operations = [
        # تم تعديل الملف لتجنب محاولة إزالة فهارس غير موجودة
        # سنقوم بإضافة عملية فارغة بدلاً من ذلك
    ]
