# Generated by Django 6.0 on 2026-01-28 13:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("installations", "0022_installationschedule_vehicle_mission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallationAccountingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_price_per_window",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("35.00"),
                        help_text="السعر الافتراضي لتركيب الشباك الواحد",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="سعر الشباك الافتراضي",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "إعدادات حسابات التركيبات",
                "verbose_name_plural": "إعدادات حسابات التركيبات",
            },
        ),
        migrations.CreateModel(
            name="InstallationCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("pending", "معلق"),
                            ("completed", "مكتمل"),
                            ("paid", "مدفوع"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "windows_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="عدد الشبابيك التي تم تركيبها (يتم جلبها من الجدولة)",
                        verbose_name="عدد الشبابيك",
                    ),
                ),
                (
                    "price_per_window",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="سعر التركيب للشباك الواحد لهذا الطلب",
                        max_digits=10,
                        verbose_name="سعر الشباك",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="عدد الشبابيك × سعر الشباك",
                        max_digits=10,
                        verbose_name="إجمالي التكلفة",
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="تاريخ إكمال التركيب",
                        null=True,
                        verbose_name="تاريخ الإكمال",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="تاريخ سداد المستحقات",
                        null=True,
                        verbose_name="تاريخ الدفع",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "installation_schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_card",
                        to="installations.installationschedule",
                        verbose_name="جدولة التركيب",
                    ),
                ),
            ],
            options={
                "verbose_name": "بطاقة محاسبة التركيب",
                "verbose_name_plural": "بطاقات محاسبة التركيبات",
                "ordering": ["-completion_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TechnicianShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_windows",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="حصة الفني من عدد الشبابيك",
                        max_digits=10,
                        verbose_name="عدد الشبابيك المخصصة",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="حصة الفني من المبلغ الإجمالي",
                        max_digits=10,
                        verbose_name="المبلغ المستحق",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="مدفوع"
                    ),
                ),
                (
                    "paid_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الدفع"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="installation_accounting.installationcard",
                        verbose_name="بطاقة التركيب",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installation_shares",
                        to="installations.technician",
                        verbose_name="الفني",
                    ),
                ),
            ],
            options={
                "verbose_name": "حصة فني",
                "verbose_name_plural": "حصص الفنيين",
                "ordering": ["card", "technician"],
            },
        ),
        migrations.AddIndex(
            model_name="installationcard",
            index=models.Index(fields=["status"], name="instcard_status_idx"),
        ),
        migrations.AddIndex(
            model_name="installationcard",
            index=models.Index(fields=["completion_date"], name="instcard_date_idx"),
        ),
        migrations.AddIndex(
            model_name="technicianshare",
            index=models.Index(fields=["is_paid"], name="tech_share_paid_idx"),
        ),
        migrations.AddIndex(
            model_name="technicianshare",
            index=models.Index(
                fields=["technician", "is_paid"], name="tech_share_status_idx"
            ),
        ),
    ]
