# Generated by Django 5.1.5 on 2026-02-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installation_accounting", "0001_initial"),
        ("installations", "0024_customerdebt_inst_debt_cust_paid_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installationcard",
            name="installation_schedule",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounting_card",
                to="installations.installationschedule",
                verbose_name="جدولة التركيب",
            ),
        ),
    ]
