# Generated by Django 5.1.15 on 2026-02-15 14:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "installation_accounting",
            "0002_alter_installationcard_installation_schedule",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="installationaccountingsettings",
            name="default_price_per_window",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("35.00"),
                help_text="السعر الافتراضي لتركيب الشباك الواحد",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="سعر الشباك الافتراضي",
            ),
        ),
        migrations.AlterField(
            model_name="installationcard",
            name="price_per_window",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="سعر التركيب للشباك الواحد لهذا الطلب",
                max_digits=15,
                verbose_name="سعر الشباك",
            ),
        ),
        migrations.AlterField(
            model_name="installationcard",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="عدد الشبابيك × سعر الشباك",
                max_digits=15,
                verbose_name="إجمالي التكلفة",
            ),
        ),
        migrations.AlterField(
            model_name="technicianshare",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="حصة الفني من المبلغ الإجمالي",
                max_digits=15,
                verbose_name="المبلغ المستحق",
            ),
        ),
        migrations.AlterField(
            model_name="technicianshare",
            name="assigned_windows",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="حصة الفني من عدد الشبابيك",
                max_digits=12,
                verbose_name="عدد الشبابيك المخصصة",
            ),
        ),
    ]
