# Generated by Django 5.1.15 on 2026-02-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("installation_accounting", "0003_standardize_decimal_precision"),
        ("installations", "0026_standardize_decimal_precision"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="technicianshare",
            unique_together={("card", "technician")},
        ),
    ]
