# Generated by Django 5.2.4 on 2025-07-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'قيد الموافقة'), ('pending', 'قيد الانتظار'), ('in_progress', 'قيد التصنيع'), ('ready_for_installation', 'جاهز للتركيب'), ('completed', 'مكتمل'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending_approval', max_length=30, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='manufacturingorderitem',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'قيد الموافقة'), ('pending', 'قيد الانتظار'), ('in_progress', 'قيد التصنيع'), ('ready_for_installation', 'جاهز للتركيب'), ('completed', 'مكتمل'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=30, verbose_name='حالة العنصر'),
        ),
    ]
