# Generated by Django 4.2.21 on 2025-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='completion_date',
            field=models.DateTimeField(blank=True, help_text='يتم تعبئته تلقائياً عند اكتمال التصنيع أو جاهزية المنتج للتركيب', null=True, verbose_name='تاريخ الانتهاء'),
        ),
    ]
