# Generated by Django 5.2.4 on 2025-07-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_manufacturingorder_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='delivery_permit_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم إذن التسليم'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='delivery_recipient_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المستلم'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'قيد الموافقة'), ('pending', 'قيد الانتظار'), ('in_progress', 'قيد التصنيع'), ('ready_for_installation', 'جاهز للتركيب'), ('completed', 'مكتمل'), ('delivered', 'تم التسليم'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending_approval', max_length=30, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='manufacturingorderitem',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'قيد الموافقة'), ('pending', 'قيد الانتظار'), ('in_progress', 'قيد التصنيع'), ('ready_for_installation', 'جاهز للتركيب'), ('completed', 'مكتمل'), ('delivered', 'تم التسليم'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=30, verbose_name='حالة العنصر'),
        ),
    ]
