# Generated by Django 4.2.21 on 2025-08-14 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manufacturing", "0003_add_rejection_reply_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturingDisplaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم وصفي لهذا الإعداد",
                        max_length=200,
                        verbose_name="اسم الإعداد",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="وصف تفصيلي لهذا الإعداد",
                        null=True,
                        verbose_name="الوصف",
                    ),
                ),
                (
                    "allowed_statuses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="قائمة بالحالات التي يُسمح بعرضها. إذا كانت فارغة، ستُعرض جميع الحالات",
                        verbose_name="الحالات المسموحة",
                    ),
                ),
                (
                    "allowed_order_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="قائمة بأنواع الطلبات التي يُسمح بعرضها. إذا كانت فارغة، ستُعرض جميع الأنواع",
                        verbose_name="أنواع الطلبات المسموحة",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="تحديد ما إذا كان هذا الإعداد نشطاً أم لا",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="أولوية تطبيق هذا الإعداد (الرقم الأعلى له أولوية أكبر)",
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "apply_to_all_users",
                    models.BooleanField(
                        default=False,
                        help_text="إذا تم تفعيل هذا الخيار، سيتم تطبيق الإعداد على جميع المستخدمين",
                        verbose_name="تطبيق على جميع المستخدمين",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_manufacturing_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="المستخدمون الذين ينطبق عليهم هذا الإعداد. إذا كان فارغاً، ينطبق على جميع المستخدمين",
                        related_name="manufacturing_display_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدمون المستهدفون",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد عرض التصنيع",
                "verbose_name_plural": "إعدادات عرض التصنيع",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
