# Generated by Django 5.2.4 on 2025-07-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_add_delivery_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturingorder',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_orders', 'يمكن الموافقة على أوامر التصنيع'), ('can_reject_orders', 'يمكن رفض أوامر التصنيع')], 'verbose_name': 'أمر تصنيع', 'verbose_name_plural': 'أوامر التصنيع'},
        ),
    ]
