# Generated by Django 4.2.21 on 2025-08-14 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_useractivitylog_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturing', '0004_manufacturingdisplaysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم مميز لخط الإنتاج', max_length=200, unique=True, verbose_name='اسم خط الإنتاج')),
                ('description', models.TextField(blank=True, help_text='وصف تفصيلي لخط الإنتاج ونوع المنتجات التي ينتجها', null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, help_text='تحديد ما إذا كان خط الإنتاج نشطاً أم لا', verbose_name='نشط')),
                ('capacity_per_day', models.PositiveIntegerField(blank=True, help_text='عدد الطلبات التي يمكن إنتاجها يومياً (اختياري)', null=True, verbose_name='الطاقة الإنتاجية اليومية')),
                ('priority', models.PositiveIntegerField(default=1, help_text='أولوية خط الإنتاج (الرقم الأعلى له أولوية أكبر)', verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branches', models.ManyToManyField(blank=True, help_text='الفروع التي يخدمها هذا الخط', related_name='production_lines', to='accounts.branch', verbose_name='الفروع المرتبطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_lines', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'خط إنتاج',
                'verbose_name_plural': 'خطوط الإنتاج',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='production_line',
            field=models.ForeignKey(blank=True, help_text='خط الإنتاج المسؤول عن هذا الطلب', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturing_orders', to='manufacturing.productionline', verbose_name='خط الإنتاج'),
        ),
    ]
