# Generated by Django 4.2.21 on 2025-08-14 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manufacturing", "0006_productionline_supported_order_types_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturingDisplaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم مميز لإعداد العرض",
                        max_length=200,
                        unique=True,
                        verbose_name="اسم الإعداد",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="وصف تفصيلي لإعداد العرض",
                        null=True,
                        verbose_name="الوصف",
                    ),
                ),
                (
                    "allowed_statuses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="حدد الحالات التي ستظهر في هذا العرض",
                        verbose_name="الحالات المسموحة",
                    ),
                ),
                (
                    "allowed_order_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="حدد أنواع الطلبات التي ستظهر في هذا العرض",
                        verbose_name="أنواع الطلبات المسموحة",
                    ),
                ),
                (
                    "apply_to_all_users",
                    models.BooleanField(
                        default=False,
                        help_text="تطبيق هذا الإعداد على جميع المستخدمين",
                        verbose_name="تطبيق على جميع المستخدمين",
                    ),
                ),
                (
                    "show_customer_info",
                    models.BooleanField(
                        default=True,
                        help_text="إظهار معلومات العميل في الجدول",
                        verbose_name="إظهار معلومات العميل",
                    ),
                ),
                (
                    "show_order_details",
                    models.BooleanField(
                        default=True,
                        help_text="إظهار تفاصيل الطلب في الجدول",
                        verbose_name="إظهار تفاصيل الطلب",
                    ),
                ),
                (
                    "show_dates",
                    models.BooleanField(
                        default=True,
                        help_text="إظهار التواريخ في الجدول",
                        verbose_name="إظهار التواريخ",
                    ),
                ),
                (
                    "show_files",
                    models.BooleanField(
                        default=True,
                        help_text="إظهار الملفات المرفقة في الجدول",
                        verbose_name="إظهار الملفات",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="تحديد ما إذا كان هذا الإعداد نشطاً",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="تحديد ما إذا كان هذا الإعداد افتراضياً",
                        verbose_name="افتراضي",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="أولوية الإعداد (الرقم الأعلى له أولوية أكبر)",
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_display_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="المستخدمون الذين ينطبق عليهم هذا الإعداد",
                        related_name="display_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدمون المستهدفون",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد عرض التصنيع",
                "verbose_name_plural": "إعدادات عرض التصنيع",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
