# Generated by Django 4.2.21 on 2025-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0008_fix_null_allowed_order_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturingorderitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                help_text="يمكن إدخال قيم عشرية مثل 4.25 متر",
                max_digits=10,
                verbose_name="الكمية",
            ),
        ),
    ]
