# Generated by Django 4.2.21 on 2025-08-28 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manufacturing", "0009_alter_manufacturingorderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="bag_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم الشنطة"
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="cutting_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ التقطيع"
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="delivery_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ التسليم"
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="fabric_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات استلام الأقمشة"),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="fabric_received",
            field=models.BooleanField(default=False, verbose_name="تم استلام الأقمشة"),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="fabric_received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_fabric_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مستلم الأقمشة",
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="fabric_received_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ استلام الأقمشة"
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="permit_number",
            field=models.CharField(blank=True, max_length=50, verbose_name="رقم الإذن"),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="receiver_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="اسم المستلم"
            ),
        ),
    ]
