# Generated by Django 4.2.21 on 2025-08-30 08:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0004_alter_cuttingorder_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0028_alter_order_order_type"),
        ("manufacturing", "0010_manufacturingorderitem_bag_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FabricReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_code",
                    models.CharField(
                        help_text="كود فريد لاستلام الأقمشة",
                        max_length=50,
                        unique=True,
                        verbose_name="كود الاستلام",
                    ),
                ),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("cutting_order", "أمر تقطيع"),
                            ("manufacturing_order", "أمر تصنيع"),
                            ("direct", "استلام مباشر"),
                        ],
                        default="cutting_order",
                        max_length=20,
                        verbose_name="نوع الاستلام",
                    ),
                ),
                (
                    "bag_number",
                    models.CharField(max_length=50, verbose_name="رقم الشنطة"),
                ),
                (
                    "receipt_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الاستلام"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "cutting_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fabric_receipts",
                        to="cutting.cuttingorder",
                        verbose_name="أمر التقطيع",
                    ),
                ),
                (
                    "manufacturing_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fabric_receipts",
                        to="manufacturing.manufacturingorder",
                        verbose_name="أمر التصنيع",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fabric_receipts",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fabric_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "استلام أقمشة",
                "verbose_name_plural": "استلام الأقمشة",
                "ordering": ["-receipt_date"],
            },
        ),
        migrations.CreateModel(
            name="FabricReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="اسم المنتج"),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="الكمية المستلمة"
                    ),
                ),
                (
                    "item_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات العنصر"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "cutting_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cutting.cuttingorderitem",
                        verbose_name="عنصر التقطيع",
                    ),
                ),
                (
                    "fabric_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="manufacturing.fabricreceipt",
                        verbose_name="استلام الأقمشة",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.orderitem",
                        verbose_name="عنصر الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر استلام أقمشة",
                "verbose_name_plural": "عناصر استلام الأقمشة",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="fabricreceipt",
            index=models.Index(fields=["receipt_code"], name="fabric_receipt_code_idx"),
        ),
        migrations.AddIndex(
            model_name="fabricreceipt",
            index=models.Index(fields=["receipt_date"], name="fabric_receipt_date_idx"),
        ),
        migrations.AddIndex(
            model_name="fabricreceipt",
            index=models.Index(fields=["bag_number"], name="fabric_receipt_bag_idx"),
        ),
    ]
