# Generated by Django 4.2.21 on 2025-08-30 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0005_cuttingorder_rejection_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0028_alter_order_order_type"),
        ("manufacturing", "0011_fabricreceipt_fabricreceiptitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabricreceipt",
            name="permit_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="رقم الإذن"
            ),
        ),
        migrations.AddField(
            model_name="fabricreceipt",
            name="received_by_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="اسم المستلم"
            ),
        ),
        migrations.AlterField(
            model_name="fabricreceipt",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fabric_receipts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم المسجل",
            ),
        ),
        migrations.CreateModel(
            name="ProductReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permit_number",
                    models.CharField(max_length=100, verbose_name="رقم الإذن"),
                ),
                (
                    "bag_number",
                    models.CharField(max_length=50, verbose_name="رقم الشنطة"),
                ),
                (
                    "receipt_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الاستلام"
                    ),
                ),
                (
                    "received_by_name",
                    models.CharField(max_length=200, verbose_name="اسم المستلم"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "cutting_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_receipts",
                        to="cutting.cuttingorder",
                        verbose_name="أمر التقطيع",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_receipts",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "received_by_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسجل",
                    ),
                ),
            ],
            options={
                "verbose_name": "استلام منتج",
                "verbose_name_plural": "استلام المنتجات",
                "ordering": ["-receipt_date"],
                "indexes": [
                    models.Index(
                        fields=["permit_number"], name="product_receipt_permit_idx"
                    ),
                    models.Index(
                        fields=["receipt_date"], name="product_receipt_date_idx"
                    ),
                    models.Index(fields=["bag_number"], name="product_receipt_bag_idx"),
                ],
            },
        ),
    ]
