# Generated by Django 5.2.6 on 2025-09-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0011_alter_installationschedule_status_and_more"),
        ("manufacturing", "0012_fabricreceipt_permit_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingorder",
            name="modification_request",
            field=models.ForeignKey(
                blank=True,
                help_text="يربط أمر التصنيع بطلب التعديل إذا كان هذا الأمر خاصاً بتعديل.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manufacturing_orders",
                to="installations.modificationrequest",
                verbose_name="طلب التعديل",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturingorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("installation", "تركيب"),
                    ("custom", "تفصيل"),
                    ("accessory", "اكسسوار"),
                    ("modification", "تعديل"),
                ],
                max_length=20,
                verbose_name="نوع الطلب",
            ),
        ),
    ]
