# Generated by Django 5.2.6 on 2025-09-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0013_manufacturingorder_modification_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingorder",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="وصف أمر التصنيع أو تفاصيل التعديل إذا كان الأمر خاصاً بتعديل.",
                null=True,
                verbose_name="الوصف",
            ),
        ),
    ]
