# Generated by Django 5.2.6 on 2025-09-25 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0014_manufacturingorder_description"),
        ("orders", "0030_ordermodificationlog_is_manual_modification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturingorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturing_orders",
                to="orders.order",
                verbose_name="رقم الطلب",
            ),
        ),
    ]
