# Generated by Django 5.2.6 on 2025-09-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0007_section"),
        ("manufacturing", "0015_alter_manufacturingorder_order"),
        ("orders", "0033_add_detailed_status_log_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="cutting_item",
            field=models.ForeignKey(
                blank=True,
                help_text="ربط مباشر بعنصر التقطيع للتتبع الفردي",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manufacturing_items",
                to="cutting.cuttingorderitem",
                verbose_name="عنصر التقطيع",
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturing_items",
                to="orders.orderitem",
                verbose_name="عنصر الطلب الأصلي",
            ),
        ),
    ]
