# Generated by Django 5.2.6 on 2025-09-30 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0007_section"),
        ("manufacturing", "0016_add_cutting_item_link"),
        ("orders", "0033_add_detailed_status_log_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="manufacturingorderitem",
            index=models.Index(
                fields=["fabric_received", "fabric_received_date"],
                name="fabric_rcvd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingorderitem",
            index=models.Index(fields=["bag_number"], name="bag_number_idx"),
        ),
        migrations.AddIndex(
            model_name="manufacturingorderitem",
            index=models.Index(
                fields=["fabric_received", "bag_number"], name="fabric_bag_idx"
            ),
        ),
    ]
