# Generated by Django 5.2.6 on 2025-09-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_product_currency"),
        ("manufacturing", "0017_manufacturingorderitem_fabric_rcvd_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="نشط"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "warehouses_for_display",
                    models.ManyToManyField(
                        blank=True,
                        help_text="المستودعات التي تظهر عناصرها في تفاصيل أمر التصنيع",
                        related_name="manufacturing_display_settings",
                        to="inventory.warehouse",
                        verbose_name="المستودعات المعروضة",
                    ),
                ),
                (
                    "warehouses_for_meters_calculation",
                    models.ManyToManyField(
                        blank=True,
                        help_text="المستودعات التي يتم حساب أمتارها في badge إجمالي أمتار أمر التصنيع",
                        related_name="manufacturing_meters_settings",
                        to="inventory.warehouse",
                        verbose_name="المستودعات المحسوبة في الأمتار",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات التصنيع",
                "verbose_name_plural": "إعدادات التصنيع",
            },
        ),
    ]
