# Generated by Django 4.2.21 on 2025-10-07 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manufacturing", "0018_manufacturingsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturingRejectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        help_text="السبب الذي تم رفض أمر التصنيع من أجله",
                        verbose_name="سبب الرفض",
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الرفض"),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="الحالة السابقة",
                    ),
                ),
                (
                    "reply_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="الرد على الرفض"
                    ),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الرد"
                    ),
                ),
                (
                    "reply_read",
                    models.BooleanField(default=False, verbose_name="تم قراءة الرد"),
                ),
                (
                    "status_after_reply",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="الحالة بعد الرد",
                    ),
                ),
                (
                    "manufacturing_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejection_logs",
                        to="manufacturing.manufacturingorder",
                        verbose_name="أمر التصنيع",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_manufacturing_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الرفض بواسطة",
                    ),
                ),
                (
                    "replied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replied_manufacturing_rejections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الرد بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل رفض التصنيع",
                "verbose_name_plural": "سجلات رفض التصنيع",
                "ordering": ["-rejected_at"],
            },
        ),
    ]
