# Generated by Django 5.2.6 on 2025-10-08 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0019_add_rejection_log_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturingStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "قيد الموافقة"),
                            ("pending", "قيد الانتظار"),
                            ("in_progress", "قيد التصنيع"),
                            ("ready_install", "جاهز للتركيب"),
                            ("completed", "مكتمل"),
                            ("delivered", "تم التسليم"),
                            ("rejected", "مرفوض"),
                            ("cancelled", "ملغي"),
                        ],
                        help_text="الحالة السابقة",
                        max_length=30,
                        verbose_name="من حالة",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "قيد الموافقة"),
                            ("pending", "قيد الانتظار"),
                            ("in_progress", "قيد التصنيع"),
                            ("ready_install", "جاهز للتركيب"),
                            ("completed", "مكتمل"),
                            ("delivered", "تم التسليم"),
                            ("rejected", "مرفوض"),
                            ("cancelled", "ملغي"),
                        ],
                        help_text="الحالة الجديدة",
                        max_length=30,
                        verbose_name="إلى حالة",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ التغيير"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "order_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("installation", "تركيب"),
                            ("custom", "تفصيل"),
                            ("accessory", "اكسسوار"),
                            ("modification", "تعديل"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="نوع الطلب",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manufacturing_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التغيير بواسطة",
                    ),
                ),
                (
                    "manufacturing_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="manufacturing.manufacturingorder",
                        verbose_name="أمر التصنيع",
                    ),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="manufacturing.productionline",
                        verbose_name="خط الإنتاج",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حالة التصنيع",
                "verbose_name_plural": "سجلات حالات التصنيع",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["manufacturing_order", "changed_at"],
                        name="manufacturi_manufac_7938ef_idx",
                    ),
                    models.Index(
                        fields=["from_status", "to_status"],
                        name="manufacturi_from_st_59a9db_idx",
                    ),
                    models.Index(
                        fields=["changed_at"], name="manufacturi_changed_b1b84b_idx"
                    ),
                    models.Index(
                        fields=["changed_by"], name="manufacturi_changed_2e7e59_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductionForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_date",
                    models.DateField(db_index=True, verbose_name="تاريخ التوقع"),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "يومي"),
                            ("weekly", "أسبوعي"),
                            ("monthly", "شهري"),
                            ("quarterly", "ربع سنوي"),
                            ("yearly", "سنوي"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="نوع الفترة",
                    ),
                ),
                (
                    "forecasted_orders_count",
                    models.IntegerField(default=0, verbose_name="عدد الطلبات المتوقع"),
                ),
                (
                    "actual_orders_count",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="عدد الطلبات الفعلي",
                    ),
                ),
                (
                    "forecasted_meters",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الأمتار المتوقعة",
                    ),
                ),
                (
                    "actual_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="الأمتار الفعلية",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("installation", "تركيب"),
                            ("custom", "تفصيل"),
                            ("accessory", "اكسسوار"),
                            ("modification", "تعديل"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="نوع الطلب",
                    ),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="مستوى الثقة في التوقع (0-100)",
                        max_digits=5,
                        verbose_name="مستوى الثقة (%)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forecasts",
                        to="manufacturing.productionline",
                        verbose_name="خط الإنتاج",
                    ),
                ),
            ],
            options={
                "verbose_name": "توقع إنتاج",
                "verbose_name_plural": "توقعات الإنتاج",
                "ordering": ["-forecast_date"],
                "indexes": [
                    models.Index(
                        fields=["forecast_date", "period_type"],
                        name="manufacturi_forecas_1e4fc9_idx",
                    ),
                    models.Index(
                        fields=["production_line", "forecast_date"],
                        name="manufacturi_product_4c1bfe_idx",
                    ),
                ],
                "unique_together": {
                    ("forecast_date", "period_type", "production_line", "order_type")
                },
            },
        ),
    ]
