# Generated by Django 4.2.21 on 2025-10-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0020_manufacturingstatuslog_productionforecast"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="manufacturingstatuslog",
            name="manufacturi_manufac_7938ef_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingstatuslog",
            name="manufacturi_from_st_59a9db_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingstatuslog",
            name="manufacturi_changed_b1b84b_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingstatuslog",
            name="manufacturi_changed_2e7e59_idx",
        ),
        migrations.RemoveField(
            model_name="manufacturingstatuslog",
            name="from_status",
        ),
        migrations.RemoveField(
            model_name="manufacturingstatuslog",
            name="order_type",
        ),
        migrations.RemoveField(
            model_name="manufacturingstatuslog",
            name="production_line",
        ),
        migrations.RemoveField(
            model_name="manufacturingstatuslog",
            name="to_status",
        ),
        migrations.AddField(
            model_name="manufacturingstatuslog",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "قيد الموافقة"),
                    ("pending", "قيد الانتظار"),
                    ("in_progress", "قيد التصنيع"),
                    ("ready_install", "جاهز للتركيب"),
                    ("completed", "مكتمل"),
                    ("delivered", "تم التسليم"),
                    ("rejected", "مرفوض"),
                    ("cancelled", "ملغي"),
                ],
                default="pending",
                help_text="الحالة بعد التغيير",
                max_length=30,
                verbose_name="الحالة الجديدة",
            ),
        ),
        migrations.AddField(
            model_name="manufacturingstatuslog",
            name="previous_status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "قيد الموافقة"),
                    ("pending", "قيد الانتظار"),
                    ("in_progress", "قيد التصنيع"),
                    ("ready_install", "جاهز للتركيب"),
                    ("completed", "مكتمل"),
                    ("delivered", "تم التسليم"),
                    ("rejected", "مرفوض"),
                    ("cancelled", "ملغي"),
                ],
                default="pending",
                help_text="الحالة قبل التغيير",
                max_length=30,
                verbose_name="الحالة السابقة",
            ),
        ),
        migrations.AlterModelTable(
            name="manufacturingstatuslog",
            table="manufacturing_manufacturingstatuslog",
        ),
    ]
