# Generated by Django 5.2.6 on 2025-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manufacturing",
            "0021_remove_manufacturingstatuslog_manufacturi_manufac_7938ef_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturingorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("installation", "تركيب"),
                    ("custom", "تفصيل"),
                    ("accessory", "اكسسوار"),
                    ("modification", "تعديل"),
                    ("delivery", "تسليم"),
                ],
                max_length=20,
                verbose_name="نوع الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="productionforecast",
            name="order_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("installation", "تركيب"),
                    ("custom", "تفصيل"),
                    ("accessory", "اكسسوار"),
                    ("modification", "تعديل"),
                    ("delivery", "تسليم"),
                ],
                max_length=20,
                null=True,
                verbose_name="نوع الطلب",
            ),
        ),
    ]
