# Generated by Django 5.2.6 on 2025-12-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0022_alter_manufacturingorder_order_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductionForecast",
        ),
    ]
