# Generated by Django 5.2.6 on 2025-12-03 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0013_installationschedule_inst_status_date_idx_and_more"),
        ("manufacturing", "0023_remove_production_forecast"),
        ("orders", "0073_add_accessory_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="manufacturingorder",
            index=models.Index(
                fields=["status", "order_type"], name="mfg_status_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingorder",
            index=models.Index(fields=["order", "status"], name="mfg_order_status_idx"),
        ),
        migrations.AddIndex(
            model_name="manufacturingorder",
            index=models.Index(
                fields=["status", "-created_at"], name="mfg_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingorder",
            index=models.Index(
                fields=["production_line", "status"], name="mfg_line_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingorder",
            index=models.Index(
                fields=["expected_delivery_date", "status"],
                name="mfg_delivery_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingorder",
            index=models.Index(
                fields=["order_type", "status", "-created_at"],
                name="mfg_type_status_date_idx",
            ),
        ),
    ]
