# Generated by Django 5.2.6 on 2025-12-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0025_add_comprehensive_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="manufacturingorder",
            name="mfg_contract_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorder",
            name="mfg_invoice_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorder",
            name="mfg_exit_permit_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorder",
            name="mfg_dlv_permit_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorder",
            name="mfg_completion_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorder",
            name="mfg_delivery_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorder",
            name="mfg_order_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorder",
            name="mfg_exp_dlv_sts_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorder",
            name="mfg_line_sts_crt_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorder",
            name="mfg_type_sts_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorderitem",
            name="mfg_item_order_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorderitem",
            name="mfg_item_orderitem_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorderitem",
            name="mfg_item_cutting_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorderitem",
            name="mfg_item_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorderitem",
            name="mfg_item_ord_rcvd_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorderitem",
            name="mfg_item_ord_sts_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorderitem",
            name="mfg_item_rcvd_by_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorderitem",
            name="mfg_item_cut_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="manufacturingorderitem",
            name="mfg_item_dlv_date_idx",
        ),
    ]
