# Generated by Django 6.0 on 2025-12-17 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cutting", "0011_add_production_line_delivery"),
        ("manufacturing", "0026_remove_manufacturingorder_mfg_contract_idx_and_more"),
        ("orders", "0077_draftorder_edit_history_draftorder_last_modified_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="delivered_to_production",
            field=models.BooleanField(
                default=False, verbose_name="تم التسليم لخط الإنتاج"
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="production_delivered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivered_production_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مُسلِّم خط الإنتاج",
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="production_delivery_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ التسليم لخط الإنتاج"
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="production_delivery_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات تسليم خط الإنتاج"),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="production_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manufacturing_items",
                to="manufacturing.productionline",
                verbose_name="خط الإنتاج",
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingorderitem",
            index=models.Index(
                fields=["delivered_to_production", "production_delivery_date"],
                name="prod_delivery_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingorderitem",
            index=models.Index(fields=["production_line"], name="prod_line_idx"),
        ),
    ]
