# Generated by Django 6.0 on 2025-12-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0027_add_production_line_delivery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturingorderitem",
            options={
                "permissions": [
                    ("can_receive_fabric", "يمكنه استلام الأقمشة من التقطيع"),
                    (
                        "can_deliver_to_production_line",
                        "يمكنه تسليم الأقمشة لخطوط الإنتاج",
                    ),
                    ("can_view_fabric_receipts", "يمكنه عرض قائمة استلامات الأقمشة"),
                ],
                "verbose_name": "عنصر أمر تصنيع",
                "verbose_name_plural": "عناصر أوامر التصنيع",
            },
        ),
    ]
