# Generated by Django 6.0 on 2026-01-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0028_add_material_width_to_product"),
        ("manufacturing", "0028_alter_manufacturingorderitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingsettings",
            name="external_fabric_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="المستودع الذي سيتم تعيين أوامر تقطيع الأقمشة الخارجية إليه تلقائياً",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_fabric_settings",
                to="inventory.warehouse",
                verbose_name="مستودع الأقمشة الخارجية",
            ),
        ),
    ]
