# Generated by Django 5.1.15 on 2026-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0032_manufacturingorder_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabricreceiptitem",
            name="quantity_received",
            field=models.DecimalField(
                decimal_places=3, max_digits=12, verbose_name="الكمية المستلمة"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturingorderitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                help_text="يمكن إدخال قيم عشرية مثل 4.25 متر",
                max_digits=12,
                verbose_name="الكمية",
            ),
        ),
    ]
