# Generated by Django 5.1.15 on 2026-02-28 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0033_standardize_decimal_precision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingorder",
            name="previous_production_line",
            field=models.ForeignKey(
                blank=True,
                help_text="خط الإنتاج قبل آخر تغيير",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_manufacturing_orders",
                to="manufacturing.productionline",
                verbose_name="خط الإنتاج السابق",
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorder",
            name="production_line_changed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ تغيير خط الإنتاج"
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorder",
            name="production_line_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_line_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم تغيير خط الإنتاج بواسطة",
            ),
        ),
    ]
