# Generated by Django 5.1.15 on 2026-02-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0034_add_production_line_change_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionline",
            name="badge_color",
            field=models.CharField(
                choices=[
                    ("#0d6efd", "أزرق"),
                    ("#198754", "أخضر"),
                    ("#dc3545", "أحمر"),
                    ("#ffc107", "أصفر"),
                    ("#0dcaf0", "سماوي"),
                    ("#6f42c1", "بنفسجي"),
                    ("#fd7e14", "برتقالي"),
                    ("#d63384", "وردي"),
                    ("#20c997", "أخضر فاتح"),
                    ("#6c757d", "رمادي"),
                    ("#343a40", "أسود"),
                    ("#0b5394", "أزرق داكن"),
                ],
                default="#0d6efd",
                help_text="لون البادج الخاص بخط الإنتاج في الصفحات",
                max_length=7,
                verbose_name="لون البادج",
            ),
        ),
    ]
