# Generated by Django 5.1.15 on 2026-02-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0035_add_badge_color_to_production_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionline",
            name="badge_color",
            field=models.CharField(
                default="#0d6efd",
                help_text="لون البادج الخاص بخط الإنتاج في الصفحات",
                max_length=7,
                verbose_name="لون البادج",
            ),
        ),
    ]
