# Generated by Django 5.1.15 on 2026-02-28 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0058_branch_message_enhanced_customization"),
        ("manufacturing", "0036_alter_productionline_badge_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionLineOrderTypeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("installation", "تركيب"),
                            ("custom", "تفصيل"),
                            ("accessory", "اكسسوار"),
                            ("inspection", "معاينة"),
                        ],
                        max_length=20,
                        verbose_name="نوع الطلب",
                    ),
                ),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True,
                        help_text="الفروع المرتبطة بهذا النوع من الطلبات لهذا الخط",
                        related_name="order_type_configs",
                        to="accounts.branch",
                        verbose_name="الفروع",
                    ),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_type_configs",
                        to="manufacturing.productionline",
                        verbose_name="خط الإنتاج",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد نوع طلب",
                "verbose_name_plural": "إعدادات أنواع الطلبات",
                "ordering": ["order_type"],
                "unique_together": {("production_line", "order_type")},
            },
        ),
    ]
