# Generated by Django 5.1.15 on 2026-03-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0033_alter_manufacturingorder_deleted_by"),
        ("manufacturing", "0037_productionlineordertypeconfig"),
    ]

    operations = []
