# Generated by Django 4.2.21 on 2025-06-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20250505_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='interests',
            field=models.TextField(blank=True, help_text='اكتب اهتمامات العميل وتفضيلاته', verbose_name='اهتمامات العميل'),
        ),
    ]
