# Generated by Django 4.2.21 on 2025-06-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='اسم النوع')),
                ('description', models.TextField(blank=True, verbose_name='وصف النوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع العميل',
                'verbose_name_plural': 'أنواع العملاء',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='customer_type_code_idx'), models.Index(fields=['name'], name='customer_type_name_idx')],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customertype', verbose_name='نوع العميل المخصص'),
        ),
    ]
