# Generated by Django 4.2.21 on 2025-07-23 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_add_birth_date_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
            ),
        ),
    ]
