# Generated by Django 4.2.21 on 2025-06-03 16:36

from django.db import migrations


def add_default_customer_types(apps, schema_editor):
    CustomerType = apps.get_model('customers', 'CustomerType')
    
    # قائمة أنواع العملاء الافتراضية
    default_types = [
        {
            'code': 'retail',
            'name': 'أفراد',
            'description': 'عملاء التجزئة والأفراد'
        },
        {
            'code': 'wholesale',
            'name': 'جملة',
            'description': 'عملاء البيع بالجملة'
        },
        {
            'code': 'corporate',
            'name': 'شركات',
            'description': 'الشركات والمؤسسات'
        },
        {
            'code': 'vip',
            'name': 'VIP',
            'description': 'عملاء VIP وكبار العملاء'
        },
        {
            'code': 'distributor',
            'name': 'موزعين',
            'description': 'الموزعين والوكلاء'
        },
        {
            'code': 'government',
            'name': 'جهات حكومية',
            'description': 'المؤسسات والجهات الحكومية'
        }
    ]
    
    for type_data in default_types:
        CustomerType.objects.get_or_create(
            code=type_data['code'],
            defaults={
                'name': type_data['name'],
                'description': type_data['description']
            }
        )


def remove_default_customer_types(apps, schema_editor):
    CustomerType = apps.get_model('customers', 'CustomerType')
    CustomerType.objects.filter(code__in=['retail', 'wholesale', 'corporate', 'vip', 'distributor', 'government']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customertype_customer_customer_type_custom'),
    ]

    operations = [
        migrations.RunPython(add_default_customer_types, remove_default_customer_types),
    ]
