# Generated by Django 4.2.21 on 2025-07-23 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_alter_customer_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=True,
                verbose_name="تاريخ الإنشاء",
            ),
        ),
    ]
