# Generated by Django 4.2.21 on 2025-06-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_add_default_customer_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_type_custom',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'أفراد'), ('wholesale', 'جملة'), ('corporate', 'شركات')], default='retail', max_length=20, verbose_name='نوع العميل'),
        ),
    ]
