# Generated by Django 4.2.21 on 2025-07-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_companyinfo_header_logo_alter_companyinfo_logo"),
        ("customers", "0005_fix_created_at_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="accounts.branch",
                verbose_name="الفرع",
            ),
        ),
    ]
