# Generated by Django 4.2.21 on 2025-08-25 10:25

import customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_alter_customer_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="category",
            field=models.ForeignKey(
                default=customers.models.get_default_customer_category_id,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="customers",
                to="customers.customercategory",
                verbose_name="تصنيف العميل",
            ),
        ),
    ]
