# Generated by Django 4.2.21 on 2025-09-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_alter_customer_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="اسم نوع الخصم"
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="نسبة الخصم بالمئة (مثال: 10.50)",
                        max_digits=5,
                        verbose_name="نسبة الخصم",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف الخصم")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "نوع الخصم",
                "verbose_name_plural": "أنواع الخصومات",
                "ordering": ["-is_default", "percentage", "name"],
                "indexes": [
                    models.Index(fields=["is_active"], name="discount_type_active_idx"),
                    models.Index(fields=["percentage"], name="discount_type_perc_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="discount_type",
            field=models.ForeignKey(
                blank=True,
                help_text="نوع الخصم المطبق على هذا العميل",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="customers.discounttype",
                verbose_name="نوع الخصم",
            ),
        ),
        migrations.CreateModel(
            name="CustomerResponsible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="اسم المسؤول"
                    ),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="المنصب"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="المسؤول الرئيسي"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibles",
                        to="customers.customer",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "مسؤول العميل",
                "verbose_name_plural": "مسؤولي العملاء",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["customer", "is_primary"], name="cust_resp_primary_idx"
                    ),
                    models.Index(fields=["name"], name="cust_resp_name_idx"),
                ],
                "unique_together": {("customer", "order")},
            },
        ),
    ]
