# Generated by Django 4.2.21 on 2025-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_add_default_customer_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف الثاني'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[], default='retail', max_length=20, verbose_name='نوع العميل'),
        ),
    ]
