# Generated by Django 4.2.21 on 2025-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_add_phone2_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(default='retail', max_length=20, verbose_name='نوع العميل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, help_text='رقم هاتف إضافي اختياري', max_length=20, null=True, verbose_name='رقم الهاتف الثاني'),
        ),
    ]
