# Generated by Django 4.2.21 on 2025-09-10 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0016_delete_notification"),
        ("customers", "0008_discounttype_customer_discount_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_cross_branch",
                    models.BooleanField(default=False, verbose_name="وصول عبر فروع"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="معلومات المتصفح"),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الوصول"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="customers.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "customer_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_accesses",
                        to="accounts.branch",
                        verbose_name="فرع العميل",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "user_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_accesses",
                        to="accounts.branch",
                        verbose_name="فرع المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل وصول العميل",
                "verbose_name_plural": "سجلات وصول العملاء",
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "accessed_at"],
                        name="customer_access_log_idx",
                    ),
                    models.Index(
                        fields=["user", "accessed_at"], name="user_access_log_idx"
                    ),
                    models.Index(
                        fields=["is_cross_branch", "accessed_at"],
                        name="cross_branch_access_idx",
                    ),
                ],
            },
        ),
    ]
