# Generated by Django 4.2.21 on 2025-06-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customer_customer_type_alter_customer_phone2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'permissions': [('view_customer_reports', 'Can view customer reports'), ('export_customer_data', 'Can export customer data')], 'verbose_name': 'عميل', 'verbose_name_plural': 'سجل العملاء'},
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_branch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='cust_name_idx',
            old_name='customer_name_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='cust_status_idx',
            old_name='customer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='cust_type_idx',
            old_name='customer_type_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='cust_created_idx',
            old_name='customer_created_at_idx',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['code'], name='cust_code_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone', 'phone2'], name='cust_phones_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='cust_email_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['updated_at'], name='cust_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['branch', 'status', 'customer_type'], name='cust_br_st_type_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name', 'phone', 'email'], name='cust_search_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_by', 'branch'], name='cust_creator_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['name', 'phone'], name='cust_active_idx'),
        ),
    ]
