# Generated by Django 5.2.6 on 2025-09-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_fix_customeraccesslog_dependency"),
    ]

    operations = []
