# Generated by Django 5.2.6 on 2025-09-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_customeraccesslog"),
        ("customers", "0012_merge_20250920_1318"),
    ]

    operations = []
