# Generated by Django 6.0 on 2026-01-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0013_merge_0009_customeraccesslog_0012_merge_20250920_1318"),
        ("inventory", "0025_wholesale_pricing_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="customertype",
            name="badge_color",
            field=models.CharField(
                default="#6c757d",
                help_text="لون البادج بصيغة HEX (مثال: #FF5733)",
                max_length=20,
                verbose_name="لون البادج",
            ),
        ),
        migrations.AddField(
            model_name="customertype",
            name="badge_icon",
            field=models.CharField(
                blank=True,
                help_text="أيقونة Font Awesome (مثال: fas fa-crown)",
                max_length=50,
                verbose_name="أيقونة البادج",
            ),
        ),
        migrations.AddField(
            model_name="customertype",
            name="badge_style",
            field=models.CharField(
                choices=[
                    ("solid", "صلب"),
                    ("outline", "مخطط"),
                    ("gradient", "متدرج"),
                    ("glass", "زجاجي"),
                ],
                default="solid",
                max_length=20,
                verbose_name="شكل البادج",
            ),
        ),
        migrations.AddField(
            model_name="customertype",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="النسبة المئوية للخصم المطبق تلقائياً (للنوع: قطاعي مع خصم)",
                max_digits=5,
                verbose_name="نسبة الخصم الثابتة",
            ),
        ),
        migrations.AddField(
            model_name="customertype",
            name="discount_warehouses",
            field=models.ManyToManyField(
                blank=True,
                help_text="المستودعات التي يُطبق عليها الخصم تلقائياً - اتركها فارغة لتطبيق الخصم على جميع المستودعات",
                related_name="discount_customer_types",
                to="inventory.warehouse",
                verbose_name="مستودعات الخصم",
            ),
        ),
        migrations.AddField(
            model_name="customertype",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("retail", "قطاعي"),
                    ("wholesale", "جملة"),
                    ("discount", "قطاعي مع خصم"),
                ],
                default="retail",
                help_text="يحدد طريقة حساب السعر للعميل",
                max_length=20,
                verbose_name="نوع التسعير",
            ),
        ),
        migrations.AddIndex(
            model_name="customertype",
            index=models.Index(fields=["pricing_type"], name="customer_type_price_idx"),
        ),
    ]
