# Generated by Django 6.0 on 2026-01-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0014_wholesale_pricing_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="customertype",
            name="allowed_order_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="أنواع الطلبات المسموح بها لهذا النوع من العملاء - اتركها فارغة للسماح بجميع الأنواع",
                verbose_name="أنواع الطلبات المتاحة",
            ),
        ),
    ]
