# Generated by Django 6.0 on 2026-01-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0015_add_allowed_order_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("retail", "قطاعي"), ("wholesale", "جملة")],
                default="retail",
                max_length=20,
                verbose_name="نوع العميل",
            ),
        ),
    ]
