# Generated by Django 6.0 on 2026-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0016_alter_customer_customer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
    ]
