# Generated by Django 6.0 on 2026-01-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0018_customer_deleted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                db_index=True,
                default="retail",
                max_length=20,
                verbose_name="نوع العميل",
            ),
        ),
    ]
