# Generated by Django 5.1.5 on 2026-02-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0019_alter_customer_customer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="الحد الأقصى للمديونية المسموح بها (0 = غير محدود)",
                max_digits=15,
                verbose_name="الحد الائتماني",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_terms_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="عدد أيام الاستحقاق من تاريخ الفاتورة (0 = نقدي فوري)",
                verbose_name="مدة الدفع (أيام)",
            ),
        ),
    ]
