# Generated by Django 5.1.5 on 2026-02-12 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0020_add_credit_limit_payment_terms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="آخر تعديل بواسطة",
            ),
        ),
    ]
