# Generated by Django 5.1.5 on 2026-02-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_user_user_branch_active_idx_and_more"),
        ("customers", "0021_customer_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="accounts.branch",
                verbose_name="الفرع",
            ),
        ),
    ]
