# Generated by Django 5.1.15 on 2026-02-15 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0022_alter_customer_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                db_index=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[0-9\\s\\-]{7,20}$", "أدخل رقم هاتف صحيح"
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone2",
            field=models.CharField(
                blank=True,
                help_text="رقم هاتف إضافي اختياري",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[0-9\\s\\-]{7,20}$", "أدخل رقم هاتف صحيح"
                    )
                ],
                verbose_name="رقم الهاتف الثاني",
            ),
        ),
    ]
