# Generated by Django 6.0 on 2025-12-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudflareSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "worker_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="رابط Cloudflare Worker (مثال: https://qr.elkhawaga.uk)",
                        verbose_name="رابط Worker",
                    ),
                ),
                (
                    "sync_api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مفتاح سري للتحقق من طلبات المزامنة",
                        max_length=64,
                        verbose_name="مفتاح API للمزامنة",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="تفعيل أو إيقاف المزامنة التلقائية مع Cloudflare",
                        verbose_name="تفعيل المزامنة",
                    ),
                ),
                (
                    "auto_sync_on_save",
                    models.BooleanField(
                        default=True,
                        help_text="مزامنة المنتج تلقائياً عند حفظه",
                        verbose_name="مزامنة تلقائية عند الحفظ",
                    ),
                ),
                (
                    "last_full_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر مزامنة كاملة"
                    ),
                ),
                (
                    "products_synced",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المنتجات المُزامَنة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إعدادات Cloudflare",
                "verbose_name_plural": "إعدادات Cloudflare",
            },
        ),
    ]
