# Generated by Django 6.0 on 2025-12-24 08:23

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_default_cloudflare_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRDesignSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="شعار الشركة (يظهر في صفحات المنتجات والبنوك)",
                        null=True,
                        upload_to="qr_design/logos/",
                        verbose_name="الشعار / Logo",
                    ),
                ),
                (
                    "logo_text",
                    models.CharField(
                        default="الخواجة",
                        help_text="نص بديل عند عدم وجود صورة",
                        max_length=100,
                        verbose_name="نص الشعار",
                    ),
                ),
                (
                    "logo_text_en",
                    models.CharField(
                        blank=True,
                        default="Elkhawaga",
                        max_length=100,
                        verbose_name="نص الشعار (إنجليزي)",
                    ),
                ),
                (
                    "show_logo",
                    models.BooleanField(default=True, verbose_name="إظهار الشعار"),
                ),
                (
                    "color_primary",
                    colorfield.fields.ColorField(
                        default="#d4af37",
                        help_text="اللون الذهبي الرئيسي",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="اللون الأساسي",
                    ),
                ),
                (
                    "color_secondary",
                    colorfield.fields.ColorField(
                        default="#b8860b",
                        help_text="لون ذهبي داكن",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="اللون الثانوي",
                    ),
                ),
                (
                    "color_background",
                    colorfield.fields.ColorField(
                        default="#1a1a2e",
                        help_text="لون خلفية الصفحة",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="لون الخلفية",
                    ),
                ),
                (
                    "color_surface",
                    colorfield.fields.ColorField(
                        default="#16213e",
                        help_text="لون بطاقة المحتوى",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="لون السطح",
                    ),
                ),
                (
                    "color_text",
                    colorfield.fields.ColorField(
                        default="#ffffff",
                        help_text="لون النص الرئيسي",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="لون النص",
                    ),
                ),
                (
                    "color_text_secondary",
                    colorfield.fields.ColorField(
                        default="#c0c0c0",
                        help_text="لون النص الفرعي",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="لون النص الثانوي",
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        default="https://elkhawaga.com",
                        help_text='يظهر في زر "زيارة الموقع"',
                        verbose_name="رابط الموقع الرئيسي",
                    ),
                ),
                (
                    "show_website_button",
                    models.BooleanField(default=True, verbose_name="إظهار زر الموقع"),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="رابط صفحة فيسبوك",
                        verbose_name="فيسبوك",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="رابط حساب إنستجرام",
                        verbose_name="إنستجرام",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="رقم واتساب (مثال: 201234567890)",
                        max_length=20,
                        verbose_name="واتساب",
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="رابط حساب تويتر",
                        verbose_name="تويتر / X",
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="رابط قناة يوتيوب",
                        verbose_name="يوتيوب",
                    ),
                ),
                (
                    "tiktok_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="رابط حساب تيك توك",
                        verbose_name="تيك توك",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="رقم هاتف للاتصال",
                        max_length=20,
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="بريد إلكتروني للتواصل",
                        max_length=254,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "show_social_media",
                    models.BooleanField(
                        default=True,
                        help_text="إظهار/إخفاء جميع أزرار التواصل الاجتماعي",
                        verbose_name="إظهار أزرار التواصل",
                    ),
                ),
                (
                    "complaint_url",
                    models.URLField(
                        blank=True,
                        default="/complaints/create/",
                        help_text="رابط صفحة إنشاء شكوى",
                        verbose_name="رابط الشكوى",
                    ),
                ),
                (
                    "complaint_button_text",
                    models.CharField(
                        default="إنشاء شكوى",
                        help_text="النص الذي يظهر على زر الشكوى",
                        max_length=50,
                        verbose_name="نص زر الشكوى",
                    ),
                ),
                (
                    "complaint_button_text_en",
                    models.CharField(
                        blank=True,
                        default="Create Complaint",
                        max_length=50,
                        verbose_name="نص زر الشكوى (إنجليزي)",
                    ),
                ),
                (
                    "show_complaint_button",
                    models.BooleanField(default=True, verbose_name="إظهار زر الشكوى"),
                ),
                (
                    "layout_style",
                    models.CharField(
                        choices=[
                            ("modern", "حديث (Modern)"),
                            ("classic", "كلاسيكي (Classic)"),
                            ("minimal", "بسيط (Minimal)"),
                            ("elegant", "أنيق (Elegant)"),
                        ],
                        default="modern",
                        max_length=20,
                        verbose_name="نمط التخطيط",
                    ),
                ),
                (
                    "card_border_radius",
                    models.IntegerField(
                        default=15,
                        help_text="بالبكسل (0-50)",
                        verbose_name="انحناء زوايا البطاقة",
                    ),
                ),
                (
                    "enable_animations",
                    models.BooleanField(
                        default=True, verbose_name="تفعيل التأثيرات الحركية"
                    ),
                ),
                (
                    "enable_glassmorphism",
                    models.BooleanField(
                        default=True,
                        help_text="تأثير الزجاج الشفاف",
                        verbose_name="تفعيل تأثير Glassmorphism",
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="كود CSS إضافي للتخصيص المتقدم",
                        verbose_name="CSS مخصص",
                    ),
                ),
                (
                    "custom_js",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="كود JavaScript إضافي",
                        verbose_name="JavaScript مخصص",
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True,
                        default="© 2025 الخواجة - جميع الحقوق محفوظة",
                        max_length=200,
                        verbose_name="نص التذييل",
                    ),
                ),
                (
                    "show_footer",
                    models.BooleanField(default=True, verbose_name="إظهار التذييل"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر مزامنة"),
                ),
                (
                    "cloudflare_synced",
                    models.BooleanField(
                        default=False, verbose_name="تمت المزامنة مع Cloudflare"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إعدادات تصميم QR",
                "verbose_name_plural": "إعدادات تصميم QR",
                "db_table": "public_qr_design_settings",
            },
        ),
    ]
