# Generated by Django 6.0 on 2025-12-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0005_add_advanced_design_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrdesignsettings",
            name="enable_glassmorphism",
            field=models.BooleanField(
                default=True,
                help_text="تأثير الزجاج الشفاف - يطبق لون البطاقة مع شفافية 80%",
                verbose_name="تفعيل تأثير Glassmorphism",
            ),
        ),
        migrations.AlterField(
            model_name="qrdesignsettings",
            name="enable_gradient_bg",
            field=models.BooleanField(
                default=True,
                help_text="خلفية بتدرج جميل بدلاً من لون صامت",
                verbose_name="تفعيل تدرج الخلفية",
            ),
        ),
        migrations.AlterField(
            model_name="qrdesignsettings",
            name="enable_hover_effects",
            field=models.BooleanField(
                default=True,
                help_text="حركات عند التمرير على الأزرار",
                verbose_name="تفعيل تأثيرات التمرير",
            ),
        ),
        migrations.AlterField(
            model_name="qrdesignsettings",
            name="font_family",
            field=models.CharField(
                default="Cairo",
                help_text="مثل: Cairo, Tajawal, Almarai, Rubik",
                max_length=100,
                verbose_name="نوع الخط",
            ),
        ),
    ]
