# Generated by Django 6.0 on 2025-12-24 13:24

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0006_alter_qrdesignsettings_enable_glassmorphism_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrdesignsettings",
            name="background_image",
            field=models.ImageField(
                blank=True,
                help_text="صورة خلفية للصفحة (اختياري - يظهر خلف اللون)",
                null=True,
                upload_to="qr_design/backgrounds/",
                verbose_name="صورة الخلفية",
            ),
        ),
        migrations.AddField(
            model_name="qrdesignsettings",
            name="color_badge",
            field=colorfield.fields.ColorField(
                default="#d4af37",
                help_text="لون خلفية البادجات (الفئة، الوحدة، الكود)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="لون البادجات",
            ),
        ),
        migrations.AddField(
            model_name="qrdesignsettings",
            name="color_badge_text",
            field=colorfield.fields.ColorField(
                default="#1a1a2e",
                help_text="لون النص داخل البادجات",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="لون نص البادجات",
            ),
        ),
        migrations.AddField(
            model_name="qrdesignsettings",
            name="color_button",
            field=colorfield.fields.ColorField(
                default="#d4af37",
                help_text="لون خلفية الأزرار",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="لون الأزرار",
            ),
        ),
        migrations.AddField(
            model_name="qrdesignsettings",
            name="color_button_text",
            field=colorfield.fields.ColorField(
                default="#1a1a2e",
                help_text="لون النص داخل الأزرار",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="لون نص الأزرار",
            ),
        ),
        migrations.AddField(
            model_name="qrdesignsettings",
            name="color_card",
            field=colorfield.fields.ColorField(
                default="#16213e",
                help_text="لون خلفية البطاقة الرئيسية",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="لون البطاقة",
            ),
        ),
        migrations.AddField(
            model_name="qrdesignsettings",
            name="color_price",
            field=colorfield.fields.ColorField(
                default="#d4af37",
                help_text="لون رقم السعر (يدعم تدرج من primary إلى price)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="لون السعر",
            ),
        ),
    ]
