# Generated by Django 6.0 on 2025-12-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0007_qrdesignsettings_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrdesignsettings",
            name="logo_size",
            field=models.IntegerField(
                default=200,
                help_text="الحجم الأقصى للشعار بالبكسل (50-400)",
                verbose_name="حجم الشعار",
            ),
        ),
    ]
