# Generated by Django 6.0 on 2025-12-27 18:26

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0008_qrdesignsettings_logo_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrdesignsettings",
            name="color_label",
            field=colorfield.fields.ColorField(
                default="#888888",
                help_text="لون العناوين والتسميات (النوع، الوحدة، سعر المنتج الأساسي)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="لون العناوين",
            ),
        ),
        migrations.AddField(
            model_name="qrdesignsettings",
            name="color_product_name",
            field=colorfield.fields.ColorField(
                default="#d4af37",
                help_text="لون اسم المنتج الرئيسي",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="لون اسم المنتج",
            ),
        ),
    ]
