# Generated by Django 4.2.21 on 2025-09-09 11:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaintsla",
            name="critical_threshold",
            field=models.PositiveIntegerField(
                default=90,
                help_text="النسبة المئوية من وقت الحل للحالة الحرجة",
                validators=[
                    django.core.validators.MinValueValidator(80),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="نسبة الحرج (%)",
            ),
        ),
        migrations.AddField(
            model_name="complaintsla",
            name="warning_threshold",
            field=models.PositiveIntegerField(
                default=70,
                help_text="النسبة المئوية من وقت الحل للتحذير",
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="نسبة التحذير (%)",
            ),
        ),
        migrations.AddField(
            model_name="complainttype",
            name="business_hours_end",
            field=models.TimeField(default="17:00", verbose_name="نهاية ساعات العمل"),
        ),
        migrations.AddField(
            model_name="complainttype",
            name="business_hours_start",
            field=models.TimeField(default="09:00", verbose_name="بداية ساعات العمل"),
        ),
        migrations.AddField(
            model_name="complainttype",
            name="working_days",
            field=models.CharField(
                default="1,2,3,4,5",
                help_text="أرقام أيام العمل (1=الأحد، 7=السبت) مفصولة بفواصل",
                max_length=20,
                verbose_name="أيام العمل",
            ),
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="file",
            field=models.FileField(
                help_text="الحد الأقصى للحجم: 10 ميجابايت. الصيغ المسموحة: PDF, DOC, DOCX, JPG, PNG, XLS, XLSX",
                upload_to="complaints/attachments/%Y/%m/%d/",
                verbose_name="الملف",
            ),
        ),
        migrations.AlterField(
            model_name="complaintsla",
            name="escalation_time_hours",
            field=models.PositiveIntegerField(
                default=48,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(168),
                ],
                verbose_name="وقت التصعيد (ساعات)",
            ),
        ),
        migrations.AlterField(
            model_name="complaintsla",
            name="resolution_time_hours",
            field=models.PositiveIntegerField(
                default=72,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(720),
                ],
                verbose_name="وقت الحل (ساعات)",
            ),
        ),
        migrations.AlterField(
            model_name="complaintsla",
            name="response_time_hours",
            field=models.PositiveIntegerField(
                default=4,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="وقت الاستجابة (ساعات)",
            ),
        ),
        migrations.AlterField(
            model_name="complainttype",
            name="default_deadline_hours",
            field=models.PositiveIntegerField(
                default=72,
                help_text="المهلة الزمنية المحددة تلقائياً لحل الشكوى",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(720),
                ],
                verbose_name="المهلة الافتراضية (بالساعات)",
            ),
        ),
        migrations.AlterField(
            model_name="complaintupdate",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(5000)],
                verbose_name="الوصف",
            ),
        ),
        migrations.CreateModel(
            name="ComplaintTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم النموذج"
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="يمكن استخدام {customer} و {order} كمتغيرات",
                        max_length=200,
                        verbose_name="قالب العنوان",
                    ),
                ),
                (
                    "description_template",
                    models.TextField(
                        help_text="يمكن استخدام {customer}، {order}، {date} كمتغيرات",
                        verbose_name="قالب الوصف",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("medium", "متوسطة"),
                            ("high", "عالية"),
                            ("urgent", "عاجلة"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "default_deadline_hours",
                    models.PositiveIntegerField(
                        default=72, verbose_name="المهلة الافتراضية (بالساعات)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "complaint_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="complaints.complainttype",
                        verbose_name="نوع الشكوى",
                    ),
                ),
            ],
            options={
                "verbose_name": "نموذج شكوى",
                "verbose_name_plural": "نماذج الشكاوى",
                "ordering": ["complaint_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_complaint", "شكوى جديدة"),
                            ("status_change", "تغيير الحالة"),
                            ("assignment", "تعيين مسؤول"),
                            ("comment", "تعليق جديد"),
                            ("deadline", "اقتراب الموعد النهائي"),
                            ("overdue", "تجاوز الموعد النهائي"),
                            ("escalation", "تصعيد"),
                            ("resolution", "حل الشكوى"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الإشعار"),
                ),
                ("message", models.TextField(verbose_name="نص الإشعار")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="تمت القراءة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القراءة"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="الرابط المرتبط بالإشعار",
                        max_length=255,
                        verbose_name="رابط الإشعار",
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="complaints.complaint",
                        verbose_name="الشكوى",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaint_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="complaints__recipie_35fb2f_idx",
                    ),
                    models.Index(
                        fields=["complaint", "-created_at"],
                        name="complaints__complai_32ee3d_idx",
                    ),
                ],
            },
        ),
    ]
