# Generated by Django 4.2.21 on 2025-09-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_complaintsla_critical_threshold_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolutionMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم طريقة الحل"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف طريقة الحل"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "طريقة حل",
                "verbose_name_plural": "طرق الحل",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolution_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="complaints.resolutionmethod",
                verbose_name="طريقة الحل",
            ),
        ),
    ]
