# Generated by Django 4.2.21 on 2025-09-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_resolutionmethod_complaint_resolution_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaintupdate",
            name="resolution_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="complaints.resolutionmethod",
                verbose_name="طريقة الحل",
            ),
        ),
    ]
