# Generated by Django 4.2.21 on 2025-09-09 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0019_yearfilterexemption"),
        ("complaints", "0005_add_default_resolution_methods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaintupdate",
            name="update_type",
            field=models.CharField(
                choices=[
                    ("status_change", "تغيير الحالة"),
                    ("assignment", "تعيين مسؤول"),
                    ("comment", "تعليق"),
                    ("note", "ملاحظة"),
                    ("escalation", "تصعيد"),
                    ("resolution", "حل"),
                    ("customer_response", "رد العميل"),
                    ("internal_note", "ملاحظة داخلية"),
                ],
                max_length=20,
                verbose_name="نوع التحديث",
            ),
        ),
        migrations.CreateModel(
            name="ComplaintUserPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_be_assigned_complaints",
                    models.BooleanField(
                        default=False,
                        help_text="هل يمكن إسناد الشكاوى لهذا المستخدم؟",
                        verbose_name="يمكن إسناد الشكاوى إليه",
                    ),
                ),
                (
                    "can_receive_escalations",
                    models.BooleanField(
                        default=False,
                        help_text="هل يمكن تصعيد الشكاوى لهذا المستخدم؟",
                        verbose_name="يمكن تصعيد الشكاوى إليه",
                    ),
                ),
                (
                    "can_view_all_complaints",
                    models.BooleanField(
                        default=False,
                        help_text="هل يمكن لهذا المستخدم عرض جميع الشكاوى؟",
                        verbose_name="يمكن عرض جميع الشكاوى",
                    ),
                ),
                (
                    "can_edit_all_complaints",
                    models.BooleanField(
                        default=False,
                        help_text="هل يمكن لهذا المستخدم تعديل جميع الشكاوى؟",
                        verbose_name="يمكن تعديل جميع الشكاوى",
                    ),
                ),
                (
                    "max_assigned_complaints",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="الحد الأقصى لعدد الشكاوى التي يمكن إسنادها لهذا المستخدم (0 = بلا حدود)",
                        verbose_name="الحد الأقصى للشكاوى المسندة",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل هذه الصلاحيات نشطة؟",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "complaint_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="أنواع الشكاوى التي يمكن لهذا المستخدم التعامل معها",
                        to="complaints.complainttype",
                        verbose_name="أنواع الشكاوى المخولة",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="الأقسام التي يمكن لهذا المستخدم التعامل مع شكاواها",
                        to="accounts.department",
                        verbose_name="الأقسام المخولة",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaint_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "صلاحيات مستخدم الشكاوى",
                "verbose_name_plural": "صلاحيات مستخدمي الشكاوى",
                "ordering": ["user__username"],
            },
        ),
    ]
