# Generated by Django 4.2.21 on 2025-09-09 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("complaints", "0006_add_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="complainttype",
            name="responsible_staff",
            field=models.ManyToManyField(
                blank=True,
                help_text="الموظفون المسؤولون عن هذا النوع من الشكاوى",
                related_name="responsible_complaint_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الموظفون المسؤولون",
            ),
        ),
    ]
