# Generated by Django 4.2.21 on 2025-09-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0007_add_responsible_staff_to_complaint_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "جديدة"),
                    ("in_progress", "قيد الحل"),
                    ("resolved", "محلولة"),
                    ("pending_evaluation", "بحاجة تقييم"),
                    ("closed", "مغلقة"),
                    ("overdue", "متأخرة"),
                    ("escalated", "مصعدة"),
                ],
                default="new",
                max_length=20,
                verbose_name="حالة الشكوى",
            ),
        ),
        migrations.CreateModel(
            name="ComplaintEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "غير راضي جداً"),
                            (2, "غير راضي"),
                            (3, "محايد"),
                            (4, "راضي"),
                            (5, "راضي جداً"),
                        ],
                        help_text="تقييم عام لتجربة حل الشكوى",
                        verbose_name="التقييم العام",
                    ),
                ),
                (
                    "response_time_rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "بطيء جداً"),
                            (2, "بطيء"),
                            (3, "مقبول"),
                            (4, "سريع"),
                            (5, "ممتاز"),
                        ],
                        verbose_name="تقييم سرعة الاستجابة",
                    ),
                ),
                (
                    "solution_quality_rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "غير مناسب"),
                            (2, "ضعيف"),
                            (3, "مقبول"),
                            (4, "جيد"),
                            (5, "ممتاز"),
                        ],
                        verbose_name="تقييم جودة الحل",
                    ),
                ),
                (
                    "staff_behavior_rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "غير راضي جداً"),
                            (2, "غير راضي"),
                            (3, "محايد"),
                            (4, "راضي"),
                            (5, "راضي جداً"),
                        ],
                        verbose_name="تقييم تعامل الموظفين",
                    ),
                ),
                (
                    "positive_feedback",
                    models.TextField(
                        blank=True,
                        help_text="اذكر النقاط الإيجابية",
                        verbose_name="ما أعجبك في الخدمة؟",
                    ),
                ),
                (
                    "negative_feedback",
                    models.TextField(
                        blank=True,
                        help_text="اذكر النقاط التي تحتاج تحسين",
                        verbose_name="ما لم يعجبك؟",
                    ),
                ),
                (
                    "suggestions",
                    models.TextField(
                        blank=True,
                        help_text="كيف يمكننا تحسين خدمتنا؟",
                        verbose_name="اقتراحات للتحسين",
                    ),
                ),
                (
                    "would_recommend",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="هل تنصح بخدماتنا؟"
                    ),
                ),
                (
                    "evaluation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التقييم"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "complaint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="complaints.complaint",
                        verbose_name="الشكوى",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم شكوى",
                "verbose_name_plural": "تقييمات الشكاوى",
                "ordering": ["-evaluation_date"],
            },
        ),
    ]
