# Generated by Django 4.2.21 on 2025-09-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0008_alter_complaint_status_complaintevaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaintuserpermissions",
            name="can_assign_complaints",
            field=models.BooleanField(
                default=False,
                help_text="هل يمكن لهذا المستخدم إسناد الشكاوى للمستخدمين الآخرين؟",
                verbose_name="يمكن إسناد الشكاوى للآخرين",
            ),
        ),
        migrations.AddField(
            model_name="complaintuserpermissions",
            name="can_change_complaint_status",
            field=models.BooleanField(
                default=True,
                help_text="هل يمكن لهذا المستخدم تغيير حالة الشكاوى المسندة إليه؟",
                verbose_name="يمكن تغيير حالة الشكوى",
            ),
        ),
        migrations.AddField(
            model_name="complaintuserpermissions",
            name="can_close_complaints",
            field=models.BooleanField(
                default=False,
                help_text="هل يمكن لهذا المستخدم إغلاق الشكاوى نهائياً؟",
                verbose_name="يمكن إغلاق الشكاوى",
            ),
        ),
        migrations.AddField(
            model_name="complaintuserpermissions",
            name="can_delete_complaints",
            field=models.BooleanField(
                default=False,
                help_text="هل يمكن لهذا المستخدم حذف الشكاوى؟",
                verbose_name="يمكن حذف الشكاوى",
            ),
        ),

        migrations.AddField(
            model_name="complaintuserpermissions",
            name="can_resolve_complaints",
            field=models.BooleanField(
                default=True,
                help_text="هل يمكن لهذا المستخدم حل الشكاوى؟",
                verbose_name="يمكن حل الشكاوى",
            ),
        ),
    ]
