# Generated by Django 4.2.21 on 2025-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0009_add_new_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaintuserpermissions",
            name="can_escalate_complaints",
            field=models.BooleanField(
                default=False,
                help_text="هل يمكن لهذا المستخدم تصعيد الشكاوى للآخرين؟",
                verbose_name="يمكن تصعيد الشكاوى",
            ),
        ),
    ]
