# Generated by Django 4.2.21 on 2025-09-13 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("complaints", "0010_complaintuserpermissions_can_escalate_complaints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="إسناد إلى",
            ),
        ),
    ]
