# Generated by Django 5.2.6 on 2025-12-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0012_add_comprehensive_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_branch_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_order_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_resolved_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_closed_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_dept_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_creator_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_updated_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_cust_sts_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_sts_pri_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_asn_sts_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_br_sts_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_type_sts_idx",
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaint_ord_sts_idx",
        ),
        migrations.RemoveIndex(
            model_name="complainttype",
            name="comptype_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="complainttype",
            name="comptype_order_idx",
        ),
        migrations.RemoveIndex(
            model_name="complainttype",
            name="comptype_dept_idx",
        ),
    ]
