# Generated by Django 5.1.5 on 2026-02-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0013_remove_complaint_complaint_type_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaintupdate",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="عنوان IP"
            ),
        ),
    ]
