# Generated by Django 5.1.5 on 2026-02-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0014_audit_improvements_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "يدوي"),
                    ("auto", "تلقائي"),
                    ("customer", "العميل"),
                ],
                default="manual",
                help_text="كيف تم إنشاء الشكوى (يدوياً أو تلقائياً من النظام)",
                max_length=10,
                verbose_name="مصدر الشكوى",
            ),
        ),
    ]
