# Generated by Django 6.0 on 2025-12-31 10:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0013_merge_0009_customeraccesslog_0012_merge_20250920_1318"),
        ("inspections", "0010_remove_in_progress_status"),
        ("installations", "0015_remove_driver_driver_active_idx_and_more"),
        ("orders", "0079_draftorderitem_original_item_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppMessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم القالب")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("ORDER_CREATED", "إنشاء طلب"),
                            ("ORDER_WITH_CONTRACT", "طلب مع عقد"),
                            ("ORDER_WITH_INVOICE", "طلب مع فاتورة"),
                            ("INSTALLATION_SCHEDULED", "جدولة تركيب"),
                            ("INSTALLATION_COMPLETED", "اكتمال تركيب"),
                            ("INSPECTION_CREATED", "إنشاء معاينة"),
                            ("INSPECTION_SCHEDULED", "جدولة معاينة"),
                            ("CUSTOM", "رسالة مخصصة"),
                        ],
                        max_length=50,
                        verbose_name="نوع الرسالة",
                    ),
                ),
                (
                    "template_text",
                    models.TextField(
                        help_text="استخدم {customer_name}, {order_number}, إلخ للمتغيرات",
                        verbose_name="نص القالب",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                (
                    "send_contract",
                    models.BooleanField(default=False, verbose_name="إرسال العقد"),
                ),
                (
                    "send_invoice",
                    models.BooleanField(default=False, verbose_name="إرسال الفاتورة"),
                ),
                (
                    "order_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="أنواع الطلبات التي يطبق عليها هذا القالب",
                        verbose_name="أنواع الطلبات",
                    ),
                ),
                (
                    "language",
                    models.CharField(default="ar", max_length=5, verbose_name="اللغة"),
                ),
                (
                    "delay_minutes",
                    models.IntegerField(
                        default=0, verbose_name="تأخير الإرسال (دقائق)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "قالب رسالة",
                "verbose_name_plural": "قوالب الرسائل",
                "ordering": ["message_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_provider",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("meta", "Meta Business"),
                            ("custom", "Custom API"),
                        ],
                        default="twilio",
                        max_length=20,
                        verbose_name="مزود API",
                    ),
                ),
                (
                    "account_sid",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Account SID"
                    ),
                ),
                (
                    "auth_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Auth Token"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")
                        ],
                        verbose_name="رقم WhatsApp",
                    ),
                ),
                (
                    "business_account_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Business Account ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                (
                    "test_mode",
                    models.BooleanField(default=False, verbose_name="وضع الاختبار"),
                ),
                (
                    "retry_failed_messages",
                    models.BooleanField(
                        default=True, verbose_name="إعادة محاولة الرسائل الفاشلة"
                    ),
                ),
                (
                    "max_retry_attempts",
                    models.IntegerField(default=3, verbose_name="عدد محاولات الإعادة"),
                ),
                (
                    "default_language",
                    models.CharField(
                        default="ar", max_length=5, verbose_name="اللغة الافتراضية"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "إعدادات WhatsApp",
                "verbose_name_plural": "إعدادات WhatsApp",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppNotificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ORDER_CREATED", "إنشاء طلب"),
                            ("ORDER_UPDATED", "تحديث طلب"),
                            ("INSTALLATION_SCHEDULED", "جدولة تركيب"),
                            ("INSTALLATION_COMPLETED", "اكتمال تركيب"),
                            ("INSPECTION_CREATED", "إنشاء معاينة"),
                            ("INSPECTION_SCHEDULED", "جدولة معاينة"),
                            ("PAYMENT_REMINDER", "تذكير بالدفع"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="نوع الحدث",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="مفعل")),
                (
                    "delay_minutes",
                    models.IntegerField(
                        default=0, verbose_name="تأخير الإرسال (دقائق)"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="شروط إضافية لتفعيل القاعدة",
                        verbose_name="الشروط",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whatsapp.whatsappmessagetemplate",
                        verbose_name="القالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعدة إشعار",
                "verbose_name_plural": "قواعد الإشعارات",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(max_length=50, verbose_name="نوع الرسالة"),
                ),
                ("message_text", models.TextField(verbose_name="نص الرسالة")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="رقم الهاتف"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الانتظار"),
                            ("SENT", "تم الإرسال"),
                            ("DELIVERED", "تم التسليم"),
                            ("READ", "تمت القراءة"),
                            ("FAILED", "فشل"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Message SID من Twilio",
                        max_length=255,
                        verbose_name="معرف خارجي",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(blank=True, default=dict, verbose_name="المرفقات"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="عدد المحاولات"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإرسال"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت التسليم"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت القراءة"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_messages",
                        to="customers.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages",
                        to="inspections.inspection",
                        verbose_name="المعاينة",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages",
                        to="installations.installationschedule",
                        verbose_name="التركيب",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "template_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whatsapp.whatsappmessagetemplate",
                        verbose_name="القالب المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة WhatsApp",
                "verbose_name_plural": "رسائل WhatsApp",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="whatsapp_wh_created_73568f_idx"
                    ),
                    models.Index(
                        fields=["status"], name="whatsapp_wh_status_55e250_idx"
                    ),
                    models.Index(
                        fields=["customer", "-created_at"],
                        name="whatsapp_wh_custome_d0d376_idx",
                    ),
                ],
            },
        ),
    ]
