# Generated by Django 6.0 on 2025-12-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappsettings",
            name="access_token",
            field=models.CharField(
                blank=True,
                help_text="مفتاح الوصول لـ Meta Cloud API",
                max_length=500,
                verbose_name="Access Token",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsettings",
            name="phone_number_id",
            field=models.CharField(
                blank=True,
                help_text="معرف الرقم في Meta Cloud API",
                max_length=255,
                verbose_name="Phone Number ID",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappsettings",
            name="api_provider",
            field=models.CharField(
                choices=[("meta", "Meta Cloud API")],
                default="meta",
                max_length=20,
                verbose_name="مزود API",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappsettings",
            name="business_account_id",
            field=models.CharField(
                blank=True,
                help_text="معرف حساب WhatsApp Business",
                max_length=255,
                verbose_name="Business Account ID",
            ),
        ),
    ]
