# Generated by Django 6.0 on 2026-01-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0002_whatsappsettings_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappsettings",
            name="enable_welcome_messages",
            field=models.BooleanField(
                default=False,
                help_text="إرسال رسالة ترحيبية تلقائياً عند إنشاء عميل جديد",
                verbose_name="تفعيل الرسائل الترحيبية",
            ),
        ),
    ]
