# Generated by Django 6.0 on 2026-01-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0004_create_welcome_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappsettings",
            name="use_template",
            field=models.BooleanField(
                default=False,
                help_text="إرسال قالب hello_world بدلاً من رسائل نصية (للتأكد من الوصول)",
                verbose_name="استخدام قالب hello_world",
            ),
        ),
    ]
