# Generated by Django 6.0 on 2026-01-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0005_whatsappsettings_use_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappsettings",
            name="template_name",
            field=models.CharField(
                default="hello_world",
                help_text="اسم القالب المعتمد في Meta (مثل: hello_world, order_confirmation)",
                max_length=100,
                verbose_name="اسم القالب",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappsettings",
            name="use_template",
            field=models.BooleanField(
                default=False,
                help_text="إرسال قالب Meta معتمد بدلاً من رسائل نصية (للتأكد من الوصول)",
                verbose_name="استخدام قالب Meta معتمد",
            ),
        ),
    ]
