# Generated by Django 6.0 on 2026-01-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0006_whatsappsettings_template_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessagetemplate",
            name="meta_template_name",
            field=models.CharField(
                blank=True,
                help_text="اسم القالب المعتمد في Meta WhatsApp (مثل: hello_world, order_confirmation). اتركه فارغاً لاستخدام رسائل نصية",
                max_length=100,
                verbose_name="اسم القالب في Meta",
            ),
        ),
    ]
