# Generated by Django 6.0 on 2026-01-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0007_whatsappmessagetemplate_meta_template_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="template_name",
        ),
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="meta_template_name",
            field=models.CharField(
                blank=True,
                help_text="اسم القالب المعتمد في Meta (مثل: order_confirmation, hello_world)",
                max_length=100,
                verbose_name="اسم القالب في Meta",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappsettings",
            name="use_template",
            field=models.BooleanField(
                default=False,
                help_text="إرسال قالب hello_world بدلاً من رسائل نصية (للتأكد من الوصول)",
                verbose_name="استخدام قالب hello_world",
            ),
        ),
    ]
