# Generated by Django 6.0 on 2026-01-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0005_add_header_footer_fields"),
        ("whatsapp", "0008_remove_whatsappsettings_template_name_and_more"),
    ]

    operations = []
