# Generated by Django 6.0 on 2026-01-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0009_merge_20260103_1126"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="footer",
        ),
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="header",
        ),
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="template_text",
            field=models.TextField(
                help_text="استخدم {customer_name}, {order_number}, إلخ للمتغيرات",
                verbose_name="نص القالب",
            ),
        ),
    ]
