# Generated by Django 6.0 on 2026-01-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0010_remove_whatsappmessagetemplate_footer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessagetemplate",
            name="footer",
            field=models.CharField(
                blank=True,
                help_text="نص التذييل (اختياري، حد أقصى 60 حرف)",
                max_length=60,
                null=True,
                verbose_name="التذييل (Footer)",
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessagetemplate",
            name="header",
            field=models.CharField(
                blank=True,
                help_text="نص العنوان (اختياري، حد أقصى 60 حرف)",
                max_length=60,
                null=True,
                verbose_name="العنوان (Header)",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="template_text",
            field=models.TextField(
                help_text="استخدم {{customer_name}}, {{order_number}}, إلخ للمتغيرات (أقواس مزدوجة)",
                verbose_name="نص القالب",
            ),
        ),
    ]
