# Generated by Django 6.0 on 2026-01-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0012_load_default_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappsettings",
            name="enable_contract",
            field=models.BooleanField(
                default=False,
                help_text="إرسال العقد عبر WhatsApp",
                verbose_name="تفعيل قالب العقد",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsettings",
            name="enable_inspection_completed",
            field=models.BooleanField(
                default=False,
                help_text="إرسال رسالة عند اكتمال المعاينة",
                verbose_name="تفعيل قالب اكتمال المعاينة",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsettings",
            name="enable_inspection_scheduled",
            field=models.BooleanField(
                default=False,
                help_text="إرسال رسالة عند جدولة معاينة",
                verbose_name="تفعيل قالب جدولة المعاينة",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsettings",
            name="enable_installation_completed",
            field=models.BooleanField(
                default=False,
                help_text="إرسال رسالة عند اكتمال التركيب",
                verbose_name="تفعيل قالب اكتمال التركيب",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsettings",
            name="enable_installation_scheduled",
            field=models.BooleanField(
                default=False,
                help_text="إرسال رسالة عند جدولة التركيب",
                verbose_name="تفعيل قالب جدولة التركيب",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsettings",
            name="enable_invoice",
            field=models.BooleanField(
                default=False,
                help_text="إرسال الفاتورة عبر WhatsApp",
                verbose_name="تفعيل قالب الفاتورة",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsettings",
            name="enable_order_created",
            field=models.BooleanField(
                default=False,
                help_text="إرسال رسالة عند إنشاء طلب جديد",
                verbose_name="تفعيل قالب إنشاء الطلب",
            ),
        ),
    ]
