# Generated by Django 6.0 on 2026-01-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0013_add_template_enable_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppEventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="الكود الداخلي (مثل: ORDER_CREATED)",
                        max_length=50,
                        unique=True,
                        verbose_name="كود الحدث",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="الاسم الذي يظهر في لوحة التحكم",
                        max_length=100,
                        verbose_name="اسم الحدث",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف الحدث")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "نوع حدث",
                "verbose_name_plural": "أنواع الأحداث",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="whatsappnotificationrule",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("ORDER_CREATED", "إنشاء طلب"),
                    ("ORDER_UPDATED", "تحديث طلب"),
                    ("INSTALLATION_SCHEDULED", "جدولة تركيب"),
                    ("INSTALLATION_COMPLETED", "اكتمال تركيب"),
                    ("INSPECTION_CREATED", "إنشاء معاينة"),
                    ("INSPECTION_SCHEDULED", "جدولة معاينة"),
                    ("PAYMENT_REMINDER", "تذكير بالدفع"),
                    ("CUSTOMER_WELCOME", "ترحيب بالعميل"),
                ],
                max_length=50,
                unique=True,
                verbose_name="نوع الحدث",
            ),
        ),
    ]
