# Generated by Django 6.0 on 2026-01-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0014_add_event_type_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="template_text",
            field=models.TextField(
                blank=True,
                help_text="اختياري - المحتوى الفعلي يُدار من Meta Template Manager",
                verbose_name="نص القالب (للمرجع فقط)",
            ),
        ),
    ]
