# Generated by Django 6.0 on 2026-01-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0015_make_template_text_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="header",
        ),
        migrations.AddField(
            model_name="whatsappmessagetemplate",
            name="header_media_url",
            field=models.URLField(
                blank=True,
                help_text="رابط الصورة أو الفيديو أو الملف (يجب أن يكون رابط مباشر)",
                null=True,
                verbose_name="رابط الوسائط",
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessagetemplate",
            name="header_text",
            field=models.CharField(
                blank=True,
                help_text="يستخدم فقط إذا كان نوع العنوان 'نص'",
                max_length=60,
                null=True,
                verbose_name="نص العنوان",
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessagetemplate",
            name="header_type",
            field=models.CharField(
                choices=[
                    ("NONE", "لا يوجد"),
                    ("TEXT", "نص"),
                    ("IMAGE", "صورة"),
                    ("VIDEO", "فيديو"),
                    ("DOCUMENT", "ملف"),
                ],
                default="NONE",
                max_length=10,
                verbose_name="نوع العنوان",
            ),
        ),
    ]
