# Generated by Django 6.0 on 2026-01-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0016_add_header_media_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessagetemplate",
            name="variable_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='أسماء المتغيرات بالترتيب كما في Meta (مثال: ["customer_name", "order_number", "order_date"])',
                verbose_name="أسماء المتغيرات",
            ),
        ),
    ]
