# Generated by Django 6.0 on 2026-01-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0017_add_variable_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="header_media_url",
            field=models.TextField(
                blank=True,
                help_text="رابط Meta header_handle أو رابط الصورة المباشر",
                null=True,
                verbose_name="رابط الوسائط / Header Handle",
            ),
        ),
    ]
