# Generated by Django 6.0 on 2026-01-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0018_increase_header_url_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappsettings",
            name="header_image_url",
            field=models.URLField(
                blank=True,
                help_text="رابط URL عام لصورة اللوغو (يجب أن يكون متاحاً على الإنترنت)",
                max_length=500,
                verbose_name="رابط صورة الهيدر",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsettings",
            name="header_media_id",
            field=models.CharField(
                blank=True,
                help_text="معرف الصورة المرفوعة على WhatsApp (يُملأ تلقائياً بعد الرفع)",
                max_length=255,
                verbose_name="Media ID للصورة",
            ),
        ),
    ]
