# Generated by Django 6.0 on 2026-01-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0019_add_header_image_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="header_image_url",
        ),
        migrations.AddField(
            model_name="whatsappsettings",
            name="header_image",
            field=models.ImageField(
                blank=True,
                help_text="صورة اللوغو التي تظهر في رأس الرسائل (PNG أو JPG)",
                null=True,
                upload_to="whatsapp/header/",
                verbose_name="صورة الهيدر",
            ),
        ),
    ]
