# Generated by Django 6.0 on 2026-01-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0020_change_header_to_image_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="whatsappmessagetemplate",
            options={
                "ordering": ["message_type"],
                "verbose_name": "قالب رسالة",
                "verbose_name_plural": "قوالب الرسائل",
            },
        ),
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="delay_minutes",
        ),
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="footer",
        ),
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="header_media_url",
        ),
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="header_text",
        ),
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="header_type",
        ),
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="order_types",
        ),
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="send_contract",
        ),
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="send_invoice",
        ),
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="template_text",
        ),
        migrations.RemoveField(
            model_name="whatsappmessagetemplate",
            name="variable_names",
        ),
        migrations.AddField(
            model_name="whatsappmessagetemplate",
            name="description",
            field=models.TextField(
                blank=True, help_text="وصف اختياري للقالب", verbose_name="وصف/ملاحظات"
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="language",
            field=models.CharField(default="ar", max_length=10, verbose_name="اللغة"),
        ),
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("WELCOME", "ترحيب بعميل جديد"),
                    ("ORDER_CREATED", "تأكيد طلب"),
                    ("INSPECTION_SCHEDULED", "موعد معاينة"),
                    ("INSPECTION_COMPLETED", "اكتمال معاينة"),
                    ("INSTALLATION_SCHEDULED", "موعد تركيب"),
                    ("INSTALLATION_COMPLETED", "اكتمال تركيب"),
                    ("INVOICE", "فاتورة"),
                    ("CONTRACT", "عقد"),
                    ("CUSTOM", "مخصص"),
                ],
                help_text="كل نوع يمكن أن يكون له قالب واحد فقط",
                max_length=50,
                unique=True,
                verbose_name="نوع الرسالة",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="meta_template_name",
            field=models.CharField(
                help_text="اسم القالب المعتمد في Meta (مثل: customer_welcome, inspection_date)",
                max_length=100,
                verbose_name="اسم القالب في Meta",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="name",
            field=models.CharField(max_length=200, verbose_name="اسم القالب (للعرض)"),
        ),
    ]
