# Generated by Django 6.0 on 2026-01-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0021_simplify_template_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessagetemplate",
            name="test_variables",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='مثال: {"customer_name": "عميل تجريبي", "order_number": "TEST-001"}',
                verbose_name="متغيرات الاختبار",
            ),
        ),
    ]
