# Generated by Django 6.0 on 2026-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0022_add_test_variables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="enable_contract",
        ),
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="enable_inspection_completed",
        ),
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="enable_inspection_scheduled",
        ),
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="enable_installation_completed",
        ),
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="enable_installation_scheduled",
        ),
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="enable_invoice",
        ),
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="enable_order_created",
        ),
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="enable_welcome_messages",
        ),
        migrations.AddField(
            model_name="whatsappsettings",
            name="enabled_templates",
            field=models.ManyToManyField(
                blank=True,
                help_text="اختر القوالب التي تريد تفعيلها للإرسال التلقائي",
                to="whatsapp.whatsappmessagetemplate",
                verbose_name="القوالب المفعلة",
            ),
        ),
    ]
