# Generated by Django - Remove Twilio fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0024_initial_templates_data"),
    ]

    operations = [
        # إزالة حقول Twilio من WhatsAppSettings
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="api_provider",
        ),
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="account_sid",
        ),
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="auth_token",
        ),
    ]
