# Generated by Django 5.2.4 on 2025-07-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='يتم حسابه تلقائياً بناءً على نوع الطلب', null=True, verbose_name='تاريخ التسليم المتوقع'),
        ),
    ]
