# Generated by Django 4.2.21 on 2025-07-23 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ طلب المعاينة'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ تنفيذ المعاينة'),
        ),
    ]
