# Generated by Django 4.2.21 on 2025-07-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_companyinfo_header_logo_alter_companyinfo_logo"),
        ("customers", "0006_alter_customer_branch"),
        ("inspections", "0002_alter_inspection_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspections",
                to="accounts.branch",
                verbose_name="الفرع",
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspections",
                to="customers.customer",
                verbose_name="العميل",
            ),
        ),
    ]
