# Generated by Django 4.2.21 on 2025-08-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_invoicetemplate_accent_color_and_more'),
        ('inspections', '0003_alter_inspection_branch_alter_inspection_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='order',
            field=models.ForeignKey(blank=True, help_text='كل معاينة يجب أن تكون مرتبطة بطلب من قسم الطلبات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='orders.order', verbose_name='الطلب المرتبط'),
        ),
    ]
