# Generated by Django 4.2.21 on 2025-08-11 08:54

from django.db import migrations, models

import inspections.models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0004_alter_inspection_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="scheduled_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="وقت تنفيذ المعاينة"
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="inspection_file",
            field=models.FileField(
                blank=True,
                help_text="يجب أن يكون الملف من نوع PDF وأقل من 50 ميجابايت",
                null=True,
                upload_to="inspections/files/",
                validators=[inspections.models.validate_inspection_pdf_file],
                verbose_name="ملف المعاينة",
            ),
        ),
    ]
