# Generated by Django 4.2.21 on 2025-08-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_inspection_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'مكتمل السداد'), ('collect_on_visit', 'تحصيل عند العميل')], default='paid', max_length=20, verbose_name='حالة المديونية'),
        ),
    ]
