# Generated by Django 5.2.6 on 2025-09-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0007_alter_inspection_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="scheduled_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ تنفيذ المعاينة"
            ),
        ),
    ]
