# Generated by Django 5.2.6 on 2025-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0008_allow_null_scheduled_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_scheduled", "غير مجدولة"),
                    ("pending", "قيد الانتظار"),
                    ("scheduled", "مجدول"),
                    ("in_progress", "قيد التنفيذ"),
                    ("completed", "مكتملة"),
                    ("cancelled", "ملغية"),
                    ("postponed_by_customer", "مؤجل من طرف العميل"),
                ],
                default="pending",
                max_length=32,
                verbose_name="الحالة",
            ),
        ),
    ]
