# Generated by Django 5.1.5 on 2026-02-08 16:59

import django.db.models.deletion
import inspections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0012_inspection_deleted_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="يجب أن يكون الملف من نوع PDF وأقل من 50 ميجابايت",
                        upload_to="inspections/files/",
                        validators=[inspections.models.validate_inspection_pdf_file],
                        verbose_name="الملف",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="اسم الملف الأصلي"
                    ),
                ),
                (
                    "google_drive_file_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="معرف ملف Google Drive",
                    ),
                ),
                (
                    "google_drive_file_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="رابط ملف Google Drive"
                    ),
                ),
                (
                    "google_drive_file_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="اسم الملف في Google Drive",
                    ),
                ),
                (
                    "is_uploaded_to_drive",
                    models.BooleanField(
                        default=False, verbose_name="تم الرفع إلى Google Drive"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="ترتيب عرض الملف", verbose_name="الترتيب"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="inspections.inspection",
                        verbose_name="المعاينة",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف معاينة",
                "verbose_name_plural": "ملفات المعاينات",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["inspection"], name="insp_file_inspection_idx"
                    ),
                    models.Index(
                        fields=["is_uploaded_to_drive"], name="insp_file_uploaded_idx"
                    ),
                    models.Index(fields=["created_at"], name="insp_file_created_idx"),
                ],
            },
        ),
    ]
