# Generated by Django 5.1.15 on 2026-03-03 11:34

import inspections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0014_inspection_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="inspection_file",
            field=models.FileField(
                blank=True,
                help_text="يجب أن يكون الملف من نوع PDF وأقل من 50 ميجابايت",
                null=True,
                upload_to=inspections.models.inspection_main_file_upload_to,
                validators=[inspections.models.validate_inspection_pdf_file],
                verbose_name="ملف المعاينة",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionfile",
            name="file",
            field=models.FileField(
                help_text="يجب أن يكون الملف من نوع PDF وأقل من 50 ميجابايت",
                upload_to=inspections.models.inspection_additional_file_upload_to,
                validators=[inspections.models.validate_inspection_pdf_file],
                verbose_name="الملف",
            ),
        ),
    ]
