# Generated by Django 5.1.15 on 2026-03-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0014_alter_inspection_deleted_by"),
        ("inspections", "0015_alter_inspection_inspection_file_and_more"),
    ]

    operations = []
