# Generated by Django 5.2.4 on 2025-07-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedorder',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='extendedorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='fabricorder',
            name='extended_order',
        ),
        migrations.RemoveField(
            model_name='fabricorder',
            name='fabric_type',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending_approval', 'قيد الموافقة'), ('pending', 'قيد الانتظار'), ('in_progress', 'قيد التصنيع'), ('ready_install', 'جاهز للتركيب'), ('completed', 'مكتمل'), ('delivered', 'تم التسليم'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=30, verbose_name='حالة الطلب'),
        ),
        migrations.DeleteModel(
            name='AccessoryItem',
        ),
        migrations.DeleteModel(
            name='ExtendedOrder',
        ),
        migrations.DeleteModel(
            name='FabricOrder',
        ),
    ]
