# Generated by Django 5.2.4 on 2025-07-10 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_order_status_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending_approval', 'قيد الموافقة'), ('pending', 'قيد الانتظار'), ('in_progress', 'قيد التصنيع'), ('ready_install', 'جاهز للتركيب'), ('completed', 'مكتمل'), ('delivered', 'تم التسليم'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('manufacturing_deleted', 'أمر تصنيع محذوف')], default='pending', max_length=30, verbose_name='حالة الطلب'),
        ),
        migrations.CreateModel(
            name='ManufacturingDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturing_order_id', models.PositiveIntegerField(verbose_name='معرف أمر التصنيع المحذوف')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحذف')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الحذف')),
                ('manufacturing_order_data', models.JSONField(default=dict, verbose_name='بيانات أمر التصنيع المحذوف')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الحذف بواسطة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_deletion_logs', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'سجل حذف أمر تصنيع',
                'verbose_name_plural': 'سجلات حذف أوامر التصنيع',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
