# Generated by Django 5.2.4 on 2025-07-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_manufacturing_deletion_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('normal', 'طلب عادي'), ('vip', 'طلب VIP'), ('inspection', 'معاينة')], max_length=20, verbose_name='نوع الطلب')),
                ('delivery_days', models.PositiveIntegerField(help_text='عدد الأيام المتوقعة للتسليم', verbose_name='عدد أيام التسليم')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد موعد التسليم',
                'verbose_name_plural': 'إعدادات مواعيد التسليم',
                'ordering': ['order_type'],
                'unique_together': {('order_type',)},
            },
        ),
    ]
