# Generated by Django 4.2.21 on 2025-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_add_location_type_to_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="location_address",
            field=models.TextField(
                blank=True,
                help_text="عنوان التركيب بالتفصيل",
                null=True,
                verbose_name="عنوان التركيب",
            ),
        ),
    ]
