# Generated by Django 4.2.21 on 2025-07-23 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_add_location_address_to_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ الطلب"
            ),
        ),
    ]
