# Generated by Django 4.2.21 on 2025-08-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_contract_file_ordernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending_approval', 'قيد الموافقة'), ('pending', 'قيد الانتظار'), ('in_progress', 'قيد التصنيع'), ('ready_install', 'جاهز للتركيب'), ('completed', 'مكتمل'), ('delivered', 'تم التسليم'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('manufacturing_deleted', 'أمر تصنيع محذوف')], default='pending_approval', max_length=30, verbose_name='حالة الطلب'),
        ),
    ]
