# Generated by Django 4.2.21 on 2025-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_fix_order_status_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                help_text="يمكن إدخال قيم عشرية مثل 4.25 متر",
                max_digits=10,
                verbose_name="الكمية",
            ),
        ),
    ]
