# Generated by Django 4.2.21 on 2025-08-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatuslog",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "قيد الموافقة"),
                    ("pending", "قيد الانتظار"),
                    ("in_progress", "قيد التصنيع"),
                    ("ready_install", "جاهز للتركيب"),
                    ("completed", "مكتمل"),
                    ("delivered", "تم التسليم"),
                    ("rejected", "مرفوض"),
                    ("cancelled", "ملغي"),
                    ("manufacturing_deleted", "أمر تصنيع محذوف"),
                ],
                max_length=25,
                verbose_name="الحالة الجديدة",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="old_status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "قيد الموافقة"),
                    ("pending", "قيد الانتظار"),
                    ("in_progress", "قيد التصنيع"),
                    ("ready_install", "جاهز للتركيب"),
                    ("completed", "مكتمل"),
                    ("delivered", "تم التسليم"),
                    ("rejected", "مرفوض"),
                    ("cancelled", "ملغي"),
                    ("manufacturing_deleted", "أمر تصنيع محذوف"),
                ],
                max_length=25,
                verbose_name="الحالة السابقة",
            ),
        ),
    ]
