# Generated by Django 4.2.21 on 2025-08-21 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0023_update_order_status_log_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderModificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modification_type",
                    models.CharField(max_length=50, verbose_name="نوع التعديل"),
                ),
                (
                    "old_total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="المبلغ الإجمالي السابق",
                    ),
                ),
                (
                    "new_total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="المبلغ الإجمالي الجديد",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التعديل"
                    ),
                ),
                ("details", models.TextField(verbose_name="تفاصيل التعديل")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التعديل بواسطة",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modification_logs",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تعديل الطلب",
                "verbose_name_plural": "سجلات تعديل الطلبات",
                "ordering": ["-modified_at"],
                "indexes": [
                    models.Index(fields=["order"], name="order_mod_log_order_idx"),
                    models.Index(fields=["modified_at"], name="order_mod_log_date_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderItemModificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=50, verbose_name="اسم الحقل"),
                ),
                ("old_value", models.TextField(verbose_name="القيمة السابقة")),
                ("new_value", models.TextField(verbose_name="القيمة الجديدة")),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التعديل"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التعديل بواسطة",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modification_logs",
                        to="orders.orderitem",
                        verbose_name="عنصر الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تعديل عنصر الطلب",
                "verbose_name_plural": "سجلات تعديل عناصر الطلب",
                "ordering": ["-modified_at"],
                "indexes": [
                    models.Index(fields=["order_item"], name="item_mod_log_item_idx"),
                    models.Index(fields=["modified_at"], name="item_mod_log_date_idx"),
                ],
            },
        ),
    ]
