# Generated by Django 4.2.21 on 2025-08-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_ordermodificationlog_orderitemmodificationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="نسبة الخصم من 0% إلى 15%",
                max_digits=5,
                verbose_name="نسبة الخصم %",
            ),
        ),
    ]
