# Generated by Django 4.2.21 on 2025-08-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0025_orderitem_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="additional_quantity",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=10, verbose_name="كمية إضافية"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="bag_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم الشنطة"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cutter_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="اسم القصاص"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cutting_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ التقطيع"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cutting_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات التقطيع"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cutting_status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد الانتظار"),
                    ("in_progress", "قيد التقطيع"),
                    ("completed", "مكتمل"),
                    ("rejected", "مرفوض"),
                ],
                default="pending",
                max_length=20,
                verbose_name="حالة التقطيع",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="delivery_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ التسليم"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="permit_number",
            field=models.CharField(blank=True, max_length=50, verbose_name="رقم الإذن"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="receiver_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="اسم المستلم"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="سبب الرفض"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["cutting_status"], name="order_item_cutting_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["cutter_name"], name="order_item_cutter_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["receiver_name"], name="order_item_receiver_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["cutting_date"], name="order_item_cutting_date_idx"
            ),
        ),
    ]
