# Generated by Django 4.2.21 on 2025-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_orderitem_additional_quantity_orderitem_bag_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("accessory", "إكسسوار"),
                    ("installation", "تركيب"),
                    ("inspection", "معاينة"),
                    ("tailoring", "تسليم"),
                    ("products", "منتجات"),
                ],
                default="accessory",
                max_length=20,
                verbose_name="نوع الطلب",
            ),
        ),
    ]
