# Generated by Django 4.2.21 on 2025-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_auto_20250828_1952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                blank=True,
                choices=[("product", "منتج"), ("service", "خدمة")],
                max_length=10,
                null=True,
            ),
        ),
    ]
