# Generated by Django 5.2.6 on 2025-09-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_alter_order_order_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_auto_update",
            field=models.BooleanField(
                default=False,
                help_text="إشارة للتحديثات التلقائية لمنع التسجيل المكرر",
                verbose_name="تحديث تلقائي",
            ),
        ),
    ]
