# Generated by Django 5.2.6 on 2025-09-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0029_add_is_auto_update_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodificationlog",
            name="is_manual_modification",
            field=models.BooleanField(
                default=False,
                help_text="إذا كان هذا التعديل تم بواسطة المستخدم مباشرة وليس تلقائياً",
                verbose_name="تعديل يدوي",
            ),
        ),
        migrations.AddField(
            model_name="ordermodificationlog",
            name="modified_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="قاموس يحتوي على الحقول المعدلة وقيمها السابقة والجديدة",
                verbose_name="الحقول المعدلة",
            ),
        ),
    ]
