# Generated by Django 5.2.6 on 2025-09-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0030_ordermodificationlog_is_manual_modification_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverytimesettings",
            options={
                "ordering": ["order_type", "service_type", "customer_type"],
                "verbose_name": "إعداد موعد التسليم",
                "verbose_name_plural": "إعدادات مواعيد التسليم",
            },
        ),
        migrations.AlterUniqueTogether(
            name="deliverytimesettings",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="deliverytimesettings",
            name="customer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual", "فردي"),
                    ("company", "شركة"),
                    ("government", "حكومي"),
                    ("vip", "VIP"),
                ],
                max_length=20,
                null=True,
                verbose_name="نوع العميل",
            ),
        ),
        migrations.AddField(
            model_name="deliverytimesettings",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accessory", "إكسسوار"),
                    ("products", "منتجات"),
                    ("installation", "تركيب"),
                    ("tailoring", "تسليم"),
                    ("fabric", "أقمشة"),
                    ("transport", "نقل"),
                ],
                max_length=20,
                null=True,
                verbose_name="نوع الخدمة",
            ),
        ),
        migrations.AlterField(
            model_name="deliverytimesettings",
            name="order_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("normal", "طلب عادي"),
                    ("vip", "طلب VIP"),
                    ("inspection", "معاينة"),
                ],
                max_length=20,
                null=True,
                verbose_name="نوع الطلب",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deliverytimesettings",
            unique_together={("order_type", "service_type", "customer_type")},
        ),
    ]
