# Generated by Django 5.2.6 on 2025-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0031_add_service_customer_types_to_delivery_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverytimesettings",
            options={
                "ordering": ["service_type", "order_type"],
                "verbose_name": "إعداد موعد التسليم",
                "verbose_name_plural": "إعدادات مواعيد التسليم",
            },
        ),
        migrations.AlterUniqueTogether(
            name="deliverytimesettings",
            unique_together={("order_type", "service_type")},
        ),
        migrations.AlterField(
            model_name="deliverytimesettings",
            name="order_type",
            field=models.CharField(
                blank=True,
                choices=[("normal", "طلب عادي"), ("vip", "طلب VIP")],
                max_length=20,
                null=True,
                verbose_name="نوع الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="deliverytimesettings",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accessory", "إكسسوار"),
                    ("products", "منتجات"),
                    ("installation", "تركيب"),
                    ("tailoring", "تسليم"),
                    ("inspection", "معاينة"),
                ],
                max_length=20,
                null=True,
                verbose_name="نوع الخدمة",
            ),
        ),
        migrations.RemoveField(
            model_name="deliverytimesettings",
            name="customer_type",
        ),
    ]
