# Generated by Django 5.2.6 on 2025-09-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0032_remove_customer_type_and_update_service_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatuslog",
            name="change_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="تفاصيل إضافية عن التغيير في صيغة JSON",
                verbose_name="تفاصيل التغيير",
            ),
        ),
        migrations.AddField(
            model_name="orderstatuslog",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("status", "تغيير حالة"),
                    ("customer", "تغيير عميل"),
                    ("price", "تغيير سعر"),
                    ("date", "تغيير تاريخ"),
                    ("manufacturing", "تحديث تصنيع"),
                    ("installation", "تحديث تركيب"),
                    ("payment", "تحديث دفع"),
                    ("general", "تحديث عام"),
                    ("creation", "إنشاء طلب"),
                ],
                default="status",
                max_length=20,
                verbose_name="نوع التغيير",
            ),
        ),
        migrations.AddField(
            model_name="orderstatuslog",
            name="is_automatic",
            field=models.BooleanField(
                default=False,
                help_text="هل هذا التغيير تم تلقائياً أم يدوياً",
                verbose_name="تغيير تلقائي",
            ),
        ),
    ]
