# Generated by Django 5.2.6 on 2025-10-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0033_add_detailed_status_log_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatuslog",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("status", "تغيير حالة"),
                    ("customer", "تغيير عميل"),
                    ("price", "تغيير سعر"),
                    ("date", "تغيير تاريخ"),
                    ("manufacturing", "تحديث تصنيع"),
                    ("installation", "تحديث تركيب"),
                    ("cutting", "تحديث تقطيع"),
                    ("inspection", "تحديث معاينة"),
                    ("complaint", "تحديث شكوى"),
                    ("payment", "تحديث دفع"),
                    ("general", "تحديث عام"),
                    ("creation", "إنشاء طلب"),
                ],
                default="status",
                max_length=20,
                verbose_name="نوع التغيير",
            ),
        ),
    ]
