# Generated by Django 5.2.6 on 2025-11-09 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0034_alter_orderstatuslog_change_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القالب")),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("standard", "قالب عادي"),
                            ("detailed", "قالب مفصل"),
                            ("minimal", "قالب مبسط"),
                            ("custom", "قالب مخصص"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="نوع القالب",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="اسم الشركة"),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contract_templates/logos/",
                        verbose_name="شعار الشركة",
                    ),
                ),
                (
                    "company_address",
                    models.TextField(blank=True, verbose_name="عنوان الشركة"),
                ),
                (
                    "company_phone",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="هاتف الشركة"
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="بريد الشركة"
                    ),
                ),
                (
                    "company_website",
                    models.URLField(blank=True, verbose_name="موقع الشركة"),
                ),
                (
                    "company_tax_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الرقم الضريبي"
                    ),
                ),
                (
                    "company_commercial_register",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="السجل التجاري"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#007bff",
                        help_text="اللون الأساسي للعقد (مثل: #007bff)",
                        max_length=7,
                        verbose_name="اللون الأساسي",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6c757d", max_length=7, verbose_name="اللون الثانوي"
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#ffc107", max_length=7, verbose_name="لون التمييز"
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="Arial, sans-serif",
                        max_length=100,
                        verbose_name="نوع الخط",
                    ),
                ),
                (
                    "font_size",
                    models.IntegerField(default=14, verbose_name="حجم الخط (px)"),
                ),
                (
                    "page_size",
                    models.CharField(
                        choices=[("A4", "A4"), ("Letter", "Letter")],
                        default="A4",
                        max_length=10,
                        verbose_name="حجم الصفحة",
                    ),
                ),
                (
                    "page_margins",
                    models.IntegerField(
                        default=20,
                        help_text="الهوامش حول محتوى العقد",
                        verbose_name="هوامش الصفحة (mm)",
                    ),
                ),
                (
                    "html_content",
                    models.TextField(
                        blank=True,
                        help_text="محتوى HTML مخصص للقالب (للمحرر المتقدم)",
                        verbose_name="محتوى HTML مخصص",
                    ),
                ),
                (
                    "css_styles",
                    models.TextField(
                        blank=True,
                        help_text="أنماط CSS إضافية للقالب",
                        verbose_name="أنماط CSS مخصصة",
                    ),
                ),
                (
                    "advanced_settings",
                    models.JSONField(
                        default=dict,
                        help_text="إعدادات متقدمة للقالب (JSON)",
                        verbose_name="إعدادات متقدمة",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="عدد مرات الاستخدام"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر استخدام"
                    ),
                ),
                (
                    "show_company_logo",
                    models.BooleanField(default=True, verbose_name="عرض شعار الشركة"),
                ),
                (
                    "show_order_details",
                    models.BooleanField(default=True, verbose_name="عرض تفاصيل الطلب"),
                ),
                (
                    "show_customer_details",
                    models.BooleanField(default=True, verbose_name="عرض بيانات العميل"),
                ),
                (
                    "show_items_table",
                    models.BooleanField(default=True, verbose_name="عرض جدول العناصر"),
                ),
                (
                    "show_payment_details",
                    models.BooleanField(default=True, verbose_name="عرض تفاصيل الدفع"),
                ),
                (
                    "show_terms",
                    models.BooleanField(
                        default=True, verbose_name="عرض الشروط والأحكام"
                    ),
                ),
                (
                    "show_signatures",
                    models.BooleanField(default=True, verbose_name="عرض التوقيعات"),
                ),
                (
                    "header_text",
                    models.TextField(
                        blank=True,
                        help_text="نص يظهر في أعلى العقد",
                        verbose_name="نص الرأس",
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True,
                        help_text="نص يظهر في أسفل العقد",
                        verbose_name="نص التذييل",
                    ),
                ),
                (
                    "terms_text",
                    models.TextField(
                        blank=True,
                        default="شروط وأحكام العقد...",
                        verbose_name="الشروط والأحكام",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب عقد",
                "verbose_name_plural": "قوالب العقود",
                "ordering": ["-is_default", "-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContractPrintLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "print_type",
                    models.CharField(
                        choices=[("auto", "طباعة تلقائية"), ("manual", "طباعة يدوية")],
                        default="manual",
                        max_length=10,
                        verbose_name="نوع الطباعة",
                    ),
                ),
                (
                    "printed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الطباعة"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_print_logs",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تمت الطباعة بواسطة",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.contracttemplate",
                        verbose_name="القالب المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل طباعة عقد",
                "verbose_name_plural": "سجلات طباعة العقود",
                "ordering": ["-printed_at"],
            },
        ),
    ]
