# Generated by Django 5.2.6 on 2025-11-09 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0035_add_contract_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractCurtain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(default=1, verbose_name="الترتيب")),
                (
                    "room_name",
                    models.CharField(max_length=100, verbose_name="اسم الغرفة"),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="بالمتر",
                        max_digits=10,
                        verbose_name="العرض",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="بالمتر",
                        max_digits=10,
                        verbose_name="الطول",
                    ),
                ),
                (
                    "curtain_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contract_curtains/",
                        verbose_name="صورة موديل الستارة",
                    ),
                ),
                (
                    "light_fabric_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="عدد أمتار القماش الخفيف",
                    ),
                ),
                (
                    "light_fabric_tailoring",
                    models.CharField(
                        blank=True,
                        choices=[("rings", "حلقات"), ("tape", "شريط"), ("snap", "كبس")],
                        max_length=20,
                        verbose_name="نوع تفصيل القماش الخفيف",
                    ),
                ),
                (
                    "light_fabric_tailoring_size",
                    models.CharField(
                        blank=True,
                        help_text="يُملأ في حالة اختيار شريط",
                        max_length=50,
                        verbose_name="مقاس التفصيل (للشريط)",
                    ),
                ),
                (
                    "heavy_fabric_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="عدد أمتار القماش الثقيل",
                    ),
                ),
                (
                    "heavy_fabric_tailoring",
                    models.CharField(
                        blank=True,
                        choices=[("rings", "حلقات"), ("tape", "شريط"), ("snap", "كبس")],
                        max_length=20,
                        verbose_name="نوع تفصيل القماش الثقيل",
                    ),
                ),
                (
                    "heavy_fabric_tailoring_size",
                    models.CharField(
                        blank=True,
                        help_text="يُملأ في حالة اختيار شريط",
                        max_length=50,
                        verbose_name="مقاس التفصيل (للشريط)",
                    ),
                ),
                (
                    "blackout_fabric_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="عدد أمتار البلاك أوت",
                    ),
                ),
                (
                    "blackout_fabric_tailoring",
                    models.CharField(
                        blank=True,
                        choices=[("rings", "حلقات"), ("tape", "شريط"), ("snap", "كبس")],
                        max_length=20,
                        verbose_name="نوع تفصيل البلاك أوت",
                    ),
                ),
                (
                    "blackout_fabric_tailoring_size",
                    models.CharField(
                        blank=True,
                        help_text="يُملأ في حالة اختيار شريط",
                        max_length=50,
                        verbose_name="مقاس التفصيل (للشريط)",
                    ),
                ),
                (
                    "wood_quantity",
                    models.IntegerField(default=0, verbose_name="عدد الخشب"),
                ),
                (
                    "wood_type",
                    models.CharField(
                        blank=True,
                        help_text="يُكتب يدوياً",
                        max_length=100,
                        verbose_name="نوع الخشب",
                    ),
                ),
                (
                    "track_quantity",
                    models.IntegerField(default=0, verbose_name="عدد المجرى"),
                ),
                (
                    "pipe_quantity",
                    models.IntegerField(default=0, verbose_name="عدد المواسير"),
                ),
                (
                    "bracket_quantity",
                    models.IntegerField(default=0, verbose_name="عدد الكوابيل"),
                ),
                (
                    "finial_quantity",
                    models.IntegerField(default=0, verbose_name="عدد النهايات"),
                ),
                (
                    "ring_quantity",
                    models.IntegerField(default=0, verbose_name="عدد الطبة"),
                ),
                (
                    "hanger_quantity",
                    models.IntegerField(default=0, verbose_name="عدد الشماعات"),
                ),
                (
                    "valance_quantity",
                    models.IntegerField(default=0, verbose_name="عدد الفرانشة"),
                ),
                (
                    "tassel_quantity",
                    models.IntegerField(default=0, verbose_name="عدد الشرابة"),
                ),
                (
                    "tieback_quantity",
                    models.IntegerField(default=0, verbose_name="عدد المرابط"),
                ),
                (
                    "belt_quantity",
                    models.IntegerField(default=0, verbose_name="عدد حزام الوسط"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات وشرح")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "belt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_belt",
                        to="orders.orderitem",
                        verbose_name="نوع حزام الوسط",
                    ),
                ),
                (
                    "blackout_fabric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_blackout",
                        to="orders.orderitem",
                        verbose_name="قماش بلاك أوت",
                    ),
                ),
                (
                    "bracket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_bracket",
                        to="orders.orderitem",
                        verbose_name="نوع الكوابيل",
                    ),
                ),
                (
                    "finial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_finial",
                        to="orders.orderitem",
                        verbose_name="نوع النهايات",
                    ),
                ),
                (
                    "hanger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_hanger",
                        to="orders.orderitem",
                        verbose_name="نوع الشماعات",
                    ),
                ),
                (
                    "heavy_fabric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_heavy",
                        to="orders.orderitem",
                        verbose_name="قماش ثقيل",
                    ),
                ),
                (
                    "light_fabric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_light",
                        to="orders.orderitem",
                        verbose_name="قماش خفيف",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_curtains",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "pipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_pipe",
                        to="orders.orderitem",
                        verbose_name="نوع المواسير",
                    ),
                ),
                (
                    "ring",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_ring",
                        to="orders.orderitem",
                        verbose_name="نوع الطبة",
                    ),
                ),
                (
                    "tassel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_tassel",
                        to="orders.orderitem",
                        verbose_name="نوع الشرابة",
                    ),
                ),
                (
                    "tieback_fabric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_tieback",
                        to="orders.orderitem",
                        verbose_name="نوع قماش المرابط",
                    ),
                ),
                (
                    "track_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_track",
                        to="orders.orderitem",
                        verbose_name="نوع المجرى",
                    ),
                ),
                (
                    "valance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_curtains_valance",
                        to="orders.orderitem",
                        verbose_name="نوع الفرانشة",
                    ),
                ),
            ],
            options={
                "verbose_name": "ستارة في العقد",
                "verbose_name_plural": "ستائر في العقد",
                "ordering": ["order", "sequence"],
                "unique_together": {("order", "sequence")},
            },
        ),
    ]
