# Generated by Django 5.2.6 on 2025-11-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0036_add_contract_curtains"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="contract_type",
            field=models.CharField(
                choices=[("electronic", "عقد إلكتروني"), ("uploaded", "رفع ملف عقد")],
                default="uploaded",
                help_text="اختر نوع العقد: إلكتروني (يتم توليده تلقائياً) أو رفع ملف",
                max_length=20,
                verbose_name="نوع العقد",
            ),
        ),
    ]
