# Generated by Django 5.2.6 on 2025-11-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0038_alter_order_contract_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="contract_type",
        ),
    ]
