# Generated by Django 5.2.6 on 2025-11-20 17:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_internalmessage"),
        ("customers", "0013_merge_0009_customeraccesslog_0012_merge_20250920_1318"),
        ("inspections", "0010_remove_in_progress_status"),
        ("inventory", "0010_bulkuploaderror_result_status_and_more"),
        ("orders", "0039_remove_order_contract_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_terms",
                    models.TextField(blank=True, null=True, verbose_name="شروط إضافية"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات العقد"
                    ),
                ),
            ],
            options={
                "verbose_name": "مسودة عقد",
                "verbose_name_plural": "مسودات العقود",
            },
        ),
        migrations.CreateModel(
            name="DraftCurtain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_name",
                    models.CharField(max_length=200, verbose_name="اسم الغرفة"),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="العرض (متر)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="الارتفاع (متر)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curtains",
                        to="orders.draftcontract",
                        verbose_name="مسودة العقد",
                    ),
                ),
            ],
            options={
                "verbose_name": "ستارة مسودة",
                "verbose_name_plural": "ستائر مسودات",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DraftAccessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accessory_name",
                    models.CharField(max_length=200, verbose_name="اسم الإكسسوار"),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft_curtain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessories",
                        to="orders.draftcurtain",
                        verbose_name="ستارة المسودة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إكسسوار مسودة",
                "verbose_name_plural": "إكسسوارات مسودات",
            },
        ),
        migrations.CreateModel(
            name="DraftFabric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fabric_type",
                    models.CharField(
                        choices=[
                            ("light", "خفيف"),
                            ("heavy", "ثقيل"),
                            ("blackout", "بلاك أوت"),
                        ],
                        max_length=20,
                        verbose_name="نوع القماش",
                    ),
                ),
                (
                    "fabric_name",
                    models.CharField(max_length=200, verbose_name="اسم القماش"),
                ),
                (
                    "pieces",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="عدد القطع",
                    ),
                ),
                (
                    "meters",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="عدد الأمتار",
                    ),
                ),
                (
                    "tailoring_type",
                    models.CharField(
                        blank=True,
                        choices=[("rings", "حلقات"), ("tape", "شريط"), ("snap", "كبس")],
                        max_length=20,
                        null=True,
                        verbose_name="نوع التفصيل",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft_curtain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fabrics",
                        to="orders.draftcurtain",
                        verbose_name="ستارة المسودة",
                    ),
                ),
            ],
            options={
                "verbose_name": "قماش مسودة",
                "verbose_name_plural": "أقمشة مسودات",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DraftOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        choices=[
                            (1, "البيانات الأساسية"),
                            (2, "نوع الطلب"),
                            (3, "عناصر الطلب"),
                            (4, "تفاصيل الفاتورة والدفع"),
                            (5, "العقد الإلكتروني"),
                            (6, "المراجعة والتأكيد"),
                        ],
                        default=1,
                        verbose_name="الخطوة الحالية",
                    ),
                ),
                (
                    "completed_steps",
                    models.JSONField(
                        default=list,
                        help_text="قائمة بأرقام الخطوات التي تم إكمالها",
                        verbose_name="الخطوات المكتملة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("normal", "عادي"), ("vip", "VIP")],
                        default="normal",
                        max_length=20,
                        verbose_name="وضع العميل",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "selected_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accessory", "إكسسوار"),
                            ("installation", "تركيب"),
                            ("inspection", "معاينة"),
                            ("tailoring", "تسليم"),
                            ("products", "منتجات"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="نوع الطلب",
                    ),
                ),
                (
                    "related_inspection_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inspection", "معاينة محددة"),
                            ("customer_side", "طرف العميل"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="نوع المعاينة المرتبطة",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم الفاتورة الرئيسي",
                    ),
                ),
                (
                    "invoice_number_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم فاتورة إضافي 1",
                    ),
                ),
                (
                    "invoice_number_3",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم فاتورة إضافي 2",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم العقد الرئيسي",
                    ),
                ),
                (
                    "contract_number_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم عقد إضافي 1",
                    ),
                ),
                (
                    "contract_number_3",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم عقد إضافي 2",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدي"),
                            ("card", "بطاقة"),
                            ("bank_transfer", "تحويل بنكي"),
                            ("installment", "تقسيط"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="المبلغ المدفوع",
                    ),
                ),
                (
                    "payment_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات الدفع"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="المجموع قبل الخصم",
                    ),
                ),
                (
                    "total_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="إجمالي الخصم",
                    ),
                ),
                (
                    "final_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="المجموع النهائي",
                    ),
                ),
                (
                    "wizard_state",
                    models.JSONField(
                        default=dict,
                        help_text="بيانات مؤقتة إضافية للويزارد",
                        verbose_name="حالة الويزارد",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="تم تحويلها إلى طلب نهائي",
                        verbose_name="مكتملة",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإكمال"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_orders",
                        to="customers.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "final_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_draft",
                        to="orders.order",
                        verbose_name="الطلب النهائي",
                    ),
                ),
                (
                    "related_inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inspections.inspection",
                        verbose_name="المعاينة المرتبطة",
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.salesperson",
                        verbose_name="البائع",
                    ),
                ),
            ],
            options={
                "verbose_name": "مسودة طلب",
                "verbose_name_plural": "مسودات الطلبات",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="draftcontract",
            name="draft_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract",
                to="orders.draftorder",
                verbose_name="مسودة الطلب",
            ),
        ),
        migrations.CreateModel(
            name="DraftOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="سعر الوحدة",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="نسبة الخصم %",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("product", "منتج"),
                            ("fabric", "قماش"),
                            ("accessory", "إكسسوار"),
                        ],
                        default="product",
                        max_length=20,
                        verbose_name="نوع العنصر",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.draftorder",
                        verbose_name="مسودة الطلب",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر مسودة طلب",
                "verbose_name_plural": "عناصر مسودات الطلبات",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="draftorder",
            index=models.Index(
                fields=["created_by", "is_completed"],
                name="orders_draf_created_eac8ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="draftorder",
            index=models.Index(
                fields=["created_at"], name="orders_draf_created_4e5396_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftorder",
            index=models.Index(
                fields=["current_step"], name="orders_draf_current_56f3e0_idx"
            ),
        ),
    ]
