# Generated by Django 5.2.6 on 2025-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0040_draftcontract_draftcurtain_draftaccessory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftorder",
            name="contract_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="contracts/drafts/%Y/%m/",
                verbose_name="ملف العقد",
            ),
        ),
        migrations.AddField(
            model_name="draftorder",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[("electronic", "عقد إلكتروني"), ("pdf", "ملف PDF")],
                max_length=20,
                null=True,
                verbose_name="نوع العقد",
            ),
        ),
    ]
