# Generated by Django 5.2.6 on 2025-11-20 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0041_draftorder_contract_file_draftorder_contract_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="draftcontract",
            name="draft_order",
        ),
        migrations.RemoveField(
            model_name="draftcurtain",
            name="draft_contract",
        ),
        migrations.RemoveField(
            model_name="draftfabric",
            name="draft_curtain",
        ),
        migrations.AddField(
            model_name="contractcurtain",
            name="draft_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_curtains",
                to="orders.draftorder",
                verbose_name="مسودة الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="contractcurtain",
            name="blackout_fabric_tailoring",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rings", "حلقات"),
                    ("tape", "شريط"),
                    ("snap", "كبس"),
                    ("double_fold", "كسرة مزدوجة"),
                    ("triple_fold", "كسرة ثلاثية"),
                    ("pencil_pleat", "كسرة قلم"),
                    ("eyelet", "عراوي"),
                    ("tab_top", "عروة علوية"),
                ],
                max_length=20,
                verbose_name="نوع تفصيل البلاك أوت",
            ),
        ),
        migrations.AlterField(
            model_name="contractcurtain",
            name="heavy_fabric_tailoring",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rings", "حلقات"),
                    ("tape", "شريط"),
                    ("snap", "كبس"),
                    ("double_fold", "كسرة مزدوجة"),
                    ("triple_fold", "كسرة ثلاثية"),
                    ("pencil_pleat", "كسرة قلم"),
                    ("eyelet", "عراوي"),
                    ("tab_top", "عروة علوية"),
                ],
                max_length=20,
                verbose_name="نوع تفصيل القماش الثقيل",
            ),
        ),
        migrations.AlterField(
            model_name="contractcurtain",
            name="light_fabric_tailoring",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rings", "حلقات"),
                    ("tape", "شريط"),
                    ("snap", "كبس"),
                    ("double_fold", "كسرة مزدوجة"),
                    ("triple_fold", "كسرة ثلاثية"),
                    ("pencil_pleat", "كسرة قلم"),
                    ("eyelet", "عراوي"),
                    ("tab_top", "عروة علوية"),
                ],
                max_length=20,
                verbose_name="نوع تفصيل القماش الخفيف",
            ),
        ),
        migrations.AlterField(
            model_name="contractcurtain",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_curtains",
                to="orders.order",
                verbose_name="الطلب",
            ),
        ),
        migrations.CreateModel(
            name="CurtainAccessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accessory_name",
                    models.CharField(max_length=200, verbose_name="اسم الإكسسوار"),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="الكمية")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curtain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessories",
                        to="orders.contractcurtain",
                        verbose_name="الستارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إكسسوار الستارة",
                "verbose_name_plural": "إكسسوارات الستائر",
            },
        ),
        migrations.CreateModel(
            name="CurtainFabric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fabric_type",
                    models.CharField(
                        choices=[
                            ("light", "خفيف"),
                            ("heavy", "ثقيل"),
                            ("blackout", "بلاك أوت"),
                            ("additional", "إضافي"),
                        ],
                        max_length=20,
                        verbose_name="نوع القماش",
                    ),
                ),
                (
                    "fabric_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم القماش"
                    ),
                ),
                ("pieces", models.IntegerField(default=1, verbose_name="عدد القطع")),
                (
                    "meters",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="عدد الأمتار",
                    ),
                ),
                (
                    "tailoring_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rings", "حلقات"),
                            ("tape", "شريط"),
                            ("snap", "كبس"),
                            ("double_fold", "كسرة مزدوجة"),
                            ("triple_fold", "كسرة ثلاثية"),
                            ("pencil_pleat", "كسرة قلم"),
                            ("eyelet", "عراوي"),
                            ("tab_top", "عروة علوية"),
                        ],
                        max_length=20,
                        verbose_name="نوع التفصيل",
                    ),
                ),
                ("sequence", models.IntegerField(default=0, verbose_name="الترتيب")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curtain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fabrics",
                        to="orders.contractcurtain",
                        verbose_name="الستارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "قماش الستارة",
                "verbose_name_plural": "أقمشة الستائر",
                "ordering": ["curtain", "sequence"],
            },
        ),
        migrations.DeleteModel(
            name="DraftAccessory",
        ),
        migrations.DeleteModel(
            name="DraftContract",
        ),
        migrations.DeleteModel(
            name="DraftCurtain",
        ),
        migrations.DeleteModel(
            name="DraftFabric",
        ),
    ]
