# Generated by Django 5.2.6 on 2025-11-20 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0042_integrate_contract_with_wizard"),
    ]

    operations = [
        migrations.AddField(
            model_name="curtainfabric",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                help_text="القماش من عناصر الفاتورة",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curtain_fabrics",
                to="orders.orderitem",
                verbose_name="عنصر الفاتورة",
            ),
        ),
    ]
