# Generated by Django 5.2.6 on 2025-11-22 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0043_curtainfabric_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="curtainfabric",
            name="draft_order_item",
            field=models.ForeignKey(
                blank=True,
                help_text="القماش من عناصر مسودة الطلب",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curtain_fabrics",
                to="orders.draftorderitem",
                verbose_name="عنصر المسودة",
            ),
        ),
        migrations.AlterField(
            model_name="curtainfabric",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                help_text="القماش من عناصر الفاتورة النهائية",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curtain_fabrics",
                to="orders.orderitem",
                verbose_name="عنصر الفاتورة (النهائي)",
            ),
        ),
    ]
