# Generated by Django 5.2.6 on 2025-11-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0044_curtainfabric_draft_order_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curtainaccessory",
            name="color",
            field=models.CharField(blank=True, max_length=100, verbose_name="اللون"),
        ),
    ]
