# Generated by Django 5.2.6 on 2025-11-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0045_add_color_to_curtain_accessory"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractcurtain",
            name="installation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wall_gypsum", "حائط - جبس"),
                    ("wall_concrete", "حائط - مسلح"),
                    ("ceiling_gypsum", "سقف - جبس"),
                    ("ceiling_concrete", "سقف - مسلح"),
                ],
                max_length=20,
                verbose_name="نوع التركيب",
            ),
        ),
    ]
