# Generated by Django 5.2.6 on 2025-11-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0046_add_installation_type_to_curtain"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractcurtain",
            name="curtain_box_depth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="بالمتر - يُملأ عند اختيار بيت ستارة مسلح أو جبس",
                max_digits=10,
                null=True,
                verbose_name="عمق بيت الستارة",
            ),
        ),
        migrations.AddField(
            model_name="contractcurtain",
            name="curtain_box_width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="بالمتر - يُملأ عند اختيار بيت ستارة مسلح أو جبس",
                max_digits=10,
                null=True,
                verbose_name="عرض بيت الستارة",
            ),
        ),
        migrations.AlterField(
            model_name="contractcurtain",
            name="installation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wall_gypsum", "حائط - جبس"),
                    ("wall_concrete", "حائط - مسلح"),
                    ("ceiling_gypsum", "سقف - جبس"),
                    ("ceiling_concrete", "سقف - مسلح"),
                    ("curtain_box_concrete", "بيت ستارة مسلح"),
                    ("curtain_box_gypsum", "بيت ستارة جبس"),
                ],
                max_length=30,
                verbose_name="نوع التركيب",
            ),
        ),
    ]
