# Generated by Django 5.2.6 on 2025-11-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0047_add_curtain_box_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractcurtain",
            name="curtain_box_depth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="بالسنتيمتر - يُملأ عند اختيار بيت ستارة مسلح أو جبس",
                max_digits=10,
                null=True,
                verbose_name="عمق بيت الستارة (سم)",
            ),
        ),
        migrations.AlterField(
            model_name="contractcurtain",
            name="curtain_box_width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="بالسنتيمتر - يُملأ عند اختيار بيت ستارة مسلح أو جبس",
                max_digits=10,
                null=True,
                verbose_name="عرض بيت الستارة (سم)",
            ),
        ),
    ]
