# Generated by Django 5.2.6 on 2025-11-22 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_internalmessage"),
        ("orders", "0048_alter_contractcurtain_curtain_box_depth_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القالب")),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("standard", "عقد عادي"),
                            ("vip", "عقد VIP"),
                            ("tailoring", "عقد تفصيل"),
                            ("installation", "عقد تركيب"),
                            ("mixed", "عقد مختلط"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="نوع القالب",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "page_margin",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="هامش الصفحة (cm)",
                    ),
                ),
                (
                    "page_padding",
                    models.FloatField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="المساحة الداخلية (px)",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#a67c52",
                        help_text="مثال: #a67c52",
                        max_length=7,
                        verbose_name="اللون الأساسي",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#2980b9", max_length=7, verbose_name="اللون الثانوي"
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#d35400", max_length=7, verbose_name="لون التمييز"
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="Cairo", max_length=100, verbose_name="نوع الخط"
                    ),
                ),
                (
                    "base_font_size",
                    models.IntegerField(
                        default=9,
                        validators=[
                            django.core.validators.MinValueValidator(6),
                            django.core.validators.MaxValueValidator(16),
                        ],
                        verbose_name="حجم الخط الأساسي (px)",
                    ),
                ),
                (
                    "show_logo",
                    models.BooleanField(default=True, verbose_name="عرض الشعار"),
                ),
                (
                    "logo_position",
                    models.CharField(
                        choices=[
                            ("left", "يسار"),
                            ("right", "يمين"),
                            ("center", "وسط"),
                        ],
                        default="left",
                        max_length=20,
                        verbose_name="موضع الشعار",
                    ),
                ),
                (
                    "logo_width",
                    models.IntegerField(default=60, verbose_name="عرض الشعار (px)"),
                ),
                (
                    "logo_height",
                    models.IntegerField(default=60, verbose_name="ارتفاع الشعار (px)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True,
                        help_text="الفروع المسموح لها باستخدام هذا القالب",
                        related_name="dynamic_contract_templates",
                        to="accounts.branch",
                        verbose_name="الفروع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dynamic_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المنشئ",
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب عقد ديناميكي",
                "verbose_name_plural": "قوالب العقود الديناميكية",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("header", "الترويسة"),
                            ("customer_info", "بيانات العميل"),
                            ("order_info", "بيانات الطلب"),
                            ("curtain_details", "تفاصيل الستائر"),
                            ("curtain_header", "رأس الستارة"),
                            ("fabric_section", "بطاقة الأقمشة"),
                            ("accessories_section", "بطاقة الإكسسوارات"),
                            ("footer", "التذييل"),
                            ("custom", "قسم مخصص"),
                        ],
                        max_length=30,
                        verbose_name="نوع القسم",
                    ),
                ),
                (
                    "section_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="عنوان القسم"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="مرئي")),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="إجباري"),
                ),
                (
                    "width",
                    models.CharField(
                        default="100%",
                        help_text="مثال: 100%, 50%, 300px",
                        max_length=20,
                        verbose_name="العرض",
                    ),
                ),
                (
                    "min_height",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="الحد الأدنى للارتفاع (px)"
                    ),
                ),
                (
                    "padding",
                    models.CharField(
                        default="4px 5px",
                        help_text="مثال: 4px 5px أو 10px",
                        max_length=50,
                        verbose_name="المساحة الداخلية",
                    ),
                ),
                (
                    "margin",
                    models.CharField(
                        default="0",
                        help_text="مثال: 4px 0 أو 10px",
                        max_length=50,
                        verbose_name="الهامش الخارجي",
                    ),
                ),
                (
                    "border_width",
                    models.IntegerField(default=2, verbose_name="عرض الحد (px)"),
                ),
                (
                    "border_color",
                    models.CharField(
                        default="#a67c52", max_length=7, verbose_name="لون الحد"
                    ),
                ),
                (
                    "border_radius",
                    models.IntegerField(default=4, verbose_name="استدارة الحد (px)"),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff", max_length=7, verbose_name="لون الخلفية"
                    ),
                ),
                ("custom_html", models.TextField(blank=True, verbose_name="HTML مخصص")),
                ("custom_css", models.TextField(blank=True, verbose_name="CSS مخصص")),
                (
                    "display_conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='مثال: {"order_type": "vip", "has_fabrics": true}',
                        verbose_name="شروط العرض",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="orders.dynamiccontracttemplate",
                        verbose_name="القالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم القالب",
                "verbose_name_plural": "أقسام القالب",
                "ordering": ["template", "order"],
                "unique_together": {("template", "section_type", "order")},
            },
        ),
        migrations.CreateModel(
            name="TemplateSectionField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="اسم الحقل"),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "نص"),
                            ("number", "رقم"),
                            ("date", "تاريخ"),
                            ("badge", "بادج"),
                            ("image", "صورة"),
                            ("table", "جدول"),
                            ("list", "قائمة"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="نوع الحقل",
                    ),
                ),
                (
                    "field_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="تسمية الحقل"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        help_text="مثال: order.customer.name أو curtain.width",
                        max_length=200,
                        verbose_name="مصدر البيانات",
                    ),
                ),
                (
                    "default_value",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="القيمة الافتراضية"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="مرئي")),
                (
                    "font_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="حجم الخط (px)"
                    ),
                ),
                (
                    "font_weight",
                    models.IntegerField(
                        choices=[
                            (300, "خفيف"),
                            (400, "عادي"),
                            (600, "متوسط"),
                            (700, "سميك"),
                        ],
                        default=400,
                        verbose_name="وزن الخط",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#000000", max_length=7, verbose_name="اللون"
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("start", "يمين"),
                            ("center", "وسط"),
                            ("end", "يسار"),
                            ("space-between", "متباعد"),
                        ],
                        default="start",
                        max_length=20,
                        verbose_name="المحاذاة",
                    ),
                ),
                (
                    "flex",
                    models.CharField(
                        default="0 0 auto",
                        help_text="مثال: 1 أو 0 0 auto أو 0 1 50%",
                        max_length=20,
                        verbose_name="Flex",
                    ),
                ),
                (
                    "max_width",
                    models.CharField(
                        blank=True,
                        help_text="مثال: 150px أو 50%",
                        max_length=20,
                        verbose_name="الحد الأقصى للعرض",
                    ),
                ),
                (
                    "show_label",
                    models.BooleanField(default=True, verbose_name="عرض التسمية"),
                ),
                (
                    "text_transform",
                    models.CharField(
                        choices=[
                            ("none", "بدون"),
                            ("uppercase", "أحرف كبيرة"),
                            ("lowercase", "أحرف صغيرة"),
                            ("capitalize", "أول حرف كبير"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="تحويل النص",
                    ),
                ),
                (
                    "badge_color",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="لون البادج"
                    ),
                ),
                (
                    "badge_gradient",
                    models.CharField(
                        blank=True,
                        help_text="مثال: linear-gradient(135deg, #f1c40f 0%, #f9e79f 100%)",
                        max_length=200,
                        verbose_name="تدرج البادج",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="orders.templatesection",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حقل القسم",
                "verbose_name_plural": "حقول الأقسام",
                "ordering": ["section", "order"],
            },
        ),
        migrations.CreateModel(
            name="TemplateStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الكلاس"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="الوصف"),
                ),
                (
                    "css_properties",
                    models.JSONField(
                        default=dict,
                        help_text='مثال: {"font-size": "10px", "color": "#000"}',
                        verbose_name="خصائص CSS",
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(default=False, verbose_name="عام لكل القوالب"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="styles",
                        to="orders.dynamiccontracttemplate",
                        verbose_name="القالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمط CSS",
                "verbose_name_plural": "أنماط CSS",
            },
        ),
    ]
