# Generated by Django 5.2.6 on 2025-11-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0050_add_fabric_notes_and_cleanup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curtainaccessory",
            name="notes",
        ),
        migrations.AddField(
            model_name="curtainaccessory",
            name="size",
            field=models.CharField(blank=True, max_length=100, verbose_name="المقاس"),
        ),
    ]
