# Generated by Django 5.2.6 on 2025-11-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0051_add_size_to_curtain_accessory"),
    ]

    operations = [
        migrations.AddField(
            model_name="curtainaccessory",
            name="draft_order_item",
            field=models.ForeignKey(
                blank=True,
                help_text="الإكسسوار من عناصر مسودة الطلب",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curtain_accessories",
                to="orders.draftorderitem",
                verbose_name="عنصر المسودة",
            ),
        ),
        migrations.AddField(
            model_name="curtainaccessory",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                help_text="الإكسسوار من عناصر الفاتورة النهائية",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curtain_accessories",
                to="orders.orderitem",
                verbose_name="عنصر الفاتورة (النهائي)",
            ),
        ),
        migrations.AlterField(
            model_name="curtainaccessory",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                help_text="الكمية الإجمالية (العدد × المقاس إن وُجد)",
                max_digits=10,
                verbose_name="الكمية",
            ),
        ),
    ]
