# Generated by Django 5.2.6 on 2025-11-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0053_update_accessory_count_size_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contracttemplate",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="ContractPrintLog",
        ),
        migrations.DeleteModel(
            name="ContractTemplate",
        ),
    ]
