# Generated by Django 5.2.6 on 2025-11-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0055_contracttemplate_contractprintlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftorder",
            name="customer_side_measurements",
            field=models.BooleanField(default=False, verbose_name="مقاسات طرف العميل"),
        ),
        migrations.AddField(
            model_name="draftorder",
            name="measurement_agreement_file",
            field=models.FileField(
                blank=True,
                help_text="يجب رفع ملف PDF لاتفاقية المقاسات",
                null=True,
                upload_to="measurements/agreements/%Y/%m/",
                verbose_name="اتفاقية المقاسات (PDF)",
            ),
        ),
    ]
