# Generated by Django 5.2.6 on 2025-11-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0056_add_customer_side_measurements"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="default",
                        max_length=20,
                        unique=True,
                        verbose_name="اسم الإعدادات",
                    ),
                ),
                (
                    "order_system",
                    models.CharField(
                        choices=[
                            ("wizard", "نظام الويزارد فقط"),
                            ("legacy", "النظام القديم فقط"),
                            ("both", "كلا النظامين"),
                        ],
                        default="both",
                        help_text="اختر النظام المستخدم لإنشاء الطلبات",
                        max_length=10,
                        verbose_name="نظام إنشاء الطلبات",
                    ),
                ),
                (
                    "edit_priority",
                    models.CharField(
                        choices=[
                            ("source", "حسب طريقة الإنشاء"),
                            ("wizard", "الويزارد دائماً"),
                            ("legacy", "النظام القديم دائماً"),
                        ],
                        default="source",
                        help_text="كيف يتم فتح الطلبات للتعديل",
                        max_length=10,
                        verbose_name="أولوية التعديل",
                    ),
                ),
                (
                    "hide_legacy_system",
                    models.BooleanField(
                        default=False,
                        help_text="إخفاء جميع أزرار ووظائف النظام القديم من الواجهة",
                        verbose_name="إخفاء النظام القديم",
                    ),
                ),
                (
                    "hide_wizard_system",
                    models.BooleanField(
                        default=False,
                        help_text="إخفاء جميع أزرار ووظائف نظام الويزارد من الواجهة",
                        verbose_name="إخفاء نظام الويزارد",
                    ),
                ),
                (
                    "allow_legacy_to_wizard_conversion",
                    models.BooleanField(
                        default=True,
                        help_text="السماح بتحويل الطلبات المنشأة بالنظام القديم إلى نظام الويزارد",
                        verbose_name="السماح بتحويل الطلبات القديمة",
                    ),
                ),
                (
                    "tailoring_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="قائمة بأنواع التفصيل التي يمكن اختيارها",
                        verbose_name="أنواع التفصيل المتاحة",
                    ),
                ),
                (
                    "fabric_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="قائمة بأنواع الأقمشة التي يمكن اختيارها",
                        verbose_name="أنواع الأقمشة المتاحة",
                    ),
                ),
                (
                    "installation_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="قائمة بأنواع التركيب التي يمكن اختيارها",
                        verbose_name="أنواع التركيب المتاحة",
                    ),
                ),
                (
                    "payment_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="قائمة بطرق الدفع التي يمكن اختيارها",
                        verbose_name="طرق الدفع المتاحة",
                    ),
                ),
                (
                    "require_contract_number",
                    models.BooleanField(
                        default=True,
                        help_text="جعل رقم العقد حقل إلزامي في طلبات التركيب والتسليم",
                        verbose_name="رقم العقد إلزامي",
                    ),
                ),
                (
                    "require_contract_file",
                    models.BooleanField(
                        default=False,
                        help_text="جعل رفع ملف العقد إلزامي",
                        verbose_name="ملف العقد إلزامي",
                    ),
                ),
                (
                    "enable_wizard_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="إرسال إشعارات عند إكمال خطوات الويزارد",
                        verbose_name="تفعيل إشعارات الويزارد",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "إعدادات النظام",
                "verbose_name_plural": "إعدادات النظام",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="creation_method",
            field=models.CharField(
                choices=[
                    ("wizard", "نظام الويزارد"),
                    ("legacy", "النظام القديم"),
                    ("api", "API"),
                    ("import", "استيراد"),
                ],
                default="legacy",
                help_text="الطريقة المستخدمة لإنشاء الطلب",
                max_length=20,
                verbose_name="طريقة الإنشاء",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="source_draft_id",
            field=models.IntegerField(
                blank=True,
                help_text="معرف مسودة الويزارد التي تم إنشاء الطلب منها",
                null=True,
                verbose_name="معرف المسودة",
            ),
        ),
    ]
