# Generated by Django 4.2.21 on 2025-11-24 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0069_fix_payment_notes_field"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wizardfieldoption",
            name="unique_field_type_value",
        ),
        migrations.RemoveIndex(
            model_name="wizardfieldoption",
            name="wizard_field_type_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="wizardfieldoption",
            name="wizard_field_type_seq_idx",
        ),
        migrations.AlterField(
            model_name="wizardglobalsettings",
            name="minimum_payment_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="نسبة الحد الأدنى المطلوب دفعه من إجمالي الطلب",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="الحد الأدنى للدفع (%)",
            ),
        ),
    ]
