# Generated by Django 5.2.6 on 2025-11-27 10:34

from django.db import migrations, models

import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0070_remove_wizardfieldoption_unique_field_type_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftorder",
            name="invoice_image",
            field=models.ImageField(
                blank=True,
                help_text="يجب إرفاق صورة الفاتورة (JPG, PNG, GIF, WEBP)",
                null=True,
                upload_to="invoices/images/drafts/%Y/%m/",
                verbose_name="صورة الفاتورة",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_image",
            field=models.ImageField(
                blank=True,
                help_text="يجب إرفاق صورة الفاتورة (JPG, PNG, GIF, WEBP) - أقل من 10 ميجابايت",
                null=True,
                upload_to="invoices/images/%Y/%m/",
                validators=[orders.models.validate_invoice_image],
                verbose_name="صورة الفاتورة",
            ),
        ),
    ]
