# Generated by Django 5.2.6 on 2025-11-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0072_invoice_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="curtainaccessory",
            name="accessory_type",
            field=models.CharField(
                blank=True,
                help_text="نوع الإكسسوار الشائع (مثل: حامل حائط 15 سنتم)",
                max_length=200,
                verbose_name="نوع الإكسسوار",
            ),
        ),
    ]
