# Generated by Django 5.2.6 on 2025-12-03 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_add_max_draft_orders_setting"),
        ("customers", "0013_merge_0009_customeraccesslog_0012_merge_20250920_1318"),
        ("inspections", "0010_remove_in_progress_status"),
        (
            "inventory",
            "0015_product_product_code_idx_product_product_name_idx_and_more",
        ),
        ("orders", "0073_add_accessory_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_status", "created_at"], name="order_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_status", "order_date"], name="order_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["installation_status", "order_status"],
                name="order_inst_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["branch", "order_status", "created_at"],
                name="order_branch_sts_crt_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "order_status"], name="order_cust_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["salesperson", "order_status", "created_at"],
                name="order_sales_sts_crt_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["is_fully_completed", "created_at"],
                name="order_completed_crt_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tracking_status", "created_at"], name="order_track_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_number"], name="order_number_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["invoice_number"], name="order_invoice_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["contract_number"], name="order_contract_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "item_type"], name="item_order_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "processing_status"], name="item_order_proc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["cutting_status", "cutting_date"], name="item_cut_sts_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["item_type", "processing_status"], name="item_type_proc_idx"
            ),
        ),
    ]
