# Generated by Django 5.2.6 on 2025-12-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0074_order_order_status_created_idx_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contractcurtain",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="contractcurtain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order__isnull", False)),
                fields=("order", "sequence"),
                name="unique_order_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractcurtain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("draft_order__isnull", False)),
                fields=("draft_order", "sequence"),
                name="unique_draft_order_sequence",
            ),
        ),
    ]
