# Generated by Django 5.2.6 on 2025-12-06 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_add_max_draft_orders_setting"),
        ("customers", "0013_merge_0009_customeraccesslog_0012_merge_20250920_1318"),
        ("inspections", "0010_remove_in_progress_status"),
        ("inventory", "0017_add_wizard_performance_indexes"),
        ("orders", "0075_fix_contractcurtain_unique_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="draftorder",
            new_name="draft_user_complete_idx",
            old_name="orders_draf_created_eac8ec_idx",
        ),
        migrations.RenameIndex(
            model_name="draftorder",
            new_name="draft_created_idx",
            old_name="orders_draf_created_4e5396_idx",
        ),
        migrations.RenameIndex(
            model_name="draftorder",
            new_name="draft_step_idx",
            old_name="orders_draf_current_56f3e0_idx",
        ),
        migrations.AddIndex(
            model_name="draftorder",
            index=models.Index(
                fields=["created_by", "is_completed", "-updated_at"],
                name="draft_user_comp_upd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="draftorder",
            index=models.Index(fields=["updated_at"], name="draft_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="draftorder",
            index=models.Index(
                fields=["customer", "is_completed"], name="draft_customer_comp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftorder",
            index=models.Index(
                fields=["branch", "is_completed"], name="draft_branch_comp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftorder",
            index=models.Index(
                fields=["salesperson", "is_completed"], name="draft_sales_comp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftorder",
            index=models.Index(
                fields=["selected_type", "is_completed"], name="draft_type_comp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftorder",
            index=models.Index(
                fields=["status", "is_completed"], name="draft_status_comp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftorder",
            index=models.Index(
                fields=["created_by", "is_completed", "current_step", "-updated_at"],
                name="draft_search_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="draftorderitem",
            index=models.Index(fields=["draft_order"], name="draftitem_draft_idx"),
        ),
        migrations.AddIndex(
            model_name="draftorderitem",
            index=models.Index(fields=["product"], name="draftitem_product_idx"),
        ),
        migrations.AddIndex(
            model_name="draftorderitem",
            index=models.Index(
                fields=["draft_order", "item_type"], name="draftitem_draft_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftorderitem",
            index=models.Index(
                fields=["draft_order", "product"], name="draftitem_draft_prod_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftorderitem",
            index=models.Index(fields=["item_type"], name="draftitem_type_idx"),
        ),
        migrations.AddIndex(
            model_name="draftorderitem",
            index=models.Index(fields=["created_at"], name="draftitem_created_idx"),
        ),
    ]
