# Generated by Django 6.0 on 2025-12-07 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0076_add_wizard_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="draftorder",
            name="edit_history",
            field=models.JSONField(
                default=list,
                help_text="سجل بجميع التعديلات على المسودة",
                verbose_name="سجل التعديلات",
            ),
        ),
        migrations.AddField(
            model_name="draftorder",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_drafts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="آخر تعديل بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="draftorderitem",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_draft_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أضيف بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="draftorderitem",
            name="modification_note",
            field=models.TextField(
                blank=True, null=True, verbose_name="ملاحظة التعديل"
            ),
        ),
        migrations.AddField(
            model_name="draftorderitem",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_draft_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="عُدل بواسطة",
            ),
        ),
    ]
