# Generated by Django 6.0 on 2025-12-22 12:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0077_draftorder_edit_history_draftorder_last_modified_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftorderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="يُحسب تلقائياً من الكمية والسعر ونسبة الخصم",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="مبلغ الخصم",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="financial_addition",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="إضافة مالية على الطلب (رسوم إضافية)",
                max_digits=10,
                verbose_name="إضافة مالية",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="used_customer_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ المستخدم من رصيد العميل",
                max_digits=10,
                verbose_name="رصيد العميل المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ المحسوب للخصم",
                max_digits=10,
                verbose_name="مبلغ الخصم",
            ),
        ),
    ]
