# Generated by Django 6.0 on 2025-12-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0078_sync_existing_discount_and_financial_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftorderitem",
            name="original_item_id",
            field=models.IntegerField(
                blank=True,
                help_text="يستخدم عند تعديل الطلب لربط عنصر المسودة بالعنصر الأصلي",
                null=True,
                verbose_name="معرف العنصر الأصلي",
            ),
        ),
    ]
