# Generated by Django 6.0 on 2026-01-10 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0079_draftorderitem_original_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftorder",
            name="original_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edit_drafts",
                to="orders.order",
                verbose_name="الطلب الأصلي المراد تعديله",
            ),
        ),
    ]
