# Generated by Django 6.0 on 2026-01-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0080_draftorder_original_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftorder",
            name="delivery_location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="موقع التسليم"
            ),
        ),
        migrations.AddField(
            model_name="draftorder",
            name="order_source_type",
            field=models.CharField(
                choices=[
                    ("manufacturing", "تحويل للمصنع"),
                    ("branch_delivery", "تسليم من الفرع"),
                ],
                default="manufacturing",
                max_length=30,
                verbose_name="مصدر الطلب",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="موقع التسليم"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_source_type",
            field=models.CharField(
                choices=[
                    ("manufacturing", "تحويل للمصنع"),
                    ("branch_delivery", "تسليم من الفرع"),
                ],
                default="manufacturing",
                max_length=30,
                verbose_name="مصدر الطلب",
            ),
        ),
    ]
