# Generated by Django 6.0 on 2026-01-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0081_draftorder_delivery_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="draftorder",
            name="order_source_type",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_source_type",
        ),
    ]
