# Generated by Django 6.0 on 2026-01-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0082_remove_draftorder_order_source_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wizardfieldoption",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("tailoring_type", "طريقة التفصيل"),
                    ("installation_type", "نوع التركيب"),
                    ("payment_method", "طريقة الدفع"),
                    ("order_status", "حالة الطلب"),
                    ("service_type", "نوع الخدمة"),
                    ("fabric_type", "نوع القماش"),
                    ("order_type", "نوع الطلب الرئيسي"),
                    ("curtain_style", "موديل الستارة"),
                    ("accessory_type", "نوع الإكسسوار"),
                ],
                help_text="نوع الحقل الذي ينتمي إليه هذا الخيار",
                max_length=50,
                verbose_name="نوع الحقل",
            ),
        ),
    ]
