# Generated by Django 6.0 on 2026-01-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0086_remove_redundant_tailoring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curtainfabric",
            name="fabric_type",
            field=models.CharField(max_length=50, verbose_name="نوع القماش"),
        ),
    ]
