# Generated by Django 6.0 on 2026-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0087_remove_fabric_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractcurtain",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="contractcurtain",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="contracttemplate",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="contracttemplate",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="curtainaccessory",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="curtainaccessory",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="curtainfabric",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="curtainfabric",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
    ]
