# Generated by Django 6.0 on 2026-01-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0088_contractcurtain_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderinvoiceimage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="orderinvoiceimage",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
    ]
