# Generated by Django 6.0 on 2026-01-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0090_contractcurtain_deleted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftorderitem",
            name="is_manual_price",
            field=models.BooleanField(
                default=False,
                help_text="هل تم تعديل سعر هذا العنصر يدوياً؟",
                verbose_name="سعر يدوي",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_manual_price",
            field=models.BooleanField(
                default=False,
                help_text="هل تم تعديل سعر هذا العنصر يدوياً؟",
                verbose_name="سعر يدوي",
            ),
        ),
    ]
