# Generated by Django 5.1.5 on 2026-02-07 13:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0091_draftorderitem_is_manual_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="draftorder",
            name="administrative_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="الخصم الإداري الإضافي على الطلب",
                max_digits=10,
                verbose_name="قيمة الخصم الإداري",
            ),
        ),
        migrations.AddField(
            model_name="draftorder",
            name="administrative_discount_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="draft_administrative_discounts_applied",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم الذي قام بالخصم الإداري",
            ),
        ),
        migrations.AddField(
            model_name="draftorder",
            name="administrative_discount_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الخصم الإداري"
            ),
        ),
        migrations.AddField(
            model_name="draftorder",
            name="administrative_discount_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="ملاحظات الخصم الإداري"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="administrative_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="الخصم الإداري الإضافي على الطلب",
                max_digits=10,
                verbose_name="قيمة الخصم الإداري",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="administrative_discount_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administrative_discounts_applied",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم الذي قام بالخصم الإداري",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="administrative_discount_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الخصم الإداري"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="administrative_discount_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="ملاحظات الخصم الإداري"
            ),
        ),
    ]
