# Generated by Django 5.1.5 on 2026-02-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_increase_decimal_capacity_for_bulk_upload"),
        ("orders", "0092_draftorder_administrative_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftorderitem",
            name="product_code_snapshot",
            field=models.CharField(
                blank=True,
                help_text="نسخة محفوظة من كود المنتج وقت إنشاء الطلب",
                max_length=100,
                null=True,
                verbose_name="كود المنتج (نسخة محفوظة)",
            ),
        ),
        migrations.AddField(
            model_name="draftorderitem",
            name="product_name_snapshot",
            field=models.CharField(
                blank=True,
                help_text="نسخة محفوظة من اسم المنتج وقت إنشاء الطلب",
                max_length=255,
                null=True,
                verbose_name="اسم المنتج (نسخة محفوظة)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_code_snapshot",
            field=models.CharField(
                blank=True,
                help_text="نسخة محفوظة من كود المنتج وقت إنشاء الطلب - لا تتأثر بالتعديلات",
                max_length=100,
                null=True,
                verbose_name="كود المنتج (نسخة محفوظة)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_name_snapshot",
            field=models.CharField(
                blank=True,
                help_text="نسخة محفوظة من اسم المنتج وقت إنشاء الطلب - لا تتأثر بالتعديلات",
                max_length=255,
                null=True,
                verbose_name="اسم المنتج (نسخة محفوظة)",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="inventory.product",
                verbose_name="المنتج",
            ),
        ),
    ]
