# Generated by Django 5.1.5 on 2026-02-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_increase_decimal_capacity_for_bulk_upload"),
        ("orders", "0093_draftorderitem_product_code_snapshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="inventory.product",
                verbose_name="المنتج",
            ),
        ),
    ]
