# Generated by Django 5.1.5 on 2026-02-09 17:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0019_alter_customer_customer_type"),
        ("orders", "0094_alter_orderitem_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ المخصص"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التخصيص"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "تخصيص دفعة",
                "verbose_name_plural": "تخصيصات الدفعات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="allocated_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="المبلغ المخصص",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="customers.customer",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("order", "دفعة طلب محدد"), ("general", "دفعة عامة")],
                default="order",
                max_length=20,
                verbose_name="نوع الدفعة",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="orders.order",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["customer"], name="payment_customer_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["payment_type"], name="payment_type_idx"),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_allocations",
                to="orders.order",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="orders.payment",
                verbose_name="الدفعة",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(fields=["payment"], name="alloc_payment_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(fields=["order"], name="alloc_order_idx"),
        ),
    ]
