# Generated by Django 5.1.5 on 2026-02-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0095_paymentallocation_payment_allocated_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="used_customer_balance",
        ),
    ]
