# Generated by Django 5.1.5 on 2026-02-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_user_user_branch_active_idx_and_more"),
        ("customers", "0022_alter_customer_branch"),
        ("orders", "0097_order_updated_by_ordermodificationlog_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="accounts.branch",
                verbose_name="الفرع",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_orders",
                to="customers.customer",
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="salesperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="accounts.salesperson",
                verbose_name="البائع",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="customers.customer",
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="orders.order",
                verbose_name="الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_allocations",
                to="orders.order",
                verbose_name="الطلب",
            ),
        ),
    ]
