# Generated by Django 5.1.15 on 2026-02-15 14:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0099_alter_order_paid_amount_alter_order_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="administrative_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="الخصم الإداري الإضافي على الطلب",
                max_digits=15,
                verbose_name="قيمة الخصم الإداري",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="final_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="السعر النهائي",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="financial_addition",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="إضافة مالية على الطلب (رسوم إضافية)",
                max_digits=15,
                verbose_name="إضافة مالية",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="المبلغ المدفوع",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="المبلغ الإجمالي",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="additional_quantity",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=12, verbose_name="كمية إضافية"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ المحسوب للخصم",
                max_digits=15,
                verbose_name="مبلغ الخصم",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                help_text="يمكن إدخال قيم عشرية مثل 4.25 متر",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="الكمية",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="سعر الوحدة",
            ),
        ),
        migrations.AlterField(
            model_name="ordermodificationlog",
            name="new_total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="المبلغ الإجمالي الجديد",
            ),
        ),
        migrations.AlterField(
            model_name="ordermodificationlog",
            name="old_total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="المبلغ الإجمالي السابق",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="allocated_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="المبلغ المخصص",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="المبلغ",
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="allocated_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="المبلغ المخصص"
            ),
        ),
    ]
