# Generated by Django 5.1.15 on 2026-02-28 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0101_remove_order_order_tracking_status_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessoryManufacturingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="مكتمل"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإكمال"
                    ),
                ),
                (
                    "item_status",
                    models.CharField(
                        choices=[("active", "نشط"), ("stopped", "متوقف - ناقص")],
                        default="active",
                        max_length=10,
                        verbose_name="حالة الصنف",
                    ),
                ),
                (
                    "stop_reason",
                    models.TextField(blank=True, verbose_name="سبب التوقف"),
                ),
                (
                    "stopped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التوقف"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "accessory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manufacturing_status",
                        to="orders.curtainaccessory",
                        verbose_name="الإكسسوار",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accessory_completions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإكمال بواسطة",
                    ),
                ),
                (
                    "stopped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accessory_stops",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التوقف بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "حالة تصنيع إكسسوار",
                "verbose_name_plural": "حالات تصنيع الإكسسوارات",
            },
        ),
        migrations.CreateModel(
            name="FabricManufacturingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_cut",
                    models.BooleanField(
                        default=False,
                        help_text="هل تم قص القماش؟",
                        verbose_name="تم القص",
                    ),
                ),
                (
                    "cut_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القص"
                    ),
                ),
                (
                    "is_height_filtered",
                    models.BooleanField(
                        default=False,
                        help_text="هل تمت تصفية ارتفاع القماش؟",
                        verbose_name="تم تصفية الارتفاع",
                    ),
                ),
                (
                    "height_filtered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ تصفية الارتفاع"
                    ),
                ),
                (
                    "is_quality_checked",
                    models.BooleanField(
                        default=False,
                        help_text="هل تم فحص جودة القماش؟",
                        verbose_name="تم فحص الجودة",
                    ),
                ),
                (
                    "quality_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ فحص الجودة"
                    ),
                ),
                (
                    "item_status",
                    models.CharField(
                        choices=[("active", "نشط"), ("stopped", "متوقف - ناقص")],
                        default="active",
                        max_length=10,
                        verbose_name="حالة الصنف",
                    ),
                ),
                (
                    "stop_reason",
                    models.TextField(
                        blank=True,
                        help_text="سبب توقف الصنف أو نقصه",
                        verbose_name="سبب التوقف",
                    ),
                ),
                (
                    "stopped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التوقف"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "cut_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fabric_cuts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم القص بواسطة",
                    ),
                ),
                (
                    "fabric",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manufacturing_status",
                        to="orders.curtainfabric",
                        verbose_name="القماش",
                    ),
                ),
                (
                    "height_filtered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fabric_height_filters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم تصفية الارتفاع بواسطة",
                    ),
                ),
                (
                    "quality_checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fabric_quality_checks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم فحص الجودة بواسطة",
                    ),
                ),
                (
                    "stopped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fabric_stops",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التوقف بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "حالة تصنيع قماش",
                "verbose_name_plural": "حالات تصنيع الأقمشة",
                "ordering": ["fabric__curtain__sequence", "fabric__sequence"],
            },
        ),
    ]
