# Generated by Django 5.1.15 on 2026-02-28 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0102_add_fabric_accessory_manufacturing_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessorymanufacturingstatus",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="accessorymanufacturingstatus",
            name="completed_by",
        ),
        migrations.RemoveField(
            model_name="accessorymanufacturingstatus",
            name="is_complete",
        ),
        migrations.AddField(
            model_name="accessorymanufacturingstatus",
            name="cut_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ القص/التجهيز"
            ),
        ),
        migrations.AddField(
            model_name="accessorymanufacturingstatus",
            name="cut_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessory_cuts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم القص/التجهيز بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="accessorymanufacturingstatus",
            name="height_filtered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ تصفية الارتفاع"
            ),
        ),
        migrations.AddField(
            model_name="accessorymanufacturingstatus",
            name="height_filtered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessory_height_filters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم تصفية الارتفاع بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="accessorymanufacturingstatus",
            name="is_cut",
            field=models.BooleanField(
                default=False,
                help_text="هل تم تجهيز/قص الإكسسوار؟",
                verbose_name="تم القص/التجهيز",
            ),
        ),
        migrations.AddField(
            model_name="accessorymanufacturingstatus",
            name="is_height_filtered",
            field=models.BooleanField(
                default=False,
                help_text="هل تمت تصفية ارتفاع الإكسسوار؟",
                verbose_name="تم تصفية الارتفاع",
            ),
        ),
        migrations.AddField(
            model_name="accessorymanufacturingstatus",
            name="is_quality_checked",
            field=models.BooleanField(
                default=False,
                help_text="هل تم فحص جودة الإكسسوار؟",
                verbose_name="تم فحص الجودة",
            ),
        ),
        migrations.AddField(
            model_name="accessorymanufacturingstatus",
            name="quality_checked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ فحص الجودة"
            ),
        ),
        migrations.AddField(
            model_name="accessorymanufacturingstatus",
            name="quality_checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessory_quality_checks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم فحص الجودة بواسطة",
            ),
        ),
    ]
