# Generated by Django 5.1.15 on 2026-03-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0094_alter_contracttemplate_deleted_by_and_more"),
        ("orders", "0103_accessory_3_checkboxes"),
    ]

    operations = []
