# Generated by Django 5.1.15 on 2026-03-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0104_merge_20260315_0100"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="modification_status",
            field=models.CharField(
                choices=[
                    ("none", "لا يوجد"),
                    ("pending", "بانتظار التعديل"),
                    ("in_progress", "قيد التعديل"),
                    ("completed", "تم التعديل"),
                ],
                db_index=True,
                default="none",
                max_length=20,
                verbose_name="حالة التعديل",
            ),
        ),
    ]
