# Generated by Django 5.1.15 on 2026-03-17 15:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0023_alter_customer_phone_alter_customer_phone2"),
        ("orders", "0105_orderitem_modification_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="draftorder",
            name="promo_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="قيمة خصم البرومو كود",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="promo_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="قيمة خصم البرومو كود",
            ),
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=10, unique=True, verbose_name="كود الخصم"
                    ),
                ),
                (
                    "discount_percentage",
                    models.PositiveSmallIntegerField(
                        help_text="نسبة الخصم من 1% إلى 15%",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(15),
                        ],
                        verbose_name="نسبة الخصم %",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعّال"),
                            ("used", "مُستخدم"),
                            ("expired", "منتهي الصلاحية"),
                            ("cancelled", "ملغي"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإصدار"),
                ),
                ("issue_notes", models.TextField(blank=True, verbose_name="ملاحظات الإصدار")),
                ("expires_at", models.DateTimeField(verbose_name="ينتهي في")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ الاستخدام"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ الإرسال"),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_promo_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="صادر من",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_promo_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُرسل بواسطة",
                    ),
                ),
                (
                    "sent_to_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_promo_codes",
                        to="customers.customer",
                        verbose_name="أُرسل للعميل",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_promo_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="استُخدم بواسطة",
                    ),
                ),
                (
                    "used_for_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_promo_codes",
                        to="customers.customer",
                        verbose_name="العميل المُستخدم له",
                    ),
                ),
                (
                    "used_in_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_promo_codes",
                        to="orders.order",
                        verbose_name="الطلب المُطبق فيه",
                    ),
                ),
            ],
            options={
                "verbose_name": "كود خصم",
                "verbose_name_plural": "أكواد الخصم",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.AddField(
            model_name="draftorder",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="draft_orders",
                to="orders.promocode",
                verbose_name="كود الخصم المُطبق",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.promocode",
                verbose_name="كود الخصم المُطبق",
            ),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(fields=["code", "status"], name="promo_code_status_idx"),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(fields=["status", "expires_at"], name="promo_status_exp_idx"),
        ),
    ]
