# Generated by Django 5.2.6 on 2025-11-27 19:08

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0025_internalmessage"),
        ("customers", "0013_merge_0009_customeraccesslog_0012_merge_20250920_1318"),
        ("orders", "0071_add_invoice_image_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم النوع")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("asset", "أصول"),
                            ("liability", "التزامات"),
                            ("equity", "حقوق ملكية"),
                            ("revenue", "إيرادات"),
                            ("expense", "مصروفات"),
                        ],
                        max_length=20,
                        verbose_name="التصنيف",
                    ),
                ),
                (
                    "code_prefix",
                    models.CharField(max_length=4, verbose_name="بادئة الكود"),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("debit", "مدين"), ("credit", "دائن")],
                        default="debit",
                        max_length=10,
                        verbose_name="الرصيد الطبيعي",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع الحساب",
                "verbose_name_plural": "أنواع الحسابات",
                "ordering": ["code_prefix"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="كود الحساب",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="اسم الحساب"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_system_account",
                    models.BooleanField(default=False, verbose_name="حساب نظام"),
                ),
                (
                    "allow_transactions",
                    models.BooleanField(default=True, verbose_name="يسمح بالقيود"),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الرصيد الافتتاحي",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الرصيد الحالي",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounting_accounts",
                        to="accounts.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_account",
                        to="customers.customer",
                        verbose_name="العميل المرتبط",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounting.account",
                        verbose_name="الحساب الأب",
                    ),
                ),
                (
                    "account_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="accounting.accounttype",
                        verbose_name="نوع الحساب",
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب",
                "verbose_name_plural": "دليل الحسابات",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccountingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_post_transactions",
                    models.BooleanField(
                        default=True, verbose_name="ترحيل القيود تلقائياً"
                    ),
                ),
                (
                    "require_transaction_approval",
                    models.BooleanField(
                        default=False, verbose_name="تتطلب موافقة على القيود"
                    ),
                ),
                (
                    "fiscal_year_start",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="بداية السنة المالية",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_advances_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="حساب سلف العملاء الافتراضي",
                    ),
                ),
                (
                    "default_bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="حساب البنك الافتراضي",
                    ),
                ),
                (
                    "default_cash_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="حساب الصندوق الافتراضي",
                    ),
                ),
                (
                    "default_receivables_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="حساب المدينين الافتراضي",
                    ),
                ),
                (
                    "default_revenue_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="حساب الإيرادات الافتراضي",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات المحاسبة",
                "verbose_name_plural": "إعدادات المحاسبة",
            },
        ),
        migrations.CreateModel(
            name="CustomerAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advance_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="رقم العربون",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المتبقي",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقداً"),
                            ("bank_transfer", "تحويل بنكي"),
                            ("check", "شيك"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم الإيصال"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("partially_used", "مستخدم جزئياً"),
                            ("fully_used", "مستخدم بالكامل"),
                            ("refunded", "مسترد"),
                            ("cancelled", "ملغي"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_advances",
                        to="accounts.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_advances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advances",
                        to="customers.customer",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "عربون/سلفة",
                "verbose_name_plural": "عربون وسلف العملاء",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdvanceUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="المبلغ المستخدم"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الاستخدام"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم بواسطة",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advance_usages",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="accounting.customeradvance",
                        verbose_name="العربون",
                    ),
                ),
            ],
            options={
                "verbose_name": "استخدام عربون",
                "verbose_name_plural": "استخدامات العربون",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerFinancialSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_orders_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الطلبات"),
                ),
                (
                    "total_orders_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي قيمة الطلبات",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي المدفوع",
                    ),
                ),
                (
                    "total_advances",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي العربون",
                    ),
                ),
                (
                    "remaining_advances",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="رصيد العربون المتبقي",
                    ),
                ),
                (
                    "total_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي المديونية",
                    ),
                ),
                (
                    "financial_status",
                    models.CharField(
                        choices=[
                            ("clear", "بريء الذمة"),
                            ("has_debt", "عليه مستحقات"),
                            ("has_credit", "له رصيد"),
                        ],
                        default="clear",
                        max_length=20,
                        verbose_name="الحالة المالية",
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ آخر دفعة"
                    ),
                ),
                (
                    "last_order_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ آخر طلب"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_summary",
                        to="customers.customer",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملخص مالي للعميل",
                "verbose_name_plural": "ملخصات مالية للعملاء",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="رقم القيد",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "دفعة من عميل"),
                            ("advance", "عربون/سلفة"),
                            ("invoice", "فاتورة مبيعات"),
                            ("refund", "استرداد"),
                            ("expense", "مصروف"),
                            ("transfer", "تحويل بين حسابات"),
                            ("adjustment", "تسوية"),
                            ("opening", "رصيد افتتاحي"),
                        ],
                        max_length=20,
                        verbose_name="نوع القيد",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("posted", "مرحّل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="التاريخ"
                    ),
                ),
                ("description", models.TextField(verbose_name="البيان")),
                (
                    "reference",
                    models.CharField(blank=True, max_length=100, verbose_name="المرجع"),
                ),
                (
                    "total_debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي المدين",
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي الدائن",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الترحيل"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounting_transactions",
                        to="accounts.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounting_transactions",
                        to="customers.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounting_transactions",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounting_transactions",
                        to="orders.payment",
                        verbose_name="الدفعة",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الترحيل بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "قيد محاسبي",
                "verbose_name_plural": "القيود المحاسبية",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="customeradvance",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advance",
                to="accounting.transaction",
                verbose_name="القيد المحاسبي",
            ),
        ),
        migrations.CreateModel(
            name="TransactionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="مدين",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="دائن",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, verbose_name="البيان"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_lines",
                        to="accounting.account",
                        verbose_name="الحساب",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.transaction",
                        verbose_name="القيد",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند القيد",
                "verbose_name_plural": "بنود القيد",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["code"], name="acc_code_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["name"], name="acc_name_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["account_type"], name="acc_type_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["customer"], name="acc_customer_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["is_active"], name="acc_active_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["transaction_number"], name="txn_number_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["transaction_type"], name="txn_type_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["date"], name="txn_date_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="txn_status_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["customer"], name="txn_customer_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["order"], name="txn_order_idx"),
        ),
        migrations.AddIndex(
            model_name="customeradvance",
            index=models.Index(fields=["customer"], name="adv_customer_idx"),
        ),
        migrations.AddIndex(
            model_name="customeradvance",
            index=models.Index(fields=["status"], name="adv_status_idx"),
        ),
    ]
