# Generated by Django 5.2.6 on 2025-12-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_add_comprehensive_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="account",
            name="acc_parent_idx",
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="acc_branch_idx",
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="acc_balance_idx",
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="acc_created_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="acc_type_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="acc_br_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="txn_debit_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="txn_credit_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="txn_created_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="txn_updated_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="txn_type_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="txn_status_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="txn_cust_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="txn_order_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="transactionline",
            name="txn_line_txn_idx",
        ),
        migrations.RemoveIndex(
            model_name="transactionline",
            name="txn_line_acc_idx",
        ),
        migrations.RemoveIndex(
            model_name="transactionline",
            name="txn_line_debit_idx",
        ),
        migrations.RemoveIndex(
            model_name="transactionline",
            name="txn_line_credit_idx",
        ),
        migrations.RemoveIndex(
            model_name="transactionline",
            name="txn_line_txn_acc_idx",
        ),
    ]
