# Generated by Django 4.2 on 2025-12-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0004_remove_account_acc_parent_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(db_index=True, max_length=200, verbose_name='اسم البنك')),
                ('bank_name_en', models.CharField(max_length=200, verbose_name='اسم البنك بالإنجليزية')),
                ('bank_logo', models.ImageField(blank=True, null=True, upload_to='bank_logos/', verbose_name='شعار البنك')),
                ('account_number', models.CharField(max_length=100, verbose_name='رقم الحساب')),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number', max_length=34, verbose_name='IBAN')),
                ('swift_code', models.CharField(blank=True, help_text='BIC/SWIFT Code', max_length=11, verbose_name='SWIFT Code')),
                ('branch', models.CharField(blank=True, max_length=200, verbose_name='الفرع')),
                ('branch_en', models.CharField(blank=True, max_length=200, verbose_name='Branch Name')),
                ('account_holder', models.CharField(default='الخواجة', max_length=200, verbose_name='اسم صاحب الحساب')),
                ('account_holder_en', models.CharField(default='Elkhawaga', max_length=200, verbose_name='Account Holder')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('qr_code_base64', models.TextField(blank=True, help_text='Cached QR code image', verbose_name='QR Code Base64')),
                ('unique_code', models.CharField(db_index=True, help_text='كود فريد للحساب البنكي (مثال: CIB001, NBE001)', max_length=20, unique=True, verbose_name='الكود الفريد')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('is_primary', models.BooleanField(default=False, help_text='الحساب الافتراضي للتحصيل', verbose_name='حساب رئيسي')),
                ('display_order', models.IntegerField(default=0, help_text='ترتيب عرض الحساب في القوائم', verbose_name='ترتيب العرض')),
                ('show_in_qr', models.BooleanField(default=True, help_text='عرض في صفحة جميع الحسابات', verbose_name='عرض في QR')),
                ('cloudflare_synced', models.BooleanField(default=False, verbose_name='متزامن مع Cloudflare')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_accounts', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('linked_account', models.ForeignKey(blank=True, help_text='الحساب المحاسبي الذي يمثل هذا الحساب البنكي', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account', verbose_name='الحساب المحاسبي المرتبط')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
                'ordering': ['display_order', 'bank_name'],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['unique_code'], name='accounting_b_unique__idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_active', 'display_order'], name='accounting_b_is_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_primary'], name='accounting_b_is_prim_idx'),
        ),
    ]
