# Generated by Django 6.0 on 2025-12-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_add_bank_accounts"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bankaccount",
            new_name="accounting__unique__062966_idx",
            old_name="accounting_b_unique__idx",
        ),
        migrations.RenameIndex(
            model_name="bankaccount",
            new_name="accounting__is_acti_ead156_idx",
            old_name="accounting_b_is_acti_idx",
        ),
        migrations.RenameIndex(
            model_name="bankaccount",
            new_name="accounting__is_prim_e0ce81_idx",
            old_name="accounting_b_is_prim_idx",
        ),
    ]
