# Generated by Django 6.0 on 2026-01-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0006_rename_accounting_b_unique__idx_accounting__unique__062966_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customeradvance",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "عربون",
                "verbose_name_plural": "عربون العملاء",
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("payment", "دفعة من عميل"),
                    ("advance", "عربون"),
                    ("invoice", "فاتورة مبيعات"),
                    ("refund", "استرداد"),
                    ("expense", "مصروف"),
                    ("transfer", "تحويل بين حسابات"),
                    ("adjustment", "تسوية"),
                    ("opening", "رصيد افتتاحي"),
                ],
                max_length=20,
                verbose_name="نوع القيد",
            ),
        ),
    ]
