# Generated by Django 5.1.5 on 2026-02-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_alter_customeradvance_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_customer_account",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="حساب عميل"
            ),
        ),
    ]
