# Generated by Django 5.1.5 on 2026-02-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_account_is_customer_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customeradvance",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="customeradvance",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="customeradvance",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customeradvance",
            name="transaction",
        ),
        migrations.RemoveField(
            model_name="accountingsettings",
            name="default_advances_account",
        ),
        migrations.DeleteModel(
            name="AdvanceUsage",
        ),
        migrations.DeleteModel(
            name="CustomerAdvance",
        ),
    ]
