# Generated by Django 5.1.5 on 2026-02-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_remove_customeradvance_branch_and_more"),
        ("customers", "0019_alter_customer_customer_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customerfinancialsummary",
            index=models.Index(fields=["customer"], name="cfs_customer_idx"),
        ),
        migrations.AddIndex(
            model_name="customerfinancialsummary",
            index=models.Index(fields=["total_debt"], name="cfs_debt_idx"),
        ),
        migrations.AddIndex(
            model_name="customerfinancialsummary",
            index=models.Index(fields=["financial_status"], name="cfs_status_idx"),
        ),
        migrations.AddIndex(
            model_name="customerfinancialsummary",
            index=models.Index(fields=["last_updated"], name="cfs_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="customerfinancialsummary",
            index=models.Index(fields=["last_payment_date"], name="cfs_last_pay_idx"),
        ),
        migrations.AddIndex(
            model_name="customerfinancialsummary",
            index=models.Index(
                fields=["financial_status", "total_debt"], name="cfs_status_debt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerfinancialsummary",
            index=models.Index(
                fields=["total_debt", "last_updated"], name="cfs_debt_upd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionline",
            index=models.Index(fields=["transaction"], name="txnline_txn_idx"),
        ),
        migrations.AddIndex(
            model_name="transactionline",
            index=models.Index(fields=["account"], name="txnline_acc_idx"),
        ),
        migrations.AddIndex(
            model_name="transactionline",
            index=models.Index(
                fields=["transaction", "account"], name="txnline_txn_acc_idx"
            ),
        ),
    ]
