# Generated by Django 5.1.5 on 2026-02-10 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date", "-created_at"],
                "permissions": [
                    ("can_post_transaction", "يمكنه ترحيل القيود المحاسبية"),
                    ("can_void_transaction", "يمكنه إلغاء القيود المحاسبية"),
                    ("can_approve_transaction", "يمكنه الموافقة على القيود المحاسبية"),
                    ("can_view_reports", "يمكنه عرض التقارير المالية"),
                    ("can_export_reports", "يمكنه تصدير التقارير المالية"),
                ],
                "verbose_name": "قيد محاسبي",
                "verbose_name_plural": "القيود المحاسبية",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الموافقة"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تمت الموافقة بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="accounting.account",
                verbose_name="الحساب الأب",
            ),
        ),
    ]
