# Generated by Django 5.1.5 on 2026-02-10 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0011_alter_transaction_options_transaction_approved_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="accounting/attachments/%Y/%m/", verbose_name="الملف"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="اسم الملف"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="وصف المرفق"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الرفع"),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="accounting.transaction",
                        verbose_name="القيد",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الرفع بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرفق القيد",
                "verbose_name_plural": "مرفقات القيود",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
