# Generated by Django 5.1.5 on 2026-02-10 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0012_add_transaction_attachment"),
        ("accounts", "0054_user_can_apply_administrative_discount"),
        ("customers", "0019_alter_customer_customer_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_customer_account", False)),
                fields=("name",),
                name="unique_non_customer_account_name",
            ),
        ),
    ]
