# Generated by Django 5.1.5 on 2026-02-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0014_transaction_updated_by"),
        ("customers", "0021_customer_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounting_account",
                to="customers.customer",
                verbose_name="العميل المرتبط",
            ),
        ),
        migrations.AlterField(
            model_name="customerfinancialsummary",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="financial_summary",
                to="customers.customer",
                verbose_name="العميل",
            ),
        ),
    ]
