# Generated by Django 4.2.21 on 2025-08-16 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان قصير للإشعار', max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(help_text='نص تفصيلي للإشعار', verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('customer_created', 'عميل جديد'), ('order_created', 'طلب جديد'), ('order_updated', 'تعديل طلب'), ('order_status_changed', 'تغيير حالة طلب'), ('order_delivered', 'تسليم طلب'), ('installation_scheduled', 'جدولة تركيب'), ('installation_completed', 'إكمال تركيب'), ('inspection_created', 'معاينة جديدة'), ('inspection_status_changed', 'تغيير حالة معاينة'), ('complaint_created', 'شكوى جديدة')], db_index=True, max_length=30, verbose_name='نوع الإشعار')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], db_index=True, default='normal', max_length=10, verbose_name='الأولوية')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='بيانات إضافية للإشعار في صيغة JSON', verbose_name='بيانات إضافية')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المحتوى')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_records', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_visibility', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رؤية الإشعار',
                'verbose_name_plural': 'رؤية الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_customer_notifications', models.BooleanField(default=True, verbose_name='إشعارات العملاء')),
                ('enable_order_notifications', models.BooleanField(default=True, verbose_name='إشعارات الطلبات')),
                ('enable_inspection_notifications', models.BooleanField(default=True, verbose_name='إشعارات المعاينات')),
                ('enable_installation_notifications', models.BooleanField(default=True, verbose_name='إشعارات التركيبات')),
                ('enable_complaint_notifications', models.BooleanField(default=True, verbose_name='إشعارات الشكاوى')),
                ('min_priority_level', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='low', help_text='لن يتم عرض الإشعارات أقل من هذا المستوى', max_length=10, verbose_name='الحد الأدنى لمستوى الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات الإشعارات',
                'verbose_name_plural': 'إعدادات الإشعارات',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='visible_to',
            field=models.ManyToManyField(related_name='visible_notifications', through='notifications.NotificationVisibility', to=settings.AUTH_USER_MODEL, verbose_name='مرئي لـ'),
        ),
        migrations.AddIndex(
            model_name='notificationvisibility',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_385ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationvisibility',
            index=models.Index(fields=['notification', 'user'], name='notificatio_notific_c1b0f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationvisibility',
            unique_together={('notification', 'user')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_3fc670_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx'),
        ),
    ]
