# Generated by Django 4.2.21 on 2025-08-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_remove_notificationsettings_enable_complaint_notifications_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationsettings",
            name="complaint_created_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="customer_created_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="inspection_created_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="inspection_status_changed_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="installation_completed_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="installation_scheduled_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="manufacturing_status_changed_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="notifications_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="order_created_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="order_delivered_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="order_status_changed_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="order_updated_enabled",
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="enable_complaint_notifications",
            field=models.BooleanField(default=True, verbose_name="إشعارات الشكاوى"),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="enable_customer_notifications",
            field=models.BooleanField(default=True, verbose_name="إشعارات العملاء"),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="enable_inspection_notifications",
            field=models.BooleanField(default=True, verbose_name="إشعارات المعاينات"),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="enable_installation_notifications",
            field=models.BooleanField(default=True, verbose_name="إشعارات التركيبات"),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="enable_order_notifications",
            field=models.BooleanField(default=True, verbose_name="إشعارات الطلبات"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("customer_created", "عميل جديد"),
                    ("order_created", "طلب جديد"),
                    ("order_updated", "تعديل طلب"),
                    ("order_status_changed", "تغيير حالة طلب"),
                    ("order_delivered", "تسليم طلب"),
                    ("installation_scheduled", "جدولة تركيب"),
                    ("installation_completed", "إكمال تركيب"),
                    ("inspection_created", "معاينة جديدة"),
                    ("inspection_status_changed", "تغيير حالة معاينة"),
                    ("complaint_created", "شكوى جديدة"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="نوع الإشعار",
            ),
        ),
    ]
