# Generated by Django 4.2.21 on 2025-08-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0003_remove_notificationsettings_complaint_created_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("customer_created", "عميل جديد"),
                    ("order_created", "طلب جديد"),
                    ("order_updated", "تعديل طلب"),
                    ("order_status_changed", "تغيير حالة طلب"),
                    ("order_delivered", "تسليم طلب"),
                    ("installation_scheduled", "جدولة تركيب"),
                    ("installation_completed", "إكمال تركيب"),
                    ("inspection_created", "معاينة جديدة"),
                    ("inspection_status_changed", "تغيير حالة معاينة"),
                    ("manufacturing_status_changed", "تغيير حالة أمر التصنيع"),
                    ("complaint_created", "شكوى جديدة"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="نوع الإشعار",
            ),
        ),
    ]
