# Generated by Django 5.1.5 on 2026-02-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("customer_created", "عميل جديد"),
                    ("order_created", "طلب جديد"),
                    ("order_updated", "تعديل طلب"),
                    ("order_status_changed", "تغيير حالة طلب"),
                    ("order_delivered", "تسليم طلب"),
                    ("installation_scheduled", "جدولة تركيب"),
                    ("installation_completed", "إكمال تركيب"),
                    ("inspection_created", "معاينة جديدة"),
                    ("inspection_status_changed", "تغيير حالة معاينة"),
                    ("manufacturing_status_changed", "تغيير حالة أمر التصنيع"),
                    ("complaint_created", "شكوى جديدة"),
                    ("complaint_status_changed", "تغيير حالة شكوى"),
                    ("complaint_assigned", "إسناد شكوى"),
                    ("complaint_escalated", "تصعيد شكوى"),
                    ("complaint_resolved", "حل شكوى"),
                    ("complaint_overdue", "تأخر شكوى"),
                    ("cutting_order_created", "أمر تقطيع جديد"),
                    ("cutting_completed", "اكتمال التقطيع"),
                    ("cutting_item_rejected", "رفض عنصر تقطيع"),
                    ("stock_shortage", "نقص في المخزون"),
                    ("fabric_received", "استلام أقمشة"),
                    ("cutting_ready_for_pickup", "جاهز للاستلام من التقطيع"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="نوع الإشعار",
            ),
        ),
    ]
