# Generated by Django 5.2.4 on 2025-07-14 12:15

import django.db.models.deletion
import installations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_deliverytimesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السائق')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الرخصة')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المركبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='التخصص')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فني',
                'verbose_name_plural': 'الفنيين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstallationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='تاريخ التركيب')),
                ('scheduled_time', models.TimeField(verbose_name='موعد التركيب')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('scheduled', 'مجدول'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('rescheduled', 'إعادة جدولة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'جدولة تركيب',
                'verbose_name_plural': 'جدولة التركيبات',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='InstallationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('remaining', 'المتبقي'), ('additional', 'إضافي'), ('refund', 'استرداد')], max_length=20, verbose_name='نوع الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='طريقة الدفع')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الإيصال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.installationschedule', verbose_name='التركيب')),
            ],
            options={
                'verbose_name': 'دفعة تركيب',
                'verbose_name_plural': 'مدفوعات التركيب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإكمال')),
                ('archive_notes', models.TextField(blank=True, verbose_name='ملاحظات الأرشفة')),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الأرشفة بواسطة')),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='installations.installationschedule', verbose_name='التركيب')),
            ],
            options={
                'verbose_name': 'أرشيف تركيب',
                'verbose_name_plural': 'أرشيف التركيبات',
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='InstallationTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفريق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.driver', verbose_name='السائق')),
                ('technicians', models.ManyToManyField(to='installations.technician', verbose_name='الفنيين')),
            ],
            options={
                'verbose_name': 'فريق تركيب',
                'verbose_name_plural': 'فرق التركيب',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='installationschedule',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.installationteam', verbose_name='الفريق'),
        ),
        migrations.CreateModel(
            name='ModificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to=installations.models.modification_report_path, verbose_name='ملف التقرير')),
                ('description', models.TextField(verbose_name='وصف التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.installationschedule', verbose_name='التركيب')),
            ],
            options={
                'verbose_name': 'تقرير تعديل',
                'verbose_name_plural': 'تقارير التعديل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to=installations.models.installation_receipt_path, verbose_name='صورة مذكرة الاستلام')),
                ('customer_signature', models.BooleanField(default=False, verbose_name='توقيع العميل')),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المستلم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='installations.installationschedule', verbose_name='التركيب')),
            ],
            options={
                'verbose_name': 'مذكرة استلام',
                'verbose_name_plural': 'مذكرات الاستلام',
            },
        ),
    ]
