# Generated by Django 4.2.21 on 2025-07-19 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "installations",
            "0003_installationeventlog_installationschedulingsettings_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="modificationerroranalysis",
            name="analyzed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم التحليل بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="modificationerroranalysis",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "منخفض"),
                    ("medium", "متوسط"),
                    ("high", "عالي"),
                    ("critical", "حرج"),
                ],
                default="medium",
                max_length=20,
                verbose_name="الشدة",
            ),
        ),
    ]
