# Generated by Django 5.2 on 2025-05-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0004_merge_0002_add_indexes_0003_auto_20250507_0639'),
    ]

    operations = [
        # تم تعديل الملف لتجنب محاولة إزالة فهارس غير موجودة
        # سنقوم بإضافة عملية فارغة بدلاً من ذلك
    ]
