# Generated by Django 4.2.21 on 2025-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0006_add_location_type_to_installationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationschedule',
            name='location_address',
            field=models.TextField(blank=True, help_text='عنوان التركيب بالتفصيل', null=True, verbose_name='عنوان التركيب'),
        ),
    ]
