# Generated by Django 4.2.21 on 2025-07-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0006_add_production_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationnote',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_notes', to='installations.installationnew', verbose_name='التركيب'),
        ),
    ]
