# Generated by Django 4.2.21 on 2025-07-03 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('installations', '0007_fix_notes_conflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationnew',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installations_new', to='orders.order', verbose_name='الطلب'),
        ),
    ]
