# Generated by Django 4.2.21 on 2025-08-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_add_indexes'),
        ('installations', '0007_add_location_address_to_installationschedule'),
    ]

    operations = [
    ]
