# Generated by Django 5.2.6 on 2025-09-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0009_technician_department"),
        ("orders", "0028_alter_order_order_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="installationschedule",
            constraint=models.UniqueConstraint(
                fields=("order",), name="unique_installation_per_order"
            ),
        ),
    ]
