# Generated by Django 5.2.6 on 2025-09-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0010_add_unique_installation_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installationschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("needs_scheduling", "بحاجة جدولة"),
                    ("scheduled", "مجدول"),
                    ("in_installation", "قيد التركيب"),
                    ("completed", "مكتمل"),
                    ("cancelled", "ملغي"),
                    ("modification_required", "يحتاج تعديل"),
                    ("modification_scheduled", "جدولة التعديل"),
                    ("modification_in_progress", "التعديل قيد التنفيذ"),
                    ("modification_completed", "التعديل مكتمل"),
                ],
                default="needs_scheduling",
                max_length=30,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="installationstatuslog",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("needs_scheduling", "بحاجة جدولة"),
                    ("scheduled", "مجدول"),
                    ("in_installation", "قيد التركيب"),
                    ("completed", "مكتمل"),
                    ("cancelled", "ملغي"),
                    ("modification_required", "يحتاج تعديل"),
                    ("modification_scheduled", "جدولة التعديل"),
                    ("modification_in_progress", "التعديل قيد التنفيذ"),
                    ("modification_completed", "التعديل مكتمل"),
                ],
                max_length=30,
                verbose_name="الحالة الجديدة",
            ),
        ),
        migrations.AlterField(
            model_name="installationstatuslog",
            name="old_status",
            field=models.CharField(
                choices=[
                    ("needs_scheduling", "بحاجة جدولة"),
                    ("scheduled", "مجدول"),
                    ("in_installation", "قيد التركيب"),
                    ("completed", "مكتمل"),
                    ("cancelled", "ملغي"),
                    ("modification_required", "يحتاج تعديل"),
                    ("modification_scheduled", "جدولة التعديل"),
                    ("modification_in_progress", "التعديل قيد التنفيذ"),
                    ("modification_completed", "التعديل مكتمل"),
                ],
                max_length=30,
                verbose_name="الحالة السابقة",
            ),
        ),
    ]
