# Generated by Django 5.2.6 on 2025-09-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0011_alter_installationschedule_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="installationschedule",
            name="windows_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="عدد الشبابيك المطلوبة للتركيب",
                null=True,
                verbose_name="عدد الشبابيك",
            ),
        ),
    ]
