# Generated by Django 5.2.6 on 2025-12-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0012_installationschedule_windows_count"),
        ("orders", "0073_add_accessory_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="installationschedule",
            index=models.Index(
                fields=["status", "scheduled_date"], name="inst_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installationschedule",
            index=models.Index(
                fields=["order", "status"], name="inst_order_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installationschedule",
            index=models.Index(
                fields=["team", "scheduled_date"], name="inst_team_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installationschedule",
            index=models.Index(
                fields=["status", "-created_at"], name="inst_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installationschedule",
            index=models.Index(
                fields=["scheduled_date", "status", "team"],
                name="inst_date_status_team_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="installationschedule",
            index=models.Index(
                fields=["-scheduled_date", "-scheduled_time"], name="inst_date_time_idx"
            ),
        ),
    ]
