# Generated by Django 5.2.6 on 2025-12-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0014_add_comprehensive_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="driver",
            name="driver_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="driver",
            name="driver_phone_idx",
        ),
        migrations.RemoveIndex(
            model_name="installationschedule",
            name="inst_updated_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="installationteam",
            name="inst_team_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="technician",
            name="technician_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="technician",
            name="technician_phone_idx",
        ),
        migrations.RemoveIndex(
            model_name="technician",
            name="technician_dept_idx",
        ),
    ]
