# Generated by Django 6.0 on 2026-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0015_remove_driver_driver_active_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="installationschedule",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="installationschedule",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="installationteam",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="installationteam",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorder",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorder",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="modificationrequest",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="modificationrequest",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محذوف"
            ),
        ),
    ]
