# Generated by Django 6.0 on 2026-01-27 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "installations",
            "0017_driver_deleted_by_installationschedule_deleted_by_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="installationschedule",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installations",
                to="installations.driver",
                verbose_name="السائق",
            ),
        ),
        migrations.AddField(
            model_name="installationschedule",
            name="technicians",
            field=models.ManyToManyField(
                blank=True,
                related_name="installations",
                to="installations.technician",
                verbose_name="الفنيين",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم المركبة (قديم)"
            ),
        ),
        migrations.AlterField(
            model_name="installationschedule",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="installations.installationteam",
                verbose_name="الفريق (قديم)",
            ),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="محذوف"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المركبة")),
                (
                    "plate_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم اللوحة"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=50, verbose_name="الموديل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("maintenance", "صيانة"),
                            ("inactive", "غير نشط"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "license_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ انتهاء الرخصة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حذف بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مركبة",
                "verbose_name_plural": "المركبات",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drivers",
                to="installations.vehicle",
                verbose_name="المركبة الافتراضية",
            ),
        ),
    ]
