# Generated by Django 6.0 on 2026-01-27 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0018_installationschedule_driver_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="محذوف"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "mission_type",
                    models.CharField(
                        choices=[
                            ("installation", "تركيب"),
                            ("custom", "مهمة خاصة"),
                            ("maintenance", "صيانة"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="نوع المهمة",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف المهمة"),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="وقت البدء"),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="وقت الانتهاء"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "معلق"),
                            ("active", "نشط"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_missions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حذف بواسطة",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missions",
                        to="installations.driver",
                        verbose_name="السائق",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_missions",
                        to="installations.installationschedule",
                        verbose_name="التركيب المرتبط",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missions",
                        to="installations.vehicle",
                        verbose_name="المركبة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة مركبة",
                "verbose_name_plural": "مهام المركبات",
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="VehicleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="محذوف"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                ("requested_date", models.DateField(verbose_name="التاريخ المطلوب")),
                (
                    "requested_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="الوقت المطلوب"
                    ),
                ),
                ("purpose", models.TextField(verbose_name="الغر")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "تمت الموافقة"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="سبب الرفض"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "assigned_mission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request",
                        to="installations.vehiclemission",
                        verbose_name="المهمة المرتبطة",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حذف بواسطة",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مقدم الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب مركبة",
                "verbose_name_plural": "طلبات المركبات",
                "ordering": ["-created_at"],
            },
        ),
    ]
