# Generated by Django 6.0 on 2026-01-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0020_installationpayment_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="chassis_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم الشاصي"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("truck", "سيارة نقل"),
                    ("van", "فان"),
                    ("car", "سيارة ملاكي"),
                    ("motorcycle", "دراجة نارية"),
                    ("other", "أخرى"),
                ],
                default="truck",
                max_length=20,
                verbose_name="نوع المركبة",
            ),
        ),
    ]
