# Generated by Django 6.0 on 2026-01-27 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0021_vehicle_chassis_number_vehicle_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="installationschedule",
            name="vehicle_mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_installations",
                to="installations.vehiclemission",
                verbose_name="مهمة المركبة المرتبطة",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemission",
            name="installation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_missions",
                to="installations.installationschedule",
                verbose_name="التركيب المرتبط (قديم)",
            ),
        ),
    ]
