# Generated by Django 5.1.5 on 2026-02-15 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0022_alter_customer_branch"),
        ("installations", "0023_installationschedule_updated_by_and_more"),
        ("orders", "0098_alter_order_branch_alter_order_customer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customerdebt",
            index=models.Index(
                fields=["customer", "is_paid"], name="inst_debt_cust_paid_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerdebt",
            index=models.Index(fields=["order"], name="inst_debt_order_idx"),
        ),
        migrations.AddIndex(
            model_name="customerdebt",
            index=models.Index(fields=["-created_at"], name="inst_debt_created_idx"),
        ),
        migrations.AddIndex(
            model_name="installationeventlog",
            index=models.Index(
                fields=["installation", "event_type"], name="instevt_inst_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installationeventlog",
            index=models.Index(fields=["-created_at"], name="instevt_created_idx"),
        ),
        migrations.AddIndex(
            model_name="installationpayment",
            index=models.Index(
                fields=["installation", "-created_at"], name="instpay_inst_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installationpayment",
            index=models.Index(fields=["payment_type"], name="instpay_type_idx"),
        ),
        migrations.AddIndex(
            model_name="installationstatuslog",
            index=models.Index(
                fields=["installation", "-created_at"], name="inststatlog_inst_crtd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingorder",
            index=models.Index(
                fields=["modification_request", "status"], name="instmfg_modreq_sts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingorder",
            index=models.Index(fields=["-created_at"], name="instmfg_created_idx"),
        ),
        migrations.AddIndex(
            model_name="modificationrequest",
            index=models.Index(
                fields=["installation", "priority"], name="modreq_inst_pri_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modificationrequest",
            index=models.Index(fields=["-created_at"], name="modreq_created_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclemission",
            index=models.Index(
                fields=["vehicle", "date"], name="vmission_veh_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclemission",
            index=models.Index(
                fields=["status", "date"], name="vmission_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclemission",
            index=models.Index(fields=["installation"], name="vmission_inst_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclerequest",
            index=models.Index(
                fields=["status", "-created_at"], name="vreq_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclerequest",
            index=models.Index(fields=["requester"], name="vreq_requester_idx"),
        ),
    ]
