# Generated by Django 5.1.15 on 2026-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0025_rename_manufacturing_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modificationmanufacturingorder",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "أمر تصنيع تعديل",
                "verbose_name_plural": "أوامر تصنيع التعديلات",
            },
        ),
        migrations.AlterField(
            model_name="installationpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="المبلغ"
            ),
        ),
        migrations.AlterModelTable(
            name="modificationmanufacturingorder",
            table="installations_manufacturingorder",
        ),
    ]
