# Generated by Django 5.1.15 on 2026-03-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0019_alter_driver_deleted_by_and_more"),
        ("installations", "0026_standardize_decimal_precision"),
    ]

    operations = []
