# Generated by Django 5.1.15 on 2026-03-15 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0023_alter_customer_phone_alter_customer_phone2"),
        ("installations", "0027_merge_20260315_0100"),
        ("manufacturing", "0038_merge_20260315_0100"),
        ("orders", "0105_orderitem_modification_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModificationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fabric_type",
                    models.CharField(
                        choices=[
                            ("light", "قماش خفيف"),
                            ("heavy", "قماش ثقيل"),
                            ("blackout", "بلاك أوت"),
                        ],
                        max_length=20,
                        verbose_name="نوع القماش",
                    ),
                ),
                ("modification_reason", models.TextField(verbose_name="سبب التعديل")),
                (
                    "fault_party",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("factory", "المصنع"),
                            ("salesperson", "البائع"),
                            ("customer", "العميل"),
                            ("installation", "التركيب"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="الجهة المسؤولة",
                    ),
                ),
                ("fault_details", models.TextField(blank=True, verbose_name="تفاصيل التحقيق")),
                (
                    "fault_resolved",
                    models.BooleanField(default=False, verbose_name="تم حسم المسؤولية"),
                ),
                (
                    "needs_manufacturing",
                    models.BooleanField(default=True, verbose_name="يحتاج تصنيع"),
                ),
                (
                    "new_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="اتركه فارغاً لاستخدام الكمية الأصلية",
                        max_digits=10,
                        null=True,
                        verbose_name="الكمية الجديدة (متر)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار التحقيق"),
                            ("investigating", "قيد التحقيق"),
                            ("approved", "تمت الموافقة للتصنيع"),
                            ("manufacturing", "قيد التصنيع"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث")),
            ],
            options={
                "verbose_name": "عنصر تعديل",
                "verbose_name_plural": "عناصر التعديل",
                "ordering": ["contract_curtain__sequence"],
            },
        ),
        migrations.AddField(
            model_name="modificationrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_modifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإنشاء بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="modificationrequest",
            name="investigated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigated_modifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم التحقيق بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="modificationrequest",
            name="investigation_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تاريخ التحقيق"),
        ),
        migrations.AddField(
            model_name="modificationrequest",
            name="investigation_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات التحقيق"),
        ),
        migrations.AddField(
            model_name="modificationrequest",
            name="investigation_status",
            field=models.CharField(
                choices=[
                    ("pending", "بانتظار التحقيق"),
                    ("in_progress", "قيد التحقيق"),
                    ("completed", "تم التحقيق"),
                ],
                default="pending",
                max_length=20,
                verbose_name="حالة التحقيق",
            ),
        ),
        migrations.AddField(
            model_name="modificationrequest",
            name="overall_fault_party",
            field=models.CharField(
                blank=True,
                choices=[
                    ("factory", "المصنع"),
                    ("salesperson", "البائع"),
                    ("customer", "العميل"),
                    ("installation", "التركيب"),
                    ("other", "أخرى"),
                ],
                max_length=20,
                verbose_name="الجهة المسؤولة",
            ),
        ),
        migrations.AddField(
            model_name="modificationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "جديد"),
                    ("investigating", "قيد التحقيق"),
                    ("approved", "تمت الموافقة"),
                    ("manufacturing", "قيد التصنيع"),
                    ("completed", "مكتمل"),
                    ("cancelled", "ملغي"),
                ],
                default="pending",
                max_length=20,
                verbose_name="حالة الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="modificationrequest",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modification_requests",
                to="customers.customer",
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="modificationrequest",
            name="installation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modification_requests",
                to="installations.installationschedule",
                verbose_name="التركيب",
            ),
        ),
        migrations.AddIndex(
            model_name="modificationrequest",
            index=models.Index(fields=["status"], name="modreq_status_idx"),
        ),
        migrations.AddIndex(
            model_name="modificationrequest",
            index=models.Index(fields=["customer", "-created_at"], name="modreq_cust_crtd_idx"),
        ),
        migrations.AddField(
            model_name="modificationitem",
            name="contract_curtain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modification_items",
                to="orders.contractcurtain",
                verbose_name="الستارة",
            ),
        ),
        migrations.AddField(
            model_name="modificationitem",
            name="manufacturing_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modification_source",
                to="manufacturing.manufacturingorderitem",
                verbose_name="عنصر أمر التصنيع",
            ),
        ),
        migrations.AddField(
            model_name="modificationitem",
            name="modification_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modification_items",
                to="installations.modificationrequest",
                verbose_name="طلب التعديل",
            ),
        ),
        migrations.AddField(
            model_name="modificationitem",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modification_items",
                to="orders.orderitem",
                verbose_name="عنصر الطلب الأصلي",
            ),
        ),
        migrations.AddIndex(
            model_name="modificationitem",
            index=models.Index(
                fields=["modification_request", "status"], name="moditem_req_sts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modificationitem",
            index=models.Index(fields=["order_item"], name="moditem_orderitem_idx"),
        ),
    ]
