# Generated by Django 5.1.15 on 2026-03-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0028_modificationitem_modificationrequest_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modificationrequest",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_investigate_modification", "يمكنه التحقيق واعتماد التعديلات")
                ],
                "verbose_name": "طلب تعديل",
                "verbose_name_plural": "طلبات التعديل",
            },
        ),
    ]
