# Generated by Django 5.1.15 on 2026-03-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory_accounting", "0019_add_view_factory_reports_permission"),
        ("installations", "0029_add_investigate_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="modificationrequest",
            name="tailor",
            field=models.ForeignKey(
                blank=True,
                help_text="الخياط الذي قام بتنفيذ التعديل",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modification_requests",
                to="factory_accounting.tailor",
                verbose_name="الخياط",
            ),
        ),
    ]
