# Generated by Django 4.2.21 on 2025-06-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_branch_branch_is_active_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('message_type', models.CharField(choices=[('welcome', 'رسالة ترحيبية'), ('goal', 'هدف'), ('announcement', 'إعلان'), ('holiday', 'إجازة')], default='announcement', max_length=20, verbose_name='نوع الرسالة')),
                ('color', models.CharField(default='primary', max_length=50, verbose_name='لون الرسالة')),
                ('icon', models.CharField(default='fas fa-bell', max_length=50, verbose_name='الأيقونة')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'رسالة الفرع',
                'verbose_name_plural': 'رسائل الفروع',
                'ordering': ['-created_at'],
            },
        ),
    ]
