# Generated by Django 4.2.21 on 2025-06-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_updated_at'),
        ('accounts', '0009_clean_migrations'),
        ('accounts', '0009_fix_branchmessage_color'),
    ]

    operations = [
    ]
